"object"!==typeof JSON&&(JSON={});
(function(){function l(h){return 10>h?"0"+h:h}function h(h){n.lastIndex=0;return n.test(h)?'"'+h.replace(n,function(h){var k=z[h];return"string"===typeof k?k:"\\u"+("0000"+h.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+h+'"'}function q(k,l){var n,z,P,fa,F=m,M,y=l[k];y&&("object"===typeof y&&"function"===typeof y.toJSON)&&(y=y.toJSON(k));"function"===typeof B&&(y=B.call(l,k,y));switch(typeof y){case "string":return h(y);case "number":return isFinite(y)?String(y):"null";case "boolean":case "null":return String(y);
case "object":if(!y)return"null";m+=t;M=[];if("[object Array]"===Object.prototype.toString.apply(y)){fa=y.length;for(n=0;n<fa;n+=1)M[n]=q(n,y)||"null";P=0===M.length?"[]":m?"[\n"+m+M.join(",\n"+m)+"\n"+F+"]":"["+M.join(",")+"]";m=F;return P}if(B&&"object"===typeof B){fa=B.length;for(n=0;n<fa;n+=1)"string"===typeof B[n]&&(z=B[n],(P=q(z,y))&&M.push(h(z)+(m?": ":":")+P))}else for(z in y)Object.prototype.hasOwnProperty.call(y,z)&&(P=q(z,y))&&M.push(h(z)+(m?": ":":")+P);P=0===M.length?"{}":m?"{\n"+m+M.join(",\n"+
m)+"\n"+F+"}":"{"+M.join(",")+"}";m=F;return P}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+l(this.getUTCMonth()+1)+"-"+l(this.getUTCDate())+"T"+l(this.getUTCHours())+":"+l(this.getUTCMinutes())+":"+l(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var k=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
n=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,m,t,z={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},B;"function"!==typeof JSON.stringify&&(JSON.stringify=function(h,k,n){var l;t=m="";if("number"===typeof n)for(l=0;l<n;l+=1)t+=" ";else"string"===typeof n&&(t=n);if((B=k)&&"function"!==typeof k&&("object"!==typeof k||"number"!==typeof k.length))throw Error("JSON.stringify");return q("",{"":h})});
"function"!==typeof JSON.parse&&(JSON.parse=function(h,q){function n(h,k){var l,m,t=h[k];if(t&&"object"===typeof t)for(l in t)Object.prototype.hasOwnProperty.call(t,l)&&(m=n(t,l),void 0!==m?t[l]=m:delete t[l]);return q.call(h,k,t)}var l;h=String(h);k.lastIndex=0;k.test(h)&&(h=h.replace(k,function(h){return"\\u"+("0000"+h.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(h.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return l=eval("("+h+")"),"function"===typeof q?n({"":l},""):l;throw new SyntaxError("JSON.parse");})})();
(function(l,h){function q(a){var b=a.length,c=d.type(a);return d.isWindow(a)?!1:1===a.nodeType&&b?!0:"array"===c||"function"!==c&&(0===b||"number"==typeof b&&0<b&&b-1 in a)}function k(){Object.defineProperty(this.cache={},0,{get:function(){return{}}});this.expando=d.expando+Math.random()}function n(a,b,c){var e;if(c===h&&1===a.nodeType)if(e="data-"+b.replace(kc,"-$1").toLowerCase(),c=a.getAttribute(e),"string"==typeof c){try{c="true"===c?!0:"false"===c?!1:"null"===c?null:+c+""===c?+c:lc.test(c)?JSON.parse(c):
c}catch(d){}G.set(a,b,c)}else c=h;return c}function m(){return!0}function t(){return!1}function z(){try{return x.activeElement}catch(a){}}function B(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function L(a,b,c){if(d.isFunction(b))return d.grep(a,function(a,d){return!!b.call(a,d,a)!==c});if(b.nodeType)return d.grep(a,function(a){return a===b!==c});if("string"==typeof b){if(mc.test(b))return d.filter(b,a,c);b=d.filter(b,a)}return d.grep(a,function(a){return 0<=xa.call(b,a)!==c})}function H(a,b){return d.nodeName(a,
"table")&&d.nodeName(1===b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function ic(a){return a.type=(null!==a.getAttribute("type"))+"/"+a.type,a}function jc(a){var b=nc.exec(a.type);return b?a.type=b[1]:a.removeAttribute("type"),a}function P(a,b){for(var c=a.length,e=0;c>e;e++)v.set(a[e],"globalEval",!b||v.get(b[e],"globalEval"))}function fa(a,b){var c,e,f,g,j,r;if(1===b.nodeType){if(v.hasData(a)&&(c=v.access(a),e=v.set(b,
c),r=c.events))for(f in delete e.handle,e.events={},r){c=0;for(e=r[f].length;e>c;c++)d.event.add(b,f,r[f][c])}G.hasData(a)&&(g=G.access(a),j=d.extend({},g),G.set(b,j))}}function F(a,b){var c=a.getElementsByTagName?a.getElementsByTagName(b||"*"):a.querySelectorAll?a.querySelectorAll(b||"*"):[];return b===h||b&&d.nodeName(a,b)?d.merge([a],c):c}function M(a,b){if(b in a)return b;for(var c=b.charAt(0).toUpperCase()+b.slice(1),e=b,d=lb.length;d--;)if(b=lb[d]+c,b in a)return b;return e}function y(a,b){return a=
b||a,"none"===d.css(a,"display")||!d.contains(a.ownerDocument,a)}function mb(a,b){for(var c,e,f,g=[],j=0,r=a.length;r>j;j++)e=a[j],e.style&&(g[j]=v.get(e,"olddisplay"),c=e.style.display,b?(g[j]||"none"!==c||(e.style.display=""),""===e.style.display&&y(e)&&(g[j]=v.access(e,"olddisplay",oc(e.nodeName)))):g[j]||(f=y(e),(c&&"none"!==c||!f)&&v.set(e,"olddisplay",f?c:d.css(e,"display"))));for(j=0;r>j;j++)e=a[j],e.style&&(b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[j]||"":"none"));
return a}function nb(a,b,c){return(a=pc.exec(b))?Math.max(0,a[1]-(c||0))+(a[2]||"px"):b}function ob(a,b,c,e,f){b=c===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===c&&(g+=d.css(a,c+ga[b],!0,f)),e?("content"===c&&(g-=d.css(a,"padding"+ga[b],!0,f)),"margin"!==c&&(g-=d.css(a,"border"+ga[b]+"Width",!0,f))):(g+=d.css(a,"padding"+ga[b],!0,f),"padding"!==c&&(g+=d.css(a,"border"+ga[b]+"Width",!0,f)));return g}function pb(a,b,c){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,
g=l.getComputedStyle(a,null),j=d.support.boxSizing&&"border-box"===d.css(a,"boxSizing",!1,g);if(0>=f||null==f){if(f=oa(a,b,g),(0>f||null==f)&&(f=a.style[b]),Qa.test(f))return f;e=j&&(d.support.boxSizingReliable||f===a.style[b]);f=parseFloat(f)||0}return f+ob(a,b,c||(j?"border":"content"),e,g)+"px"}function oc(a){var b=x,c=qb[a];return c||(c=rb(a,b),"none"!==c&&c||(sa=(sa||d("<iframe frameborder='0' width='0' height='0'/>").css("cssText","display:block !important")).appendTo(b.documentElement),b=(sa[0].contentWindow||
sa[0].contentDocument).document,b.write("<!doctype html><html><body>"),b.close(),c=rb(a,b),sa.detach()),qb[a]=c),c}function rb(a,b){var c=d(b.createElement(a)).appendTo(b.body),e=d.css(c[0],"display");return c.remove(),e}function Ra(a,b,c,e){var f;if(d.isArray(b))d.each(b,function(b,d){c||qc.test(a)?e(a,d):Ra(a+"["+("object"==typeof d?b:"")+"]",d,c,e)});else if(c||"object"!==d.type(b))e(a,b);else for(f in b)Ra(a+"["+f+"]",b[f],c,e)}function sb(a){return function(b,c){"string"!=typeof b&&(c=b,b="*");
var e,f=0,g=b.toLowerCase().match(V)||[];if(d.isFunction(c))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(c)):(a[e]=a[e]||[]).push(c)}}function tb(a,b,c,e){function f(r){var N;return g[r]=!0,d.each(a[r]||[],function(a,d){var r=d(b,c,e);return"string"!=typeof r||j||g[r]?j?!(N=r):h:(b.dataTypes.unshift(r),f(r),!1)}),N}var g={},j=a===Sa;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Ta(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)b[c]!==h&&((f[c]?a:e||(e={}))[c]=
b[c]);return e&&d.extend(!0,a,e),a}function ub(){return setTimeout(function(){pa=h}),pa=d.now()}function vb(a,b,c){for(var e,d=(ta[b]||[]).concat(ta["*"]),g=0,j=d.length;j>g;g++)if(e=d[g].call(c,b,a))return e}function wb(a,b,c){var e,f,g=0,j=ya.length,r=d.Deferred().always(function(){delete h.elem}),h=function(){if(f)return!1;for(var b=pa||ub(),b=Math.max(0,s.startTime+s.duration-b),c=1-(b/s.duration||0),e=0,d=s.tweens.length;d>e;e++)s.tweens[e].run(c);return r.notifyWith(a,[s,c,b]),1>c&&d?b:(r.resolveWith(a,
[s]),!1)},s=r.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{}},c),originalProperties:b,originalOptions:c,startTime:pa||ub(),duration:c.duration,tweens:[],createTween:function(b,c){var e=d.Tween(a,s.opts,b,c,s.opts.specialEasing[b]||s.opts.easing);return s.tweens.push(e),e},stop:function(b){var c=0,e=b?s.tweens.length:0;if(f)return this;for(f=!0;e>c;c++)s.tweens[c].run(1);return b?r.resolveWith(a,[s,b]):r.rejectWith(a,[s,b]),this}});b=s.props;c=s.opts.specialEasing;var u,p,
W,k;for(e in b)if(u=d.camelCase(e),p=c[u],W=b[e],d.isArray(W)&&(p=W[1],W=b[e]=W[0]),e!==u&&(b[u]=W,delete b[e]),k=d.cssHooks[u],k&&"expand"in k)for(e in W=k.expand(W),delete b[u],W)e in b||(b[e]=W[e],c[e]=p);else c[u]=p;for(;j>g;g++)if(e=ya[g].call(s,a,b,s.opts))return e;return d.map(b,vb,s),d.isFunction(s.opts.start)&&s.opts.start.call(a,s),d.fx.timer(d.extend(h,{elem:a,anim:s,queue:s.opts.queue})),s.progress(s.opts.progress).done(s.opts.done,s.opts.complete).fail(s.opts.fail).always(s.opts.always)}
function J(a,b,c,e,d){return new J.prototype.init(a,b,c,e,d)}function za(a,b){var c,e={height:a},d=0;for(b=b?1:0;4>d;d+=2-b)c=ga[d],e["margin"+c]=e["padding"+c]=a;return b&&(e.opacity=e.width=a),e}var xb,Aa,Ba=typeof h,sc=l.location,x=l.document,yb=x.documentElement,tc=l.jQuery,uc=l.$,Ca={},Da=[],zb=Da.concat,Ua=Da.push,ha=Da.slice,xa=Da.indexOf,vc=Ca.toString,Va=Ca.hasOwnProperty,wc="2.0.3".trim,d=function(a,b){return new d.fn.init(a,b,xb)},Ea=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,V=/\S+/g,
xc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]*))$/,Ab=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,yc=/^-ms-/,zc=/-([\da-z])/gi,Ac=function(a,b){return b.toUpperCase()},Fa=function(){x.removeEventListener("DOMContentLoaded",Fa,!1);l.removeEventListener("load",Fa,!1);d.ready()};d.fn=d.prototype={jquery:"2.0.3",constructor:d,init:function(a,b,c){var e,f;if(!a)return this;if("string"==typeof a){if(e="<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?[null,a,null]:xc.exec(a),!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):
this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:x,!0)),Ab.test(e[1])&&d.isPlainObject(b))for(e in b)d.isFunction(this[e])?this[e](b[e]):this.attr(e,b[e]);return this}return f=x.getElementById(e[2]),f&&f.parentNode&&(this.length=1,this[0]=f),this.context=x,this.selector=a,this}return a.nodeType?(this.context=this[0]=a,this.length=1,this):d.isFunction(a)?c.ready(a):(a.selector!==h&&(this.selector=a.selector,this.context=
a.context),d.makeArray(a,this))},selector:"",length:0,toArray:function(){return ha.call(this)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a){a=d.merge(this.constructor(),a);return a.prevObject=this,a.context=this.context,a},each:function(a,b){return d.each(this,a,b)},ready:function(a){return d.ready.promise().done(a),this},slice:function(){return this.pushStack(ha.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},
eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&b>a?[this[a]]:[])},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:Ua,sort:[].sort,splice:[].splice};d.fn.init.prototype=d.fn;d.extend=d.fn.extend=function(){var a,b,c,e,f,g,j=arguments[0]||{},r=1,N=arguments.length,s=!1;"boolean"==typeof j&&(s=j,j=arguments[1]||{},r=2);"object"==typeof j||d.isFunction(j)||(j={});for(N===
r&&(j=this,--r);N>r;r++)if(null!=(a=arguments[r]))for(b in a)c=j[b],e=a[b],j!==e&&(s&&e&&(d.isPlainObject(e)||(f=d.isArray(e)))?(f?(f=!1,g=c&&d.isArray(c)?c:[]):g=c&&d.isPlainObject(c)?c:{},j[b]=d.extend(s,g,e)):e!==h&&(j[b]=e));return j};d.extend({expando:"jQuery"+("2.0.3"+Math.random()).replace(/\D/g,""),noConflict:function(a){return l.$===d&&(l.$=uc),a&&l.jQuery===d&&(l.jQuery=tc),d},isReady:!1,readyWait:1,holdReady:function(a){a?d.readyWait++:d.ready(!0)},ready:function(a){(!0===a?--d.readyWait:
d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||(Aa.resolveWith(x,[d]),d.fn.trigger&&d(x).trigger("ready").off("ready")))},isFunction:function(a){return"function"===d.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?Ca[vc.call(a)]||"object":typeof a},isPlainObject:function(a){if("object"!==d.type(a)||a.nodeType||d.isWindow(a))return!1;
try{if(a.constructor&&!Va.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}return!0},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseHTML:function(a,b,c){if(!a||"string"!=typeof a)return null;"boolean"==typeof b&&(c=b,b=!1);b=b||x;var e=Ab.exec(a);c=!c&&[];return e?[b.createElement(e[1])]:(e=d.buildFragment([a],b,c),c&&d(c).remove(),d.merge([],e.childNodes))},parseJSON:JSON.parse,parseXML:function(a){var b,c;if(!a||"string"!=
typeof a)return null;try{c=new DOMParser,b=c.parseFromString(a,"text/xml")}catch(e){b=h}return(!b||b.getElementsByTagName("parsererror").length)&&d.error("Invalid XML: "+a),b},noop:function(){},globalEval:function(a){var b,c=eval;(a=d.trim(a))&&(1===a.indexOf("use strict")?(b=x.createElement("script"),b.text=a,x.head.appendChild(b).parentNode.removeChild(b)):c(a))},camelCase:function(a){return a.replace(yc,"ms-").replace(zc,Ac)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===
b.toLowerCase()},each:function(a,b,c){var e,d=0,g=a.length,j=q(a);if(c)if(j)for(;g>d&&!(e=b.apply(a[d],c),!1===e);d++);else for(d in a){if(e=b.apply(a[d],c),!1===e)break}else if(j)for(;g>d&&!(e=b.call(a[d],d,a[d]),!1===e);d++);else for(d in a)if(e=b.call(a[d],d,a[d]),!1===e)break;return a},trim:function(a){return null==a?"":wc.call(a)},makeArray:function(a,b){var c=b||[];return null!=a&&(q(Object(a))?d.merge(c,"string"==typeof a?[a]:a):Ua.call(c,a)),c},inArray:function(a,b,c){return null==b?-1:xa.call(b,
a,c)},merge:function(a,b){var c=b.length,e=a.length,d=0;if("number"==typeof c)for(;c>d;d++)a[e++]=b[d];else for(;b[d]!==h;)a[e++]=b[d++];return a.length=e,a},grep:function(a,b,c){var e,d=[],g=0,j=a.length;for(c=!!c;j>g;g++)e=!!b(a[g],g),c!==e&&d.push(a[g]);return d},map:function(a,b,c){var e,d=0,g=a.length,j=[];if(q(a))for(;g>d;d++)e=b(a[d],d,c),null!=e&&(j[j.length]=e);else for(d in a)e=b(a[d],d,c),null!=e&&(j[j.length]=e);return zb.apply([],j)},guid:1,proxy:function(a,b){var c,e,f;return"string"==
typeof b&&(c=a[b],b=a,a=c),d.isFunction(a)?(e=ha.call(arguments,2),f=function(){return a.apply(b||this,e.concat(ha.call(arguments)))},f.guid=a.guid=a.guid||d.guid++,f):h},access:function(a,b,c,e,f,g,j){var r=0,N=a.length,s=null==c;if("object"===d.type(c))for(r in f=!0,c)d.access(a,b,r,c[r],!0,g,j);else if(e!==h&&(f=!0,d.isFunction(e)||(j=!0),s&&(j?(b.call(a,e),b=null):(s=b,b=function(a,b,c){return s.call(d(a),c)})),b))for(;N>r;r++)b(a[r],c,j?e:e.call(a[r],r,b(a[r],c)));return f?a:s?b.call(a):N?b(a[0],
c):g},now:Date.now,swap:function(a,b,c,e){var d,g={};for(d in b)g[d]=a.style[d],a.style[d]=b[d];c=c.apply(a,e||[]);for(d in b)a.style[d]=g[d];return c}});d.ready.promise=function(a){return Aa||(Aa=d.Deferred(),"complete"===x.readyState?setTimeout(d.ready):(x.addEventListener("DOMContentLoaded",Fa,!1),l.addEventListener("load",Fa,!1))),Aa.promise(a)};d.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,b){Ca["[object "+b+"]"]=b.toLowerCase()});xb=d(x);var Wa=
l,A=function(a,b,c,e){var d,g,j,r,h;if((b?b.ownerDocument||b:$)!==K&&ia(b),b=b||K,c=c||[],!a||"string"!=typeof a)return c;if(1!==(r=b.nodeType)&&9!==r)return[];if(X&&!e){if(d=Bc.exec(a))if(j=d[1])if(9===r){if(g=b.getElementById(j),!g||!g.parentNode)return c;if(g.id===j)return c.push(g),c}else{if(b.ownerDocument&&(g=b.ownerDocument.getElementById(j))&&ua(b,g)&&g.id===j)return c.push(g),c}else{if(d[2])return aa.apply(c,b.getElementsByTagName(a)),c;if((j=d[3])&&C.getElementsByClassName&&b.getElementsByClassName)return aa.apply(c,
b.getElementsByClassName(j)),c}if(C.qsa&&(!O||!O.test(a))){if(g=d=I,j=b,h=9===r&&a,1===r&&"object"!==b.nodeName.toLowerCase()){r=Ga(a);(d=b.getAttribute("id"))?g=d.replace(Cc,"\\$&"):b.setAttribute("id",g);g="[id='"+g+"'] ";for(j=r.length;j--;)r[j]=g+Ha(r[j]);j=Xa.test(a)&&b.parentNode||b;h=r.join(",")}if(h)try{return aa.apply(c,j.querySelectorAll(h)),c}catch(s){}finally{d||b.removeAttribute("id")}}}var u;a:{a=a.replace(Ia,"$1");var p,k;g=Ga(a);if(!e&&1===g.length){if(u=g[0]=g[0].slice(0),2<u.length&&
"ID"===(p=u[0]).type&&C.getById&&9===b.nodeType&&X&&w.relative[u[1].type]){if(b=(w.find.ID(p.matches[0].replace(ba,ca),b)||[])[0],!b){u=c;break a}a=a.slice(u.shift().value.length)}for(r=Ja.needsContext.test(a)?0:u.length;r--&&!(p=u[r],w.relative[d=p.type]);)if((k=w.find[d])&&(e=k(p.matches[0].replace(ba,ca),Xa.test(u[0].type)&&b.parentNode||b))){if(u.splice(r,1),a=e.length&&Ha(u),!a){u=(aa.apply(c,e),c);break a}break}}u=(Ya(a,g)(e,b,!X,c,Xa.test(a)),c)}return u},Za=function(){function a(c,e){return b.push(c+=
" ")>w.cacheLength&&delete a[b.shift()],a[c]=e}var b=[];return a},T=function(a){return a[I]=!0,a},U=function(a){var b=K.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}},$a=function(a,b){for(var c=a.split("|"),e=a.length;e--;)w.attrHandle[c[e]]=b},Cb=function(a,b){var c=b&&a,e=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||Bb)-(~a.sourceIndex||Bb);if(e)return e;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1},Dc=function(a){return function(b){return"input"===
b.nodeName.toLowerCase()&&b.type===a}},Ec=function(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}},ja=function(a){return T(function(b){return b=+b,T(function(c,e){for(var d,g=a([],c.length,b),j=g.length;j--;)c[d=g[j]]&&(c[d]=!(e[d]=c[d]))})})},Db=function(){},Ga=function(a,b){var c,e,d,g,j,r,h;if(j=Eb[a+" "])return b?0:j.slice(0);j=a;r=[];for(h=w.preFilter;j;){(!c||(e=Fc.exec(j)))&&(e&&(j=j.slice(e[0].length)||j),r.push(d=[]));c=!1;(e=Gc.exec(j))&&
(c=e.shift(),d.push({value:c,type:e[0].replace(Ia," ")}),j=j.slice(c.length));for(g in w.filter)!(e=Ja[g].exec(j))||h[g]&&!(e=h[g](e))||(c=e.shift(),d.push({value:c,type:g,matches:e}),j=j.slice(c.length));if(!c)break}return b?j.length:j?A.error(a):Eb(a,r).slice(0)},Ha=function(a){for(var b=0,c=a.length,e="";c>b;b++)e+=a[b].value;return e},ab=function(a,b,c){var e=b.dir,d=c&&"parentNode"===e,g=Hc++;return b.first?function(b,c,g){for(;b=b[e];)if(1===b.nodeType||d)return a(b,c,g)}:function(b,c,h){var s,
u,p,k=Y+" "+g;if(h)for(;b=b[e];){if((1===b.nodeType||d)&&a(b,c,h))return!0}else for(;b=b[e];)if(1===b.nodeType||d)if(p=b[I]||(b[I]={}),(u=p[e])&&u[0]===k){if(!0===(s=u[1])||s===Ka)return!0===s}else if(u=p[e]=[k],u[1]=a(b,c,h)||Ka,!0===u[1])return!0}},bb=function(a){return 1<a.length?function(b,c,e){for(var d=a.length;d--;)if(!a[d](b,c,e))return!1;return!0}:a[0]},La=function(a,b,c,e,d){for(var g,j=[],r=0,h=a.length,s=null!=b;h>r;r++)(g=a[r])&&(!c||c(g,e,d))&&(j.push(g),s&&b.push(r));return j},cb=function(a,
b,c,e,d,g){return e&&!e[I]&&(e=cb(e)),d&&!d[I]&&(d=cb(d,g)),T(function(g,r,h,s){var u,p,k=[],q=[],n=r.length,l;if(!(l=g)){l=b||"*";for(var m=h.nodeType?[h]:h,t=[],z=0,v=m.length;v>z;z++)A(l,m[z],t);l=t}l=!a||!g&&b?l:La(l,k,a,h,s);m=c?d||(g?a:n||e)?[]:r:l;if(c&&c(l,m,h,s),e){u=La(m,q);e(u,[],h,s);for(h=u.length;h--;)(p=u[h])&&(m[q[h]]=!(l[q[h]]=p))}if(g){if(d||a){if(d){u=[];for(h=m.length;h--;)(p=m[h])&&u.push(l[h]=p);d(null,m=[],u,s)}for(h=m.length;h--;)(p=m[h])&&-1<(u=d?ka.call(g,p):k[h])&&(g[u]=
!(r[u]=p))}}else m=La(m===r?m.splice(n,m.length):m),d?d(null,r,m,s):aa.apply(r,m)})},db=function(a){var b,c,e,d=a.length,g=w.relative[a[0].type];c=g||w.relative[" "];for(var j=g?1:0,r=ab(function(a){return a===b},c,!0),h=ab(function(a){return-1<ka.call(b,a)},c,!0),s=[function(a,c,d){return!g&&(d||c!==Ma)||((b=c).nodeType?r(a,c,d):h(a,c,d))}];d>j;j++)if(c=w.relative[a[j].type])s=[ab(bb(s),c)];else{if(c=w.filter[a[j].type].apply(null,a[j].matches),c[I]){for(e=++j;d>e&&!w.relative[a[e].type];e++);return cb(1<
j&&bb(s),1<j&&Ha(a.slice(0,j-1).concat({value:" "===a[j-2].type?"*":""})).replace(Ia,"$1"),c,e>j&&db(a.slice(j,e)),d>e&&db(a=a.slice(e)),d>e&&Ha(a))}s.push(c)}return bb(s)},qa,C,Ka,w,Na,Fb,Ya,Ma,la,ia,K,Z,X,O,ma,Oa,ua,I="sizzle"+-new Date,$=Wa.document,Y=0,Hc=0,Gb=Za(),Eb=Za(),Hb=Za(),ra=!1,eb=function(a,b){return a===b?(ra=!0,0):0},Bb=-2147483648,Ic={}.hasOwnProperty,da=[],Jc=da.pop,Kc=da.push,aa=da.push,Ib=da.slice,ka=da.indexOf||function(a){for(var b=0,c=this.length;c>b;b++)if(this[b]===a)return b;
return-1},Jb="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),Kb="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+Jb+")|)|)[\\x20\\t\\r\\n\\f]*\\]",fb=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+Kb.replace(3,8)+")*)|.*)\\)|)",Ia=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),Fc=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,
Gc=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Xa=/[\x20\t\r\n\f]*[+~]/,Lc=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*)[\\x20\\t\\r\\n\\f]*\\]","g"),Mc=RegExp(fb),Nc=RegExp("^"+Jb+"$"),Ja={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+Kb),PSEUDO:RegExp("^"+fb),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},gb=/^[^{]+\{\s*\[native \w/,Bc=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,Oc=/^(?:input|select|textarea|button)$/i,Pc=/^h\d$/i,Cc=/'|\\/g,ba=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)",
"ig"),ca=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(55296|a>>10,56320|1023&a)};try{aa.apply(da=Ib.call($.childNodes),$.childNodes),da[$.childNodes.length].nodeType}catch(od){aa={apply:da.length?function(a,b){Kc.apply(a,Ib.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}Fb=A.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};C=A.support={};ia=A.setDocument=function(a){var b=
a?a.ownerDocument||a:$;a=b.defaultView;return b!==K&&9===b.nodeType&&b.documentElement?(K=b,Z=b.documentElement,X=!Fb(b),a&&a.attachEvent&&a!==a.top&&a.attachEvent("onbeforeunload",function(){ia()}),C.attributes=U(function(a){return a.className="i",!a.getAttribute("className")}),C.getElementsByTagName=U(function(a){return a.appendChild(b.createComment("")),!a.getElementsByTagName("*").length}),C.getElementsByClassName=U(function(a){return a.innerHTML="<div class='a'></div><div class='a i'></div>",
a.firstChild.className="i",2===a.getElementsByClassName("i").length}),C.getById=U(function(a){return Z.appendChild(a).id=I,!b.getElementsByName||!b.getElementsByName(I).length}),C.getById?(w.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&X){var d=b.getElementById(a);return d&&d.parentNode?[d]:[]}},w.filter.ID=function(a){var b=a.replace(ba,ca);return function(a){return a.getAttribute("id")===b}}):(delete w.find.ID,w.filter.ID=function(a){var b=a.replace(ba,ca);return function(a){return(a=
"undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}}),w.find.TAG=C.getElementsByTagName?function(a,b){return"undefined"!==typeof b.getElementsByTagName?b.getElementsByTagName(a):void 0}:function(a,b){var d,g=[],j=0,r=b.getElementsByTagName(a);if("*"===a){for(;d=r[j++];)1===d.nodeType&&g.push(d);return g}return r},w.find.CLASS=C.getElementsByClassName&&function(a,b){return"undefined"!==typeof b.getElementsByClassName&&X?b.getElementsByClassName(a):void 0},ma=[],O=[],(C.qsa=
gb.test(b.querySelectorAll))&&(U(function(a){a.innerHTML="<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||O.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||O.push(":checked")}),U(function(a){var d=b.createElement("input");d.setAttribute("type","hidden");a.appendChild(d).setAttribute("t","");a.querySelectorAll("[t^='']").length&&
O.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll(":enabled").length||O.push(":enabled",":disabled");a.querySelectorAll("*,:x");O.push(",.*:")})),(C.matchesSelector=gb.test(Oa=Z.webkitMatchesSelector||Z.mozMatchesSelector||Z.oMatchesSelector||Z.msMatchesSelector))&&U(function(a){C.disconnectedMatch=Oa.call(a,"div");Oa.call(a,"[s!='']:x");ma.push("!=",fb)}),O=O.length&&RegExp(O.join("|")),ma=ma.length&&RegExp(ma.join("|")),ua=gb.test(Z.contains)||Z.compareDocumentPosition?function(a,
b){var d=9===a.nodeType?a.documentElement:a,g=b&&b.parentNode;return a===g||!(!g||1!==g.nodeType||!(d.contains?d.contains(g):a.compareDocumentPosition&&16&a.compareDocumentPosition(g)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1},eb=Z.compareDocumentPosition?function(a,d){if(a===d)return ra=!0,0;var f=d.compareDocumentPosition&&a.compareDocumentPosition&&a.compareDocumentPosition(d);return f?1&f||!C.sortDetached&&d.compareDocumentPosition(a)===f?a===b||ua($,a)?-1:d===b||ua($,
d)?1:la?ka.call(la,a)-ka.call(la,d):0:4&f?-1:1:a.compareDocumentPosition?-1:1}:function(a,d){var f,g=0;f=a.parentNode;var j=d.parentNode,r=[a],h=[d];if(a===d)return ra=!0,0;if(!f||!j)return a===b?-1:d===b?1:f?-1:j?1:la?ka.call(la,a)-ka.call(la,d):0;if(f===j)return Cb(a,d);for(f=a;f=f.parentNode;)r.unshift(f);for(f=d;f=f.parentNode;)h.unshift(f);for(;r[g]===h[g];)g++;return g?Cb(r[g],h[g]):r[g]===$?-1:h[g]===$?1:0},b):K};A.matches=function(a,b){return A(a,null,null,b)};A.matchesSelector=function(a,
b){if((a.ownerDocument||a)!==K&&ia(a),b=b.replace(Lc,"='$1']"),!(!C.matchesSelector||!X||ma&&ma.test(b)||O&&O.test(b)))try{var c=Oa.call(a,b);if(c||C.disconnectedMatch||a.document&&11!==a.document.nodeType)return c}catch(d){}return 0<A(b,K,null,[a]).length};A.contains=function(a,b){return(a.ownerDocument||a)!==K&&ia(a),ua(a,b)};A.attr=function(a,b){(a.ownerDocument||a)!==K&&ia(a);var c=w.attrHandle[b.toLowerCase()],c=c&&Ic.call(w.attrHandle,b.toLowerCase())?c(a,b,!X):void 0;return void 0===c?C.attributes||
!X?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null:c};A.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};A.uniqueSort=function(a){var b,c=[],d=0,f=0;if(ra=!C.detectDuplicates,la=!C.sortStable&&a.slice(0),a.sort(eb),ra){for(;b=a[f++];)b===a[f]&&(d=c.push(f));for(;d--;)a.splice(c[d],1)}return a};Na=A.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"==typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=
a.nextSibling)c+=Na(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d];d++)c+=Na(b);return c};w=A.selectors={cacheLength:50,createPseudo:T,match:Ja,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){return a[1]=a[1].replace(ba,ca),a[3]=(a[4]||a[5]||"").replace(ba,ca),"~="===a[2]&&(a[3]=" "+a[3]+" "),a.slice(0,4)},CHILD:function(a){return a[1]=a[1].toLowerCase(),
"nth"===a[1].slice(0,3)?(a[3]||A.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&A.error(a[0]),a},PSEUDO:function(a){var b,c=!a[5]&&a[2];return Ja.CHILD.test(a[0])?null:(a[3]&&void 0!==a[4]?a[2]=a[4]:c&&Mc.test(c)&&(b=Ga(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=c.slice(0,b)),a.slice(0,3))}},filter:{TAG:function(a){var b=a.replace(ba,ca).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&
a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=Gb[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&Gb(a,function(a){return b.test("string"==typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")})},ATTR:function(a,b,c){return function(d){d=A.attr(d,a);return null==d?"!="===b:b?(d+="","="===b?d===c:"!="===b?d!==c:"^="===b?c&&0===d.indexOf(c):"*="===b?c&&-1<d.indexOf(c):"$="===b?c&&d.slice(-c.length)===c:"~="===b?
-1<(" "+d+" ").indexOf(c):"|="===b?d===c||d.slice(0,c.length+1)===c+"-":!1):!0}},CHILD:function(a,b,c,d,f){var g="nth"!==a.slice(0,3),j="last"!==a.slice(-4),r="of-type"===b;return 1===d&&0===f?function(a){return!!a.parentNode}:function(b,c,h){var p,k,l,q,n;c=g!==j?"nextSibling":"previousSibling";var m=b.parentNode,t=r&&b.nodeName.toLowerCase();h=!h&&!r;if(m){if(g){for(;c;){for(k=b;k=k[c];)if(r?k.nodeName.toLowerCase()===t:1===k.nodeType)return!1;n=c="only"===a&&!n&&"nextSibling"}return!0}if(n=[j?
m.firstChild:m.lastChild],j&&h){h=m[I]||(m[I]={});p=h[a]||[];q=p[0]===Y&&p[1];l=p[0]===Y&&p[2];for(k=q&&m.childNodes[q];k=++q&&k&&k[c]||(l=q=0)||n.pop();)if(1===k.nodeType&&++l&&k===b){h[a]=[Y,q,l];break}}else if(h&&(p=(b[I]||(b[I]={}))[a])&&p[0]===Y)l=p[1];else for(;(k=++q&&k&&k[c]||(l=q=0)||n.pop())&&(!(r?k.nodeName.toLowerCase()===t:1===k.nodeType)||!++l||!(h&&((k[I]||(k[I]={}))[a]=[Y,l]),k===b)););return l-=f,l===d||0===l%d&&0<=l/d}}},PSEUDO:function(a,b){var c,d=w.pseudos[a]||w.setFilters[a.toLowerCase()]||
A.error("unsupported pseudo: "+a);return d[I]?d(b):1<d.length?(c=[a,a,"",b],w.setFilters.hasOwnProperty(a.toLowerCase())?T(function(a,c){for(var j,h=d(a,b),k=h.length;k--;)j=ka.call(a,h[k]),a[j]=!(c[j]=h[k])}):function(a){return d(a,0,c)}):d}},pseudos:{not:T(function(a){var b=[],c=[],d=Ya(a.replace(Ia,"$1"));return d[I]?T(function(a,b,c,h){var k;c=d(a,null,h,[]);for(h=a.length;h--;)(k=c[h])&&(a[h]=!(b[h]=k))}):function(a,g,j){return b[0]=a,d(b,null,j,c),!c.pop()}}),has:T(function(a){return function(b){return 0<
A(a,b).length}}),contains:T(function(a){return function(b){return-1<(b.textContent||b.innerText||Na(b)).indexOf(a)}}),lang:T(function(a){return Nc.test(a||"")||A.error("unsupported lang: "+a),a=a.replace(ba,ca).toLowerCase(),function(b){var c;do if(c=X?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(a){var b=Wa.location&&Wa.location.hash;return b&&b.slice(1)===a.id},root:function(a){return a===
Z},focus:function(a){return a===K.activeElement&&(!K.hasFocus||K.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){return a.parentNode&&a.parentNode.selectedIndex,!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if("@"<a.nodeName||3===a.nodeType||4===a.nodeType)return!1;
return!0},parent:function(a){return!w.pseudos.empty(a)},header:function(a){return Pc.test(a.nodeName)},input:function(a){return Oc.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||b.toLowerCase()===a.type)},first:ja(function(){return[0]}),last:ja(function(a,b){return[b-1]}),eq:ja(function(a,b,c){return[0>c?c+b:c]}),
even:ja(function(a,b){for(var c=0;b>c;c+=2)a.push(c);return a}),odd:ja(function(a,b){for(var c=1;b>c;c+=2)a.push(c);return a}),lt:ja(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:ja(function(a,b,c){for(c=0>c?c+b:c;b>++c;)a.push(c);return a})}};w.pseudos.nth=w.pseudos.eq;for(qa in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})w.pseudos[qa]=Dc(qa);for(qa in{submit:!0,reset:!0})w.pseudos[qa]=Ec(qa);Db.prototype=w.filters=w.pseudos;w.setFilters=new Db;Ya=A.compile=function(a,b){var c,
d=[],f=[],g=Hb[a+" "];if(!g){b||(b=Ga(a));for(c=b.length;c--;)g=db(b[c]),g[I]?d.push(g):f.push(g);var j=0,h=0<d.length,k=0<f.length;c=function(a,b,c,g,l){var q,n,m=[],t=0,z="0",v=a&&[],B=null!=l,D=Ma,x=a||k&&w.find.TAG("*",l&&b.parentNode||b),Lb=Y+=null==D?1:Math.random()||0.1;for(B&&(Ma=b!==K&&b,Ka=j);null!=(l=x[z]);z++){if(k&&l){for(q=0;n=f[q++];)if(n(l,b,c)){g.push(l);break}B&&(Y=Lb,Ka=++j)}h&&((l=!n&&l)&&t--,a&&v.push(l))}if(t+=z,h&&z!==t){for(q=0;n=d[q++];)n(v,m,b,c);if(a){if(0<t)for(;z--;)v[z]||
m[z]||(m[z]=Jc.call(g));m=La(m)}aa.apply(g,m);B&&!a&&0<m.length&&1<t+d.length&&A.uniqueSort(g)}return B&&(Y=Lb,Ma=D),v};c=h?T(c):c;g=Hb(a,c)}return g};C.sortStable=I.split("").sort(eb).join("")===I;C.detectDuplicates=ra;ia();C.sortDetached=U(function(a){return 1&a.compareDocumentPosition(K.createElement("div"))});U(function(a){return a.innerHTML="<a href='#'></a>","#"===a.firstChild.getAttribute("href")})||$a("type|href|height|width",function(a,b,c){return c?void 0:a.getAttribute(b,"type"===b.toLowerCase()?
1:2)});C.attributes&&U(function(a){return a.innerHTML="<input/>",a.firstChild.setAttribute("value",""),""===a.firstChild.getAttribute("value")})||$a("value",function(a,b,c){return c||"input"!==a.nodeName.toLowerCase()?void 0:a.defaultValue});U(function(a){return null==a.getAttribute("disabled")})||$a("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;return c?void 0:(d=a.getAttributeNode(b))&&d.specified?
d.value:!0===a[b]?b.toLowerCase():null});d.find=A;d.expr=A.selectors;d.expr[":"]=d.expr.pseudos;d.unique=A.uniqueSort;d.text=A.getText;d.isXMLDoc=A.isXML;d.contains=A.contains;var Mb={};d.Callbacks=function(a){var b;if("string"==typeof a){if(!(b=Mb[a])){b=a;var c=Mb[b]={};b=(d.each(b.match(V)||[],function(a,b){c[b]=!0}),c)}}else b=d.extend({},a);a=b;var e,f,g,j,r,k,s=[],l=!a.once&&[],p=function(b){e=a.memory&&b;f=!0;k=j||0;j=0;r=s.length;for(g=!0;s&&r>k;k++)if(!1===s[k].apply(b[0],b[1])&&a.stopOnFalse){e=
!1;break}g=!1;s&&(l?l.length&&p(l.shift()):e?s=[]:q.disable())},q={add:function(){if(s){var b=s.length;(function rc(b){d.each(b,function(b,c){var e=d.type(c);"function"===e?a.unique&&q.has(c)||s.push(c):c&&c.length&&"string"!==e&&rc(c)})})(arguments);g?r=s.length:e&&(j=b,p(e))}return this},remove:function(){return s&&d.each(arguments,function(a,b){for(var c;-1<(c=d.inArray(b,s,c));)s.splice(c,1),g&&(r>=c&&r--,k>=c&&k--)}),this},has:function(a){return a?-1<d.inArray(a,s):!(!s||!s.length)},empty:function(){return s=
[],r=0,this},disable:function(){return s=l=e=h,this},disabled:function(){return!s},lock:function(){return l=h,e||q.disable(),this},locked:function(){return!l},fireWith:function(a,b){return!s||f&&!l||(b=b||[],b=[a,b.slice?b.slice():b],g?l.push(b):p(b)),this},fire:function(){return q.fireWith(this,arguments),this},fired:function(){return!!f}};return q};d.extend({Deferred:function(a){var b=[["resolve","done",d.Callbacks("once memory"),"resolved"],["reject","fail",d.Callbacks("once memory"),"rejected"],
["notify","progress",d.Callbacks("memory")]],c="pending",e={state:function(){return c},always:function(){return f.done(arguments).fail(arguments),this},then:function(){var a=arguments;return d.Deferred(function(c){d.each(b,function(b,h){var k=h[0],l=d.isFunction(a[b])&&a[b];f[h[1]](function(){var a=l&&l.apply(this,arguments);a&&d.isFunction(a.promise)?a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[k+"With"](this===e?c.promise():this,l?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=
a?d.extend(a,e):e}},f={};return e.pipe=e.then,d.each(b,function(a,d){var h=d[2],k=d[3];e[d[1]]=h.add;k&&h.add(function(){c=k},b[1^a][2].disable,b[2][2].lock);f[d[0]]=function(){return f[d[0]+"With"](this===f?e:this,arguments),this};f[d[0]+"With"]=h.fireWith}),e.promise(f),a&&a.call(f,f),f},when:function(a){var b=0,c=ha.call(arguments),e=c.length,f=1!==e||a&&d.isFunction(a.promise)?e:0,g=1===f?a:d.Deferred(),j=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?ha.call(arguments):
d;c===h?g.notifyWith(b,c):--f||g.resolveWith(b,c)}},h,k,s;if(1<e){h=Array(e);k=Array(e);for(s=Array(e);e>b;b++)c[b]&&d.isFunction(c[b].promise)?c[b].promise().done(j(b,s,c)).fail(g.reject).progress(j(b,k,h)):--f}return f||g.resolveWith(s,c),g.promise()}});var Qc=d,Nb,E={},Q=x.createElement("input"),Ob=x.createDocumentFragment(),R=x.createElement("div"),Pb=x.createElement("select"),Qb=Pb.appendChild(x.createElement("option"));Nb=Q.type?(Q.type="checkbox",E.checkOn=""!==Q.value,E.optSelected=Qb.selected,
E.reliableMarginRight=!0,E.boxSizingReliable=!0,E.pixelPosition=!1,Q.checked=!0,E.noCloneChecked=Q.cloneNode(!0).checked,Pb.disabled=!0,E.optDisabled=!Qb.disabled,Q=x.createElement("input"),Q.value="t",Q.type="radio",E.radioValue="t"===Q.value,Q.setAttribute("checked","t"),Q.setAttribute("name","t"),Ob.appendChild(Q),E.checkClone=Ob.cloneNode(!0).cloneNode(!0).lastChild.checked,E.focusinBubbles="onfocusin"in l,R.style.backgroundClip="content-box",R.cloneNode(!0).style.backgroundClip="",E.clearCloneStyle=
"content-box"===R.style.backgroundClip,d(function(){var a,b,c=x.getElementsByTagName("body")[0];c&&(a=x.createElement("div"),a.style.cssText="border:0;width:0;height:0;position:absolute;top:0;left:-9999px;margin-top:1px",c.appendChild(a).appendChild(R),R.innerHTML="",R.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%",d.swap(c,null!=c.style.zoom?{zoom:1}:{},function(){E.boxSizing=
4===R.offsetWidth}),l.getComputedStyle&&(E.pixelPosition="1%"!==(l.getComputedStyle(R,null)||{}).top,E.boxSizingReliable="4px"===(l.getComputedStyle(R,null)||{width:"4px"}).width,b=R.appendChild(x.createElement("div")),b.style.cssText=R.style.cssText="padding:0;margin:0;border:0;display:block;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box",b.style.marginRight=b.style.width="0",R.style.width="1px",E.reliableMarginRight=!parseFloat((l.getComputedStyle(b,null)||{}).marginRight)),
c.removeChild(a))}),E):E;Qc.support=Nb;var G,v,lc=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,kc=/([A-Z])/g;k.uid=1;k.accepts=function(a){return a.nodeType?1===a.nodeType||9===a.nodeType:!0};k.prototype={key:function(a){if(!k.accepts(a))return 0;var b={},c=a[this.expando];if(!c){c=k.uid++;try{b[this.expando]={value:c},Object.defineProperties(a,b)}catch(e){b[this.expando]=c,d.extend(a,b)}}return this.cache[c]||(this.cache[c]={}),c},set:function(a,b,c){var e;a=this.key(a);var f=this.cache[a];if("string"==typeof b)f[b]=
c;else if(d.isEmptyObject(f))d.extend(this.cache[a],b);else for(e in b)f[e]=b[e];return f},get:function(a,b){var c=this.cache[this.key(a)];return b===h?c:c[b]},access:function(a,b,c){var e;return b===h||b&&"string"==typeof b&&c===h?(e=this.get(a,b),e!==h?e:this.get(a,d.camelCase(b))):(this.set(a,b,c),c!==h?c:b)},remove:function(a,b){var c,e,f=this.key(a),g=this.cache[f];if(b===h)this.cache[f]={};else{d.isArray(b)?e=b.concat(b.map(d.camelCase)):(c=d.camelCase(b),b in g?e=[b,c]:(e=c,e=e in g?[e]:e.match(V)||
[]));for(c=e.length;c--;)delete g[e[c]]}},hasData:function(a){return!d.isEmptyObject(this.cache[a[this.expando]]||{})},discard:function(a){a[this.expando]&&delete this.cache[a[this.expando]]}};G=new k;v=new k;d.extend({acceptData:k.accepts,hasData:function(a){return G.hasData(a)||v.hasData(a)},data:function(a,b,c){return G.access(a,b,c)},removeData:function(a,b){G.remove(a,b)},_data:function(a,b,c){return v.access(a,b,c)},_removeData:function(a,b){v.remove(a,b)}});d.fn.extend({data:function(a,b){var c,
e,f=this[0],g=0,j=null;if(a===h){if(this.length&&(j=G.get(f),1===f.nodeType&&!v.get(f,"hasDataAttrs"))){for(c=f.attributes;c.length>g;g++)e=c[g].name,0===e.indexOf("data-")&&(e=d.camelCase(e.slice(5)),n(f,e,j[e]));v.set(f,"hasDataAttrs",!0)}return j}return"object"==typeof a?this.each(function(){G.set(this,a)}):d.access(this,function(b){var c,e=d.camelCase(a);if(f&&b===h){if((c=G.get(f,a),c!==h)||(c=G.get(f,e),c!==h)||(c=n(f,e,h),c!==h))return c}else this.each(function(){var c=G.get(this,e);G.set(this,
e,b);-1!==a.indexOf("-")&&c!==h&&G.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){G.remove(this,a)})}});d.extend({queue:function(a,b,c){var e;return a?(b=(b||"fx")+"queue",e=v.get(a,b),c&&(!e||d.isArray(c)?e=v.access(a,b,d.makeArray(c)):e.push(c)),e||[]):h},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),j=function(){d.dequeue(a,b)};"inprogress"===f&&(f=c.shift(),e--);f&&("fx"===b&&c.unshift("inprogress"),
delete g.stop,f.call(a,j,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return v.get(a,c)||v.access(a,c,{empty:d.Callbacks("once memory").add(function(){v.remove(a,[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;return"string"!=typeof a&&(b=a,a="fx",c--),c>arguments.length?d.queue(this[0],a):b===h?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,
a)})},delay:function(a,b){return a=d.fx?d.fx.speeds[a]||a:a,b=b||"fx",this.queue(b,function(b,d){var f=setTimeout(b,a);d.stop=function(){clearTimeout(f)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,j=this.length,r=function(){--e||f.resolveWith(g,[g])};"string"!=typeof a&&(b=a,a=h);for(a=a||"fx";j--;)(c=v.get(g[j],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(r));return r(),f.promise(b)}});var Rb,hb=/[\t\r\n\f]/g,Rc=/\r/g,Sc=/^(?:input|select|textarea|button)$/i;
d.fn.extend({attr:function(a,b){return d.access(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})},prop:function(a,b){return d.access(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})},addClass:function(a){var b,c,e,f,g,j=0,h=this.length;b="string"==typeof a&&a;if(d.isFunction(a))return this.each(function(b){d(this).addClass(a.call(this,b,this.className))});if(b)for(b=
(a||"").match(V)||[];h>j;j++)if(c=this[j],e=1===c.nodeType&&(c.className?(" "+c.className+" ").replace(hb," "):" ")){for(g=0;f=b[g++];)0>e.indexOf(" "+f+" ")&&(e+=f+" ");c.className=d.trim(e)}return this},removeClass:function(a){var b,c,e,f,g,j=0,h=this.length;b=0===arguments.length||"string"==typeof a&&a;if(d.isFunction(a))return this.each(function(b){d(this).removeClass(a.call(this,b,this.className))});if(b)for(b=(a||"").match(V)||[];h>j;j++)if(c=this[j],e=1===c.nodeType&&(c.className?(" "+c.className+
" ").replace(hb," "):"")){for(g=0;f=b[g++];)for(;0<=e.indexOf(" "+f+" ");)e=e.replace(" "+f+" "," ");c.className=a?d.trim(e):""}return this},toggleClass:function(a,b){var c=typeof a;return"boolean"==typeof b&&"string"===c?b?this.addClass(a):this.removeClass(a):d.isFunction(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,this.className,b),b)}):this.each(function(){if("string"===c)for(var b,f=0,g=d(this),j=a.match(V)||[];b=j[f++];)g.hasClass(b)?g.removeClass(b):g.addClass(b);else(c===Ba||
"boolean"===c)&&(this.className&&v.set(this,"__className__",this.className),this.className=this.className||!1===a?"":v.get(this,"__className__")||"")})},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;c>b;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(hb," ").indexOf(a))return!0;return!1},val:function(a){var b,c,e,f=this[0];if(arguments.length)return e=d.isFunction(a),this.each(function(c){var f;1===this.nodeType&&(f=e?a.call(this,c,d(this).val()):a,null==f?f="":"number"==
typeof f?f+="":d.isArray(f)&&(f=d.map(f,function(a){return null==a?"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&b.set(this,f,"value")!==h||(this.value=f))});if(f)return b=d.valHooks[f.type]||d.valHooks[f.nodeName.toLowerCase()],b&&"get"in b&&(c=b.get(f,"value"))!==h?c:(c=f.value,"string"==typeof c?c.replace(Rc,""):null==c?"":c)}});d.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){for(var b,
c=a.options,e=a.selectedIndex,f="select-one"===a.type||0>e,g=f?null:[],j=f?e+1:c.length,h=0>e?j:f?e:0;j>h;h++)if(b=c[h],!(!b.selected&&h!==e||(d.support.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&d.nodeName(b.parentNode,"optgroup"))){if(a=d(b).val(),f)return a;g.push(a)}return g},set:function(a,b){for(var c,e,f=a.options,g=d.makeArray(b),j=f.length;j--;)e=f[j],(e.selected=0<=d.inArray(d(e).val(),g))&&(c=!0);return c||(a.selectedIndex=-1),g}}},attr:function(a,
b,c){var e,f,g=a.nodeType;if(a&&3!==g&&8!==g&&2!==g)return typeof a.getAttribute===Ba?d.prop(a,b,c):(1===g&&d.isXMLDoc(a)||(b=b.toLowerCase(),e=d.attrHooks[b]||(d.expr.match.bool.test(b)?Rb:void 0)),c===h?e&&"get"in e&&null!==(f=e.get(a,b))?f:(f=d.find.attr(a,b),null==f?h:f):null!==c?e&&"set"in e&&(f=e.set(a,c,b))!==h?f:(a.setAttribute(b,c+""),c):(d.removeAttr(a,b),h))},removeAttr:function(a,b){var c,e,f=0,g=b&&b.match(V);if(g&&1===a.nodeType)for(;c=g[f++];)e=d.propFix[c]||c,d.expr.match.bool.test(c)&&
(a[e]=!1),a.removeAttribute(c)},attrHooks:{type:{set:function(a,b){if(!d.support.radioValue&&"radio"===b&&d.nodeName(a,"input")){var c=a.value;return a.setAttribute("type",b),c&&(a.value=c),b}}}},propFix:{"for":"htmlFor","class":"className"},prop:function(a,b,c){var e,f,g,j=a.nodeType;if(a&&3!==j&&8!==j&&2!==j)return g=1!==j||!d.isXMLDoc(a),g&&(b=d.propFix[b]||b,f=d.propHooks[b]),c!==h?f&&"set"in f&&(e=f.set(a,c,b))!==h?e:a[b]=c:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]},propHooks:{tabIndex:{get:function(a){return a.hasAttribute("tabindex")||
Sc.test(a.nodeName)||a.href?a.tabIndex:-1}}}});Rb={set:function(a,b,c){return!1===b?d.removeAttr(a,c):a.setAttribute(c,c),c}};d.each(d.expr.match.bool.source.match(/\w+/g),function(a,b){var c=d.expr.attrHandle[b]||d.find.attr;d.expr.attrHandle[b]=function(a,b,g){var j=d.expr.attrHandle[b];a=g?h:(d.expr.attrHandle[b]=h)!=c(a,b,g)?b.toLowerCase():null;return d.expr.attrHandle[b]=j,a}});d.support.optSelected||(d.propHooks.selected={get:function(a){a=a.parentNode;return a&&a.parentNode&&a.parentNode.selectedIndex,
null}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=this});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){return d.isArray(b)?a.checked=0<=d.inArray(d(a).val(),b):h}};d.support.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});var Tc=/^key/,Uc=/^(?:mouse|contextmenu)|click/,Sb=/^(?:focusinfocus|focusoutblur)$/,
Tb=/^([^.]*)(?:\.(.+)|)$/;d.event={global:{},add:function(a,b,c,e,f){var g,j,r,k,l,q,p,n,m,t;if(l=v.get(a)){c.handler&&(g=c,c=g.handler,f=g.selector);c.guid||(c.guid=d.guid++);(k=l.events)||(k=l.events={});(j=l.handle)||(j=l.handle=function(a){return typeof d===Ba||a&&d.event.triggered===a.type?h:d.event.dispatch.apply(j.elem,arguments)},j.elem=a);b=(b||"").match(V)||[""];for(l=b.length;l--;)r=Tb.exec(b[l])||[],m=t=r[1],r=(r[2]||"").split(".").sort(),m&&(p=d.event.special[m]||{},m=(f?p.delegateType:
p.bindType)||m,p=d.event.special[m]||{},q=d.extend({type:m,origType:t,data:e,handler:c,guid:c.guid,selector:f,needsContext:f&&d.expr.match.needsContext.test(f),namespace:r.join(".")},g),(n=k[m])||(n=k[m]=[],n.delegateCount=0,p.setup&&!1!==p.setup.call(a,e,r,j)||a.addEventListener&&a.addEventListener(m,j,!1)),p.add&&(p.add.call(a,q),q.handler.guid||(q.handler.guid=c.guid)),f?n.splice(n.delegateCount++,0,q):n.push(q),d.event.global[m]=!0);a=null}},remove:function(a,b,c,e,f){var g,j,h,k,l,q,p,m,n,t,
z,B=v.hasData(a)&&v.get(a);if(B&&(k=B.events)){b=(b||"").match(V)||[""];for(l=b.length;l--;)if(h=Tb.exec(b[l])||[],n=z=h[1],t=(h[2]||"").split(".").sort(),n){p=d.event.special[n]||{};n=(e?p.delegateType:p.bindType)||n;m=k[n]||[];h=h[2]&&RegExp("(^|\\.)"+t.join("\\.(?:.*\\.|)")+"(\\.|$)");for(j=g=m.length;g--;)q=m[g],!f&&z!==q.origType||c&&c.guid!==q.guid||h&&!h.test(q.namespace)||e&&e!==q.selector&&("**"!==e||!q.selector)||(m.splice(g,1),q.selector&&m.delegateCount--,p.remove&&p.remove.call(a,q));
j&&!m.length&&(p.teardown&&!1!==p.teardown.call(a,t,B.handle)||d.removeEvent(a,n,B.handle),delete k[n])}else for(n in k)d.event.remove(a,n+b[l],c,e,!0);d.isEmptyObject(k)&&(delete B.handle,v.remove(a,"events"))}},trigger:function(a,b,c,e){var f,g,j,r,k,q,n,p=[c||x],m=Va.call(a,"type")?a.type:a;f=Va.call(a,"namespace")?a.namespace.split("."):[];if(g=j=c=c||x,3!==c.nodeType&&8!==c.nodeType&&!Sb.test(m+d.event.triggered)&&(0<=m.indexOf(".")&&(f=m.split("."),m=f.shift(),f.sort()),k=0>m.indexOf(":")&&
"on"+m,a=a[d.expando]?a:new d.Event(m,"object"==typeof a&&a),a.isTrigger=e?2:3,a.namespace=f.join("."),a.namespace_re=a.namespace?RegExp("(^|\\.)"+f.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=h,a.target||(a.target=c),b=null==b?[a]:d.makeArray(b,[a]),n=d.event.special[m]||{},e||!n.trigger||!1!==n.trigger.apply(c,b))){if(!e&&!n.noBubble&&!d.isWindow(c)){r=n.delegateType||m;for(Sb.test(r+m)||(g=g.parentNode);g;g=g.parentNode)p.push(g),j=g;j===(c.ownerDocument||x)&&p.push(j.defaultView||j.parentWindow||
l)}for(f=0;(g=p[f++])&&!a.isPropagationStopped();)a.type=1<f?r:n.bindType||m,(q=(v.get(g,"events")||{})[a.type]&&v.get(g,"handle"))&&q.apply(g,b),(q=k&&g[k])&&d.acceptData(g)&&q.apply&&!1===q.apply(g,b)&&a.preventDefault();return a.type=m,e||a.isDefaultPrevented()||n._default&&!1!==n._default.apply(p.pop(),b)||!d.acceptData(c)||k&&d.isFunction(c[m])&&!d.isWindow(c)&&(j=c[k],j&&(c[k]=null),d.event.triggered=m,c[m](),d.event.triggered=h,j&&(c[k]=j)),a.result}},dispatch:function(a){a=d.event.fix(a);
var b,c,e,f,g,j=[],r=ha.call(arguments);b=(v.get(this,"events")||{})[a.type]||[];var k=d.event.special[a.type]||{};if(r[0]=a,a.delegateTarget=this,!k.preDispatch||!1!==k.preDispatch.call(this,a)){j=d.event.handlers.call(this,a,b);for(b=0;(f=j[b++])&&!a.isPropagationStopped();){a.currentTarget=f.elem;for(c=0;(g=f.handlers[c++])&&!a.isImmediatePropagationStopped();)(!a.namespace_re||a.namespace_re.test(g.namespace))&&(a.handleObj=g,a.data=g.data,e=((d.event.special[g.origType]||{}).handle||g.handler).apply(f.elem,
r),e!==h&&!1===(a.result=e)&&(a.preventDefault(),a.stopPropagation()))}return k.postDispatch&&k.postDispatch.call(this,a),a.result}},handlers:function(a,b){var c,e,f,g,j=[],r=b.delegateCount,k=a.target;if(r&&k.nodeType&&(!a.button||"click"!==a.type))for(;k!==this;k=k.parentNode||this)if(!0!==k.disabled||"click"!==a.type){e=[];for(c=0;r>c;c++)g=b[c],f=g.selector+" ",e[f]===h&&(e[f]=g.needsContext?0<=d(f,this).index(k):d.find(f,this,null,[k]).length),e[f]&&e.push(g);e.length&&j.push({elem:k,handlers:e})}return b.length>
r&&j.push({elem:this,handlers:b.slice(r)}),j},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){return null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode),a}},mouseHooks:{props:"button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c,d,f,g=b.button;return null==
a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||x,d=c.documentElement,f=c.body,a.pageX=b.clientX+(d&&d.scrollLeft||f&&f.scrollLeft||0)-(d&&d.clientLeft||f&&f.clientLeft||0),a.pageY=b.clientY+(d&&d.scrollTop||f&&f.scrollTop||0)-(d&&d.clientTop||f&&f.clientTop||0)),a.which||g===h||(a.which=1&g?1:2&g?3:4&g?2:0),a}},fix:function(a){if(a[d.expando])return a;var b,c,e;b=a.type;var f=a,g=this.fixHooks[b];g||(this.fixHooks[b]=g=Uc.test(b)?this.mouseHooks:Tc.test(b)?this.keyHooks:{});e=g.props?this.props.concat(g.props):
this.props;a=new d.Event(f);for(b=e.length;b--;)c=e[b],a[c]=f[c];return a.target||(a.target=x),3===a.target.nodeType&&(a.target=a.target.parentNode),g.filter?g.filter(a,f):a},special:{load:{noBubble:!0},focus:{trigger:function(){return this!==z()&&this.focus?(this.focus(),!1):h},delegateType:"focusin"},blur:{trigger:function(){return this===z()&&this.blur?(this.blur(),!1):h},delegateType:"focusout"},click:{trigger:function(){return"checkbox"===this.type&&this.click&&d.nodeName(this,"input")?(this.click(),
!1):h},_default:function(a){return d.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){a.result!==h&&(a.originalEvent.returnValue=a.result)}}},simulate:function(a,b,c,e){a=d.extend(new d.Event,c,{type:a,isSimulated:!0,originalEvent:{}});e?d.event.trigger(a,null,b):d.event.dispatch.call(b,a);a.isDefaultPrevented()&&c.preventDefault()}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};d.Event=function(a,b){return this instanceof d.Event?(a&&a.type?(this.originalEvent=
a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||a.getPreventDefault&&a.getPreventDefault()?m:t):this.type=a,b&&d.extend(this,b),this.timeStamp=a&&a.timeStamp||d.now(),this[d.expando]=!0,h):new d.Event(a,b)};d.Event.prototype={isDefaultPrevented:t,isPropagationStopped:t,isImmediatePropagationStopped:t,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=m;a&&a.preventDefault&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=
m;a&&a.stopPropagation&&a.stopPropagation()},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=m;this.stopPropagation()}};d.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var e,f=a.relatedTarget,g=a.handleObj;return(!f||f!==this&&!d.contains(this,f))&&(a.type=g.origType,e=g.handler.apply(this,arguments),a.type=b),e}}});d.support.focusinBubbles||d.each({focus:"focusin",blur:"focusout"},function(a,
b){var c=0,e=function(a){d.event.simulate(b,a.target,d.event.fix(a),!0)};d.event.special[b]={setup:function(){0===c++&&x.addEventListener(a,e,!0)},teardown:function(){0===--c&&x.removeEventListener(a,e,!0)}}});d.fn.extend({on:function(a,b,c,e,f){var g,j;if("object"==typeof a){"string"!=typeof b&&(c=c||b,b=h);for(j in a)this.on(j,b,c,a[j],f);return this}if(null==c&&null==e?(e=b,c=b=h):null==e&&("string"==typeof b?(e=c,c=h):(e=c,c=b,b=h)),!1===e)e=t;else if(!e)return this;return 1===f&&(g=e,e=function(a){return d().off(a),
g.apply(this,arguments)},e.guid=g.guid||(g.guid=d.guid++)),this.each(function(){d.event.add(this,a,e,c,b)})},one:function(a,b,c,d){return this.on(a,b,c,d,1)},off:function(a,b,c){var e,f;if(a&&a.preventDefault&&a.handleObj)return e=a.handleObj,d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler),this;if("object"==typeof a){for(f in a)this.off(f,b,a[f]);return this}return(!1===b||"function"==typeof b)&&(c=b,b=h),!1===c&&(c=t),this.each(function(){d.event.remove(this,
a,c,b)})},trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];return c?d.event.trigger(a,b,c,!0):h}});var mc=/^.[^:#\[\.,]*$/,Vc=/^(?:parents|prev(?:Until|All))/,Ub=d.expr.match.needsContext,Wc={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({find:function(a){var b,c=[],e=this,f=e.length;if("string"!=typeof a)return this.pushStack(d(a).filter(function(){for(b=0;f>b;b++)if(d.contains(e[b],this))return!0}));for(b=0;f>b;b++)d.find(a,
e[b],c);return c=this.pushStack(1<f?d.unique(c):c),c.selector=this.selector?this.selector+" "+a:a,c},has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;c>a;a++)if(d.contains(this,b[a]))return!0})},not:function(a){return this.pushStack(L(this,a||[],!0))},filter:function(a){return this.pushStack(L(this,a||[],!1))},is:function(a){return!!L(this,"string"==typeof a&&Ub.test(a)?d(a):a||[],!1).length},closest:function(a,b){for(var c,e=0,f=this.length,g=[],j=Ub.test(a)||
"string"!=typeof a?d(a,b||this.context):0;f>e;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(j?-1<j.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.unique(g):g)},index:function(a){return a?"string"==typeof a?xa.call(d(a),this[0]):xa.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){var c="string"==typeof a?d(a,b):d.makeArray(a&&a.nodeType?[a]:a),c=d.merge(this.get(),c);
return this.pushStack(d.unique(c))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return d.dir(a,"parentNode")},parentsUntil:function(a,b,c){return d.dir(a,"parentNode",c)},next:function(a){return B(a,"nextSibling")},prev:function(a){return B(a,"previousSibling")},nextAll:function(a){return d.dir(a,"nextSibling")},prevAll:function(a){return d.dir(a,"previousSibling")},
nextUntil:function(a,b,c){return d.dir(a,"nextSibling",c)},prevUntil:function(a,b,c){return d.dir(a,"previousSibling",c)},siblings:function(a){return d.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return d.sibling(a.firstChild)},contents:function(a){return a.contentDocument||d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);return"Until"!==a.slice(-5)&&(e=c),e&&"string"==typeof e&&(f=d.filter(e,f)),1<this.length&&(Wc[a]||d.unique(f),Vc.test(a)&&
f.reverse()),this.pushStack(f)}});d.extend({filter:function(a,b,c){var e=b[0];return c&&(a=":not("+a+")"),1===b.length&&1===e.nodeType?d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,d.grep(b,function(a){return 1===a.nodeType}))},dir:function(a,b,c){for(var e=[],f=c!==h;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});var Vb=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,
Wb=/<([\w:]+)/,Xc=/<|&#?\w+;/,Yc=/<(?:script|style|link)/i,Xb=/^(?:checkbox|radio)$/i,Zc=/checked\s*(?:[^=]|=\s*.checked.)/i,Yb=/^$|\/(?:java|ecma)script/i,nc=/^true\/(.*)/,$c=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,S={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};S.optgroup=S.option;S.tbody=S.tfoot=
S.colgroup=S.caption=S.thead;S.th=S.td;d.fn.extend({text:function(a){return d.access(this,function(a){return a===h?d.text(this):this.empty().append((this[0]&&this[0].ownerDocument||x).createTextNode(a))},null,a,arguments.length)},append:function(){return this.domManip(arguments,function(a){(1===this.nodeType||11===this.nodeType||9===this.nodeType)&&H(this,a).appendChild(a)})},prepend:function(){return this.domManip(arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=
H(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},remove:function(a,b){for(var c,e=a?d.filter(a,this):this,f=0;null!=(c=e[f]);f++)b||1!==c.nodeType||d.cleanData(F(c)),c.parentNode&&(b&&d.contains(c.ownerDocument,c)&&P(F(c,"script")),c.parentNode.removeChild(c));
return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(F(a,!1)),a.textContent="");return this},clone:function(a,b){return a=null==a?!1:a,b=null==b?a:b,this.map(function(){return d.clone(this,a,b)})},html:function(a){return d.access(this,function(a){var c=this[0]||{},e=0,f=this.length;if(a===h&&1===c.nodeType)return c.innerHTML;if("string"==typeof a&&!Yc.test(a)&&!S[(Wb.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Vb,"<$1></$2>");try{for(;f>e;e++)c=this[e]||
{},1===c.nodeType&&(d.cleanData(F(c,!1)),c.innerHTML=a);c=0}catch(g){}}c&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=d.map(this,function(a){return[a.nextSibling,a.parentNode]}),b=0;return this.domManip(arguments,function(c){var e=a[b++],f=a[b++];f&&(e&&e.parentNode!==f&&(e=this.nextSibling),d(this).remove(),f.insertBefore(c,e))},!0),b?this:this.remove()},detach:function(a){return this.remove(a,!0)},domManip:function(a,b,c){a=zb.apply([],a);var e,f,g,j,h=0,k=this.length,
l=this,m=k-1,p=a[0],q=d.isFunction(p);if(q||!(1>=k||"string"!=typeof p||d.support.checkClone)&&Zc.test(p))return this.each(function(d){var e=l.eq(d);q&&(a[0]=p.call(this,d,e.html()));e.domManip(a,b,c)});if(k&&(e=d.buildFragment(a,this[0].ownerDocument,!1,!c&&this),f=e.firstChild,1===e.childNodes.length&&(e=f),f)){f=d.map(F(e,"script"),ic);for(g=f.length;k>h;h++)j=e,h!==m&&(j=d.clone(j,!0,!0),g&&d.merge(f,F(j,"script"))),b.call(this[h],j,h);if(g){e=f[f.length-1].ownerDocument;d.map(f,jc);for(h=0;g>
h;h++)j=f[h],Yb.test(j.type||"")&&!v.access(j,"globalEval")&&d.contains(e,j)&&(j.src?d._evalUrl(j.src):d.globalEval(j.textContent.replace($c,"")))}}return this}});d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var e=[],f=d(a),g=f.length-1,j=0;g>=j;j++)a=j===g?this:this.clone(!0),d(f[j])[b](a),Ua.apply(e,a.get());return this.pushStack(e)}});d.extend({clone:function(a,b,c){var e,f,g,j,h=a.cloneNode(!0),
k=d.contains(a.ownerDocument,a);if(!d.support.noCloneChecked&&!(1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a))){j=F(h);g=F(a);e=0;for(f=g.length;f>e;e++){var l=g[e],q=j[e],p=q.nodeName.toLowerCase();"input"===p&&Xb.test(l.type)?q.checked=l.checked:("input"===p||"textarea"===p)&&(q.defaultValue=l.defaultValue)}}if(b)if(c){g=g||F(a);j=j||F(h);e=0;for(f=g.length;f>e;e++)fa(g[e],j[e])}else fa(a,h);return j=F(h,"script"),0<j.length&&P(j,!k&&F(a,"script")),h},buildFragment:function(a,b,c,e){for(var f,
g,j,h,k=0,l=a.length,q=b.createDocumentFragment(),p=[];l>k;k++)if(f=a[k],f||0===f)if("object"===d.type(f))d.merge(p,f.nodeType?[f]:f);else if(Xc.test(f)){g=g||q.appendChild(b.createElement("div"));j=(Wb.exec(f)||["",""])[1].toLowerCase();j=S[j]||S._default;g.innerHTML=j[1]+f.replace(Vb,"<$1></$2>")+j[2];for(j=j[0];j--;)g=g.lastChild;d.merge(p,g.childNodes);g=q.firstChild;g.textContent=""}else p.push(b.createTextNode(f));q.textContent="";for(k=0;f=p[k++];)if((!e||-1===d.inArray(f,e))&&(h=d.contains(f.ownerDocument,
f),g=F(q.appendChild(f),"script"),h&&P(g),c))for(j=0;f=g[j++];)Yb.test(f.type||"")&&c.push(f);return q},cleanData:function(a){for(var b,c,e,f,g,j,r=d.event.special,l=0;(c=a[l])!==h;l++){if(k.accepts(c)&&(g=c[v.expando],g&&(b=v.cache[g]))){if(e=Object.keys(b.events||{}),e.length)for(j=0;(f=e[j])!==h;j++)r[f]?d.event.remove(c,f):d.removeEvent(c,f,b.handle);v.cache[g]&&delete v.cache[g]}delete G.cache[c[G.expando]]}},_evalUrl:function(a){return d.ajax({url:a,type:"GET",dataType:"script",async:!1,global:!1,
"throws":!0})}});d.fn.extend({wrapAll:function(a){var b;return d.isFunction(a)?this.each(function(b){d(this).wrapAll(a.call(this,b))}):(this[0]&&(b=d(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&b.insertBefore(this[0]),b.map(function(){for(var a=this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this)),this)},wrapInner:function(a){return d.isFunction(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?
c.wrapAll(a):b.append(a)})},wrap:function(a){var b=d.isFunction(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(){return this.parent().each(function(){d.nodeName(this,"body")||d(this).replaceWith(this.childNodes)}).end()}});var oa,sa,ad=/^(none|table(?!-c[ea]).+)/,Zb=/^margin/,pc=RegExp("^("+Ea+")(.*)$","i"),Qa=RegExp("^("+Ea+")(?!px)[a-z%]+$","i"),bd=RegExp("^([+-])=("+Ea+")","i"),qb={BODY:"block"},cd={position:"absolute",visibility:"hidden",display:"block"},
$b={letterSpacing:0,fontWeight:400},ga=["Top","Right","Bottom","Left"],lb=["Webkit","O","Moz","ms"];d.fn.extend({css:function(a,b){return d.access(this,function(a,b,f){var g,j={},k=0;if(d.isArray(b)){f=l.getComputedStyle(a,null);for(g=b.length;g>k;k++)j[b[k]]=d.css(a,b[k],!1,f);return j}return f!==h?d.style(a,b,f):d.css(a,b)},a,b,1<arguments.length)},show:function(){return mb(this,!0)},hide:function(){return mb(this)},toggle:function(a){return"boolean"==typeof a?a?this.show():this.hide():this.each(function(){y(this)?
d(this).show():d(this).hide()})}});d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=oa(a,"opacity");return""===c?"1":c}}}},cssNumber:{columnCount:!0,fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g,j,k=d.camelCase(b),l=a.style;return b=d.cssProps[k]||(d.cssProps[k]=M(l,k)),j=d.cssHooks[b]||d.cssHooks[k],c===h?j&&"get"in j&&(f=
j.get(a,!1,e))!==h?f:l[b]:(g=typeof c,"string"===g&&(f=bd.exec(c))&&(c=(f[1]+1)*f[2]+parseFloat(d.css(a,b)),g="number"),null==c||"number"===g&&isNaN(c)||("number"!==g||d.cssNumber[k]||(c+="px"),d.support.clearCloneStyle||""!==c||0!==b.indexOf("background")||(l[b]="inherit"),j&&"set"in j&&(c=j.set(a,c,e))===h||(l[b]=c)),h)}},css:function(a,b,c,e){var f,g,j,k=d.camelCase(b);return b=d.cssProps[k]||(d.cssProps[k]=M(a.style,k)),j=d.cssHooks[b]||d.cssHooks[k],j&&"get"in j&&(f=j.get(a,!0,c)),f===h&&(f=
oa(a,b,e)),"normal"===f&&b in $b&&(f=$b[b]),""===c||c?(g=parseFloat(f),!0===c||d.isNumeric(g)?g||0:f):f}});oa=function(a,b,c){var e,f,g,j=(c=c||l.getComputedStyle(a,null))?c.getPropertyValue(b)||c[b]:h,k=a.style;return c&&(""!==j||d.contains(a.ownerDocument,a)||(j=d.style(a,b)),Qa.test(j)&&Zb.test(b)&&(e=k.width,f=k.minWidth,g=k.maxWidth,k.minWidth=k.maxWidth=k.width=j,j=c.width,k.width=e,k.minWidth=f,k.maxWidth=g)),j};d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){return e?
0===a.offsetWidth&&ad.test(d.css(a,"display"))?d.swap(a,cd,function(){return pb(a,b,f)}):pb(a,b,f):h},set:function(a,e,f){var g=f&&l.getComputedStyle(a,null);return nb(a,e,f?ob(a,b,f,d.support.boxSizing&&"border-box"===d.css(a,"boxSizing",!1,g),g):0)}}});d(function(){d.support.reliableMarginRight||(d.cssHooks.marginRight={get:function(a,b){return b?d.swap(a,{display:"inline-block"},oa,[a,"marginRight"]):h}});!d.support.pixelPosition&&d.fn.position&&d.each(["top","left"],function(a,b){d.cssHooks[b]=
{get:function(a,e){return e?(e=oa(a,b),Qa.test(e)?d(a).position()[b]+"px":e):h}}})});d.expr&&d.expr.filters&&(d.expr.filters.hidden=function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight},d.expr.filters.visible=function(a){return!d.expr.filters.hidden(a)});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"==typeof c?c.split(" "):[c];4>d;d++)f[a+ga[d]+b]=c[d]||c[d-2]||c[0];return f}};Zb.test(a)||(d.cssHooks[a+b].set=nb)});var dd=
/%20/g,qc=/\[\]$/,ac=/\r?\n/g,ed=/^(?:submit|button|image|reset|file)$/i,fd=/^(?:input|select|textarea|keygen)/i;d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!d(this).is(":disabled")&&fd.test(this.nodeName)&&!ed.test(a)&&(this.checked||!Xb.test(a))}).map(function(a,b){var c=d(this).val();return null==c?null:
d.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace(ac,"\r\n")}}):{name:b.name,value:c.replace(ac,"\r\n")}}).get()}});d.param=function(a,b){var c,e=[],f=function(a,b){b=d.isFunction(b)?b():null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};if(b===h&&(b=d.ajaxSettings&&d.ajaxSettings.traditional),d.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,this.value)});else for(c in a)Ra(c,a[c],b,f);return e.join("&").replace(dd,"+")};d.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),
function(a,b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});var na,ea,ib=d.now(),jb=/\?/,gd=/#.*$/,bc=/([?&])_=[^&]*/,hd=/^(.*?):[ \t]*([^\r\n]*)$/gm,
id=/^(?:GET|HEAD)$/,jd=/^\/\//,cc=/^([\w.+-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,dc=d.fn.load,ec={},Sa={},fc="*/".concat("*");try{ea=sc.href}catch(pd){ea=x.createElement("a"),ea.href="",ea=ea.href}na=cc.exec(ea.toLowerCase())||[];d.fn.load=function(a,b,c){if("string"!=typeof a&&dc)return dc.apply(this,arguments);var e,f,g,j=this,k=a.indexOf(" ");return 0<=k&&(e=a.slice(k),a=a.slice(0,k)),d.isFunction(b)?(c=b,b=h):b&&"object"==typeof b&&(f="POST"),0<j.length&&d.ajax({url:a,type:f,dataType:"html",data:b}).done(function(a){g=
arguments;j.html(e?d("<div>").append(d.parseHTML(a)).find(e):a)}).complete(c&&function(a,b){j.each(c,g||[a.responseText,b,a])}),this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:ea,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(na[1]),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",
accepts:{"*":fc,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":d.parseJSON,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Ta(Ta(a,d.ajaxSettings),b):Ta(d.ajaxSettings,a)},ajaxPrefilter:sb(ec),ajaxTransport:sb(Sa),ajax:function(a,
b){function c(a,b,c,j){var l,m,u,x,w=b;if(2!==A){A=2;k&&clearTimeout(k);e=h;g=j||"";D.readyState=0<a?4:0;j=200<=a&&300>a||304===a;if(c){u=p;for(var N=D,y,C,L,H,I=u.contents,F=u.dataTypes;"*"===F[0];)F.shift(),y===h&&(y=u.mimeType||N.getResponseHeader("Content-Type"));if(y)for(C in I)if(I[C]&&I[C].test(y)){F.unshift(C);break}if(F[0]in c)L=F[0];else{for(C in c){if(!F[0]||u.converters[C+" "+F[0]]){L=C;break}H||(H=C)}L=L||H}u=L?(L!==F[0]&&F.unshift(L),c[L]):h}var G;a:{c=p;y=u;C=D;L=j;var E,K,J;u={};N=
c.dataTypes.slice();if(N[1])for(E in c.converters)u[E.toLowerCase()]=c.converters[E];for(H=N.shift();H;)if(c.responseFields[H]&&(C[c.responseFields[H]]=y),!J&&L&&c.dataFilter&&(y=c.dataFilter(y,c.dataType)),J=H,H=N.shift())if("*"===H)H=J;else if("*"!==J&&J!==H){if(E=u[J+" "+H]||u["* "+H],!E)for(G in u)if(K=G.split(" "),K[1]===H&&(E=u[J+" "+K[0]]||u["* "+K[0]])){!0===E?E=u[G]:!0!==u[G]&&(H=K[0],N.unshift(K[1]));break}if(!0!==E)if(E&&c["throws"])y=E(y);else try{y=E(y)}catch(M){G={state:"parsererror",
error:E?M:"No conversion from "+J+" to "+H};break a}}G={state:"success",data:y}}u=G;j?(p.ifModified&&(x=D.getResponseHeader("Last-Modified"),x&&(d.lastModified[f]=x),x=D.getResponseHeader("etag"),x&&(d.etag[f]=x)),204===a||"HEAD"===p.type?w="nocontent":304===a?w="notmodified":(w=u.state,l=u.data,m=u.error,j=!m)):(m=w,(a||!w)&&(w="error",0>a&&(a=0)));D.status=a;D.statusText=(b||w)+"";j?z.resolveWith(n,[l,w,D]):z.rejectWith(n,[D,w,m]);D.statusCode(B);B=h;q&&t.trigger(j?"ajaxSuccess":"ajaxError",[D,
p,j?l:m]);v.fireWith(n,[D,w]);q&&(t.trigger("ajaxComplete",[D,p]),--d.active||d.event.trigger("ajaxStop"))}}"object"==typeof a&&(b=a,a=h);b=b||{};var e,f,g,j,k,l,q,m,p=d.ajaxSetup({},b),n=p.context||p,t=p.context&&(n.nodeType||n.jquery)?d(n):d.event,z=d.Deferred(),v=d.Callbacks("once memory"),B=p.statusCode||{},x={},w={},A=0,y="canceled",D={readyState:0,getResponseHeader:function(a){var b;if(2===A){if(!j)for(j={};b=hd.exec(g);)j[b[1].toLowerCase()]=b[2];b=j[a.toLowerCase()]}return null==b?null:b},
getAllResponseHeaders:function(){return 2===A?g:null},setRequestHeader:function(a,b){var c=a.toLowerCase();return A||(a=w[c]=w[c]||a,x[a]=b),this},overrideMimeType:function(a){return A||(p.mimeType=a),this},statusCode:function(a){var b;if(a)if(2>A)for(b in a)B[b]=[B[b],a[b]];else D.always(a[D.status]);return this},abort:function(a){a=a||y;return e&&e.abort(a),c(0,a),this}};if(z.promise(D).complete=v.add,D.success=D.done,D.error=D.fail,p.url=((a||p.url||ea)+"").replace(gd,"").replace(jd,na[1]+"//"),
p.type=b.method||b.type||p.method||p.type,p.dataTypes=d.trim(p.dataType||"*").toLowerCase().match(V)||[""],null==p.crossDomain&&(l=cc.exec(p.url.toLowerCase()),p.crossDomain=!(!l||l[1]===na[1]&&l[2]===na[2]&&(l[3]||("http:"===l[1]?"80":"443"))===(na[3]||("http:"===na[1]?"80":"443")))),p.data&&p.processData&&"string"!=typeof p.data&&(p.data=d.param(p.data,p.traditional)),tb(ec,p,b,D),2===A)return D;(q=p.global)&&0===d.active++&&d.event.trigger("ajaxStart");p.type=p.type.toUpperCase();p.hasContent=
!id.test(p.type);f=p.url;p.hasContent||(p.data&&(f=p.url+=(jb.test(f)?"&":"?")+p.data,delete p.data),!1===p.cache&&(p.url=bc.test(f)?f.replace(bc,"$1_="+ib++):f+(jb.test(f)?"&":"?")+"_="+ib++));p.ifModified&&(d.lastModified[f]&&D.setRequestHeader("If-Modified-Since",d.lastModified[f]),d.etag[f]&&D.setRequestHeader("If-None-Match",d.etag[f]));(p.data&&p.hasContent&&!1!==p.contentType||b.contentType)&&D.setRequestHeader("Content-Type",p.contentType);D.setRequestHeader("Accept",p.dataTypes[0]&&p.accepts[p.dataTypes[0]]?
p.accepts[p.dataTypes[0]]+("*"!==p.dataTypes[0]?", "+fc+"; q=0.01":""):p.accepts["*"]);for(m in p.headers)D.setRequestHeader(m,p.headers[m]);if(p.beforeSend&&(!1===p.beforeSend.call(n,D,p)||2===A))return D.abort();y="abort";for(m in{success:1,error:1,complete:1})D[m](p[m]);if(e=tb(Sa,p,b,D)){D.readyState=1;q&&t.trigger("ajaxSend",[D,p]);p.async&&0<p.timeout&&(k=setTimeout(function(){D.abort("timeout")},p.timeout));try{A=1,e.send(x,c)}catch(C){if(!(2>A))throw C;c(-1,C)}}else c(-1,"No Transport");return D},
getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,h,b,"script")}});d.each(["get","post"],function(a,b){d[b]=function(a,e,f,g){return d.isFunction(e)&&(g=g||f,f=e,e=h),d.ajax({url:a,type:b,dataType:g,data:e,success:f})}});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/(?:java|ecma)script/},converters:{"text script":function(a){return d.globalEval(a),a}}});d.ajaxPrefilter("script",
function(a){a.cache===h&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c;return{send:function(e,f){b=d("<script>").prop({async:!0,charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&f("error"===a.type?404:200,a.type)});x.head.appendChild(b[0])},abort:function(){c&&c()}}}});var gc=[],kb=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=gc.pop()||d.expando+"_"+ib++;return this[a]=
!0,a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var e,f,g,j=!1!==a.jsonp&&(kb.test(a.url)?"url":"string"==typeof a.data&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&kb.test(a.data)&&"data");return j||"jsonp"===a.dataTypes[0]?(e=a.jsonpCallback=d.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,j?a[j]=a[j].replace(kb,"$1"+e):!1!==a.jsonp&&(a.url+=(jb.test(a.url)?"&":"?")+a.jsonp+"="+e),a.converters["script json"]=function(){return g||d.error(e+" was not called"),
g[0]},a.dataTypes[0]="json",f=l[e],l[e]=function(){g=arguments},c.always(function(){l[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,gc.push(e));g&&d.isFunction(f)&&f(g[0]);g=f=h}),"script"):h});d.ajaxSettings.xhr=function(){try{return new XMLHttpRequest}catch(a){}};var va=d.ajaxSettings.xhr(),kd={"0":200,1223:204},ld=0,wa={};l.ActiveXObject&&d(l).on("unload",function(){for(var a in wa)wa[a]();wa=h});d.support.cors=!!va&&"withCredentials"in va;d.support.ajax=va=!!va;d.ajaxTransport(function(a){var b;
return d.support.cors||va&&!a.crossDomain?{send:function(c,d){var f,g,j=a.xhr();if(j.open(a.type,a.url,a.async,a.username,a.password),a.xhrFields)for(f in a.xhrFields)j[f]=a.xhrFields[f];a.mimeType&&j.overrideMimeType&&j.overrideMimeType(a.mimeType);a.crossDomain||c["X-Requested-With"]||(c["X-Requested-With"]="XMLHttpRequest");for(f in c)j.setRequestHeader(f,c[f]);b=function(a){return function(){b&&(delete wa[g],b=j.onload=j.onerror=null,"abort"===a?j.abort():"error"===a?d(j.status||404,j.statusText):
d(kd[j.status]||j.status,j.statusText,"string"==typeof j.responseText?{text:j.responseText}:h,j.getAllResponseHeaders()))}};j.onload=b();j.onerror=b("error");b=wa[g=ld++]=b("abort");j.send(a.hasContent&&a.data||null)},abort:function(){b&&b()}}:h});var pa,Pa,md=/^(?:toggle|show|hide)$/,hc=RegExp("^(?:([+-])=|)("+Ea+")([a-z%]*)$","i"),nd=/queueHooks$/,ya=[function(a,b,c){var e,f,g,j,k,l=this,q={},m=a.style,p=a.nodeType&&y(a),n=v.get(a,"fxshow");c.queue||(j=d._queueHooks(a,"fx"),null==j.unqueued&&(j.unqueued=
0,k=j.empty.fire,j.empty.fire=function(){j.unqueued||k()}),j.unqueued++,l.always(function(){l.always(function(){j.unqueued--;d.queue(a,"fx").length||j.empty.fire()})}));1===a.nodeType&&("height"in b||"width"in b)&&(c.overflow=[m.overflow,m.overflowX,m.overflowY],"inline"===d.css(a,"display")&&"none"===d.css(a,"float")&&(m.display="inline-block"));c.overflow&&(m.overflow="hidden",l.always(function(){m.overflow=c.overflow[0];m.overflowX=c.overflow[1];m.overflowY=c.overflow[2]}));for(e in b)if(f=b[e],
md.exec(f)){if(delete b[e],g=g||"toggle"===f,f===(p?"hide":"show")){if("show"!==f||!n||n[e]===h)continue;p=!0}q[e]=n&&n[e]||d.style(a,e)}if(!d.isEmptyObject(q))for(e in n?"hidden"in n&&(p=n.hidden):n=v.access(a,"fxshow",{}),g&&(n.hidden=!p),p?d(a).show():l.done(function(){d(a).hide()}),l.done(function(){var b;v.remove(a,"fxshow");for(b in q)d.style(a,b,q[b])}),q)b=vb(p?n[e]:0,e,l),e in n||(n[e]=b.start,p&&(b.end=b.start,b.start="width"===e||"height"===e?1:0))}],ta={"*":[function(a,b){var c=this.createTween(a,
b),e=c.cur(),f=hc.exec(b),g=f&&f[3]||(d.cssNumber[a]?"":"px"),j=(d.cssNumber[a]||"px"!==g&&+e)&&hc.exec(d.css(c.elem,a)),h=1,k=20;if(j&&j[3]!==g){g=g||j[3];f=f||[];j=+e||1;do h=h||".5",j/=h,d.style(c.elem,a,j+g);while(h!==(h=c.cur()/e)&&1!==h&&--k)}return f&&(j=c.start=+j||+e||0,c.unit=g,c.end=f[1]?j+(f[1]+1)*f[2]:+f[2]),c}]};d.Animation=d.extend(wb,{tweener:function(a,b){d.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var c,e=0,f=a.length;f>e;e++)c=a[e],ta[c]=ta[c]||[],ta[c].unshift(b)},prefilter:function(a,
b){b?ya.unshift(a):ya.push(a)}});d.Tween=J;J.prototype={constructor:J,init:function(a,b,c,e,f,g){this.elem=a;this.prop=c;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=J.propHooks[this.prop];return a&&a.get?a.get(this):J.propHooks._default.get(this)},run:function(a){var b,c=J.propHooks[this.prop];return this.pos=b=this.options.duration?d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):
a,this.now=(this.end-this.start)*b+this.start,this.options.step&&this.options.step.call(this.elem,this.now,this),c&&c.set?c.set(this):J.propHooks._default.set(this),this}};J.prototype.init.prototype=J.prototype;J.propHooks={_default:{get:function(a){var b;return null==a.elem[a.prop]||a.elem.style&&null!=a.elem.style[a.prop]?(b=d.css(a.elem,a.prop,""),b&&"auto"!==b?b:0):a.elem[a.prop]},set:function(a){d.fx.step[a.prop]?d.fx.step[a.prop](a):a.elem.style&&(null!=a.elem.style[d.cssProps[a.prop]]||d.cssHooks[a.prop])?
d.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};J.propHooks.scrollTop=J.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==a||"boolean"==typeof a?c.apply(this,arguments):this.animate(za(b,!0),a,d,g)}});d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(y).css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){var f=
d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var b=wb(this,d.extend({},a),g);(f||v.get(this,"finish"))&&b.stop(!0)};return b.finish=b,f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(a){var b=a.stop;delete a.stop;b(c)};return"string"!=typeof a&&(c=b,b=a,a=h),b&&!1!==a&&this.queue(a||"fx",[]),this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",j=d.timers,h=v.get(this);if(g)h[g]&&h[g].stop&&e(h[g]);else for(g in h)h[g]&&h[g].stop&&nd.test(g)&&e(h[g]);for(g=
j.length;g--;)j[g].elem!==this||null!=a&&j[g].queue!==a||(j[g].anim.stop(c),b=!1,j.splice(g,1));(b||!c)&&d.dequeue(this,a)})},finish:function(a){return!1!==a&&(a=a||"fx"),this.each(function(){var b,c=v.get(this),e=c[a+"queue"];b=c[a+"queueHooks"];var f=d.timers,g=e?e.length:0;c.finish=!0;d.queue(this,a,[]);b&&b.stop&&b.stop.call(this,!0);for(b=f.length;b--;)f[b].elem===this&&f[b].queue===a&&(f[b].anim.stop(!0),f.splice(b,1));for(b=0;g>b;b++)e[b]&&e[b].finish&&e[b].finish.call(this);delete c.finish})}});
d.each({slideDown:za("show"),slideUp:za("hide"),slideToggle:za("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.speed=function(a,b,c){var e=a&&"object"==typeof a?d.extend({},a):{complete:c||!c&&b||d.isFunction(a)&&a,duration:a,easing:c&&b||b&&!d.isFunction(b)&&b};return e.duration=d.fx.off?0:"number"==typeof e.duration?e.duration:e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default,
(null==e.queue||!0===e.queue)&&(e.queue="fx"),e.old=e.complete,e.complete=function(){d.isFunction(e.old)&&e.old.call(this);e.queue&&d.dequeue(this,e.queue)},e};d.easing={linear:function(a){return a},swing:function(a){return 0.5-Math.cos(a*Math.PI)/2}};d.timers=[];d.fx=J.prototype.init;d.fx.tick=function(){var a,b=d.timers,c=0;for(pa=d.now();b.length>c;c++)a=b[c],a()||b[c]!==a||b.splice(c--,1);b.length||d.fx.stop();pa=h};d.fx.timer=function(a){a()&&d.timers.push(a)&&d.fx.start()};d.fx.interval=13;
d.fx.start=function(){Pa||(Pa=setInterval(d.fx.tick,d.fx.interval))};d.fx.stop=function(){clearInterval(Pa);Pa=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fx.step={};d.expr&&d.expr.filters&&(d.expr.filters.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length});d.fn.offset=function(a){if(arguments.length)return a===h?this:this.each(function(b){d.offset.setOffset(this,a,b)});var b,c,e=this[0],f={top:0,left:0},g=e&&e.ownerDocument;if(g)return b=g.documentElement,
d.contains(b,e)?(typeof e.getBoundingClientRect!==Ba&&(f=e.getBoundingClientRect()),c=d.isWindow(g)?g:9===g.nodeType&&g.defaultView,{top:f.top+c.pageYOffset-b.clientTop,left:f.left+c.pageXOffset-b.clientLeft}):f};d.offset={setOffset:function(a,b,c){var e,f,g,j,h,k,l=d.css(a,"position"),m=d(a),q={};"static"===l&&(a.style.position="relative");h=m.offset();g=d.css(a,"top");k=d.css(a,"left");("absolute"===l||"fixed"===l)&&-1<(g+k).indexOf("auto")?(e=m.position(),j=e.top,f=e.left):(j=parseFloat(g)||0,
f=parseFloat(k)||0);d.isFunction(b)&&(b=b.call(a,c,h));null!=b.top&&(q.top=b.top-h.top+j);null!=b.left&&(q.left=b.left-h.left+f);"using"in b?b.using.call(a,q):m.css(q)}};d.fn.extend({position:function(){if(this[0]){var a,b,c=this[0],e={top:0,left:0};return"fixed"===d.css(c,"position")?b=c.getBoundingClientRect():(a=this.offsetParent(),b=this.offset(),d.nodeName(a[0],"html")||(e=a.offset()),e.top+=d.css(a[0],"borderTopWidth",!0),e.left+=d.css(a[0],"borderLeftWidth",!0)),{top:b.top-e.top-d.css(c,"marginTop",
!0),left:b.left-e.left-d.css(c,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||yb;a&&!d.nodeName(a,"html")&&"static"===d.css(a,"position");)a=a.offsetParent;return a||yb})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===b;d.fn[a]=function(e){return d.access(this,function(a,e,j){var k=d.isWindow(a)?a:9===a.nodeType&&a.defaultView;return j===h?k?k[b]:a[e]:(k?k.scrollTo(c?l.pageXOffset:j,c?j:l.pageYOffset):
a[e]=j,h)},a,e,arguments.length,null)}});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(e,g){var j=arguments.length&&(c||"boolean"!=typeof e),k=c||(!0===e||!0===g?"margin":"border");return d.access(this,function(b,c,e){var f;return d.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(f=b.documentElement,Math.max(b.body["scroll"+a],f["scroll"+a],b.body["offset"+a],f["offset"+a],f["client"+a])):e===
h?d.css(b,c,k):d.style(b,c,e,k)},b,j?e:h,j,null)}})});d.fn.size=function(){return this.length};d.fn.andSelf=d.fn.addBack;"object"==typeof module&&module&&"object"==typeof module.exports?module.exports=d:"function"==typeof define&&define.amd&&define("jquery",[],function(){return d});"object"==typeof l&&"object"==typeof l.document&&(l.jQuery=l.$=d)})(window);
(function(){var l=[].slice,h=window,q;q=function(k,q,m){var t,z,B,L,H;3>arguments.length&&(t=[h].concat(l.call(arguments)),k=t[0],q=t[1],m=t[2]);z=k;H=q.split(".");B=0;for(L=H.length;B<L;B++)t=H[B],k=k[t]||(k[t]={});return m(k,z)};q("__spider",function(h){return h.namespace=q});__spider.$=jQuery.noConflict(!0)}).call(this);
(function(){__spider.namespace("__spider.utils",function(l){l.nth=function(h){var l,k,n,m,t;n=h.parentElement;k=n.id;n.id="__spider"+parseInt(1E5*Math.random());l=document.querySelectorAll("#"+n.id+" > "+h.tagName);n.id=k;n=m=0;for(t=l.length;m<t;n=++m)if(k=l[n],k===h)return n+1;return 0};l.element=function(h,q){var k,n,m,t;m=h.tagName.toLowerCase();if(q)return m;var z,B;z=h.classList;B=[];n=0;for(t=z.length;n<t;n++)k=z[n],B.push(k);z=B.sort();B=[];n=0;for(t=z.length;n<t;n++)k=z[n],B.push("."+k);
k=B.join("");n=h.id?"#"+h.id:"";t=l.nth(h);return m+n+k+(0<t?":nth-of-type("+t+")":"")};l.path=function(h,q){var k;for(k=[];h&&h!==document.body;)k.splice(0,0,l.element(h,q)),h=h.parentElement;return k.join(" > ")};l.bound=function(h){var l,k;k=document.documentElement.scrollTop||document.body.scrollTop;l=document.documentElement.scrollLeft||document.body.scrollLeft;h=h.getBoundingClientRect();return{width:h.width,height:h.height,left:h.left+l,top:h.top+k}};return l.computed=function(h){var l,k,n,
m,t;k=document.defaultView.getComputedStyle(document.body);h=document.defaultView.getComputedStyle(h);l={};m=0;for(t=h.length;m<t;m++)n=h[m],"width"===n||("height"===n||"top"===n||"left"===n||"right"===n||"bottom"===n)||"-"!==n.charAt(0)&&h[n]!==k[n]&&(l[n]=h[n]);return l}})}).call(this);
(function(){__spider.namespace("__spider.extractor",function(l){l.extract_meta=function(){var h,l,k,n,m,t;m=document.querySelectorAll("title");t=[];k=0;for(n=m.length;k<n;k++)l=m[k],t.push(l.innerText);n=document.querySelectorAll('meta[name="description"]');m=[];l=0;for(k=n.length;l<k;l++)h=n[l],m.push(h.content);t.push.apply(t,function(){var k,l,m,q;m=document.querySelectorAll('meta[name="og:title"], meta[property="og:title"]');q=[];k=0;for(l=m.length;k<l;k++)h=m[k],q.push(h.content);return q}());
m.push.apply(m,function(){var k,l,m,q;m=document.querySelectorAll('meta[name="og:description"], meta[property="og:description"]');q=[];k=0;for(l=m.length;k<l;k++)h=m[k],q.push(h.content);return q}());t.push.apply(t,function(){var k,l,m,q;m=document.querySelectorAll('meta[name="twitter:title"], meta[property="twitter:title"]');q=[];k=0;for(l=m.length;k<l;k++)h=m[k],q.push(h.content);return q}());m.push.apply(m,function(){var k,l,m,q;m=document.querySelectorAll('meta[name="twitter:description"], meta[property="twitter:description"]');
q=[];k=0;for(l=m.length;k<l;k++)h=m[k],q.push(h.content);return q}());return{url:window.location.href,titles:t,descriptions:m}};l.extract_body=function(){var h,l,k,n,m;h={};m=document.defaultView.getComputedStyle(document.body);k=0;for(n=m.length;k<n;k++)l=m[k],"-"!==l.charAt(0)&&(h[l]=document.defaultView.getComputedStyle(document.body)[l]);return{scroll:{top:document.documentElement.scrollTop||document.body.scrollTop,left:document.documentElement.scrollLeft||document.body.scrollLeft},bound:__spider.utils.bound(document.body),
computed:h}};l.extract_links=function(){var h,l,k,n,m;n=document.querySelectorAll("a[href]");m=[];l=0;for(k=n.length;l<k;l++)h=n[l],m.push(h.href);return m};l.extract_texts=function(){var h,l,k,n,m;n=[];for(m=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,null,!1);k=m.nextNode();)if(0<k.nodeValue.trim().length&&(l=k.parentElement,h=__spider.utils.bound(l),0<h.width*h.height)){for(;l;){h=document.defaultView.getComputedStyle(l);if(0<parseInt(h.width)*parseInt(h.height))break;l=l.parentElement}l&&
(l.__spider?l.__spider.text.push(k.nodeValue):(l.__spider={element:__spider.utils.element(l),path:__spider.utils.path(l,!0),selector:__spider.utils.path(l),text:[k.nodeValue],html:l.innerHTML,bound:__spider.utils.bound(l),computed:__spider.utils.computed(l)},n.push(l.__spider)))}return n};l.extract_images=function(){var h,l,k,n,m,t;l=[];t=document.querySelectorAll("img[src]");n=0;for(m=t.length;n<m;n++)k=t[n],h=__spider.utils.bound(k),0<h.width*h.height&&l.push({src:k.src,element:__spider.utils.element(k),
path:__spider.utils.path(k,!0),selector:__spider.utils.path(k),bound:h,computed:__spider.utils.computed(k)});return l};return l.extract=function(){var h;h=l.extract_meta();h.body=l.extract_body();h.links=l.extract_links();h.texts=l.extract_texts();h.images=l.extract_images();return h}})}).call(this);
(function(){__spider.namespace("__spider.ui",function(l){var h;h=function(){var h;h=__spider.$("div#__spider");if(h.length)return h;h=__spider.$("<div />");h.attr({id:"__spider"});h.css({position:"fixed",zIndex:999999999,top:15,left:15,background:"#2f96b4",color:"white",fontFamily:'"Helvetica Neue", Helvetica, Arial, sans-serif',fontSize:"14px",lineHeight:"20px",fontWeight:"bold",padding:"10px 15px"});h.text("Loading ...");h.insertBefore(__spider.$(document.body));return h};l.info=function(l){var k;
k=h();k.css({background:"#2f96b4"});return k.html(l)};l.success=function(l){var k;k=h();k.css({background:"#51a351"});return k.html(l)};return l.error=function(l){var k;k=h();k.css({background:"#da4f49"});return k.html(l)}})}).call(this);
(function(){__spider.namespace("__spider.capture",function(l){var h,q;q=function(h){h=__spider.$.ajax({type:"POST",url:window.__spider_url+"/capture",dataType:"json",data:JSON.stringify(h)});h.done(function(){return __spider.ui.success("Done!")});return h.error(function(h,k){return __spider.ui.error("Something went wrong while uploading data: "+k)})};h=function(){var h;h=__spider.extractor.extract();__spider.ui.info("Uploading ...");return setTimeout(function(){return q(h)},50)};return l.run=function(){if(window.__spider_url)return __spider.ui.info("Capturing ..."),
setTimeout(h,50);__spider.ui.error("Bookmarklet outdated!")}});__spider.$(function(){return __spider.capture.run()})}).call(this);
