"object"!==typeof JSON&&(JSON={});
(function(){function l(h){return 10>h?"0"+h:h}function h(h){n.lastIndex=0;return n.test(h)?'"'+h.replace(n,function(h){var k=D[h];return"string"===typeof k?k:"\\u"+("0000"+h.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+h+'"'}function p(k,l){var n,D,Q,fa,G=s,O,z=l[k];z&&("object"===typeof z&&"function"===typeof z.toJSON)&&(z=z.toJSON(k));"function"===typeof E&&(z=E.call(l,k,z));switch(typeof z){case "string":return h(z);case "number":return isFinite(z)?String(z):"null";case "boolean":case "null":return String(z);
case "object":if(!z)return"null";s+=u;O=[];if("[object Array]"===Object.prototype.toString.apply(z)){fa=z.length;for(n=0;n<fa;n+=1)O[n]=p(n,z)||"null";Q=0===O.length?"[]":s?"[\n"+s+O.join(",\n"+s)+"\n"+G+"]":"["+O.join(",")+"]";s=G;return Q}if(E&&"object"===typeof E){fa=E.length;for(n=0;n<fa;n+=1)"string"===typeof E[n]&&(D=E[n],(Q=p(D,z))&&O.push(h(D)+(s?": ":":")+Q))}else for(D in z)Object.prototype.hasOwnProperty.call(z,D)&&(Q=p(D,z))&&O.push(h(D)+(s?": ":":")+Q);Q=0===O.length?"{}":s?"{\n"+s+O.join(",\n"+
s)+"\n"+G+"}":"{"+O.join(",")+"}";s=G;return Q}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+l(this.getUTCMonth()+1)+"-"+l(this.getUTCDate())+"T"+l(this.getUTCHours())+":"+l(this.getUTCMinutes())+":"+l(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var k=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
n=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,s,u,D={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},E;"function"!==typeof JSON.stringify&&(JSON.stringify=function(h,k,l){var n;u=s="";if("number"===typeof l)for(n=0;n<l;n+=1)u+=" ";else"string"===typeof l&&(u=l);if((E=k)&&"function"!==typeof k&&("object"!==typeof k||"number"!==typeof k.length))throw Error("JSON.stringify");return p("",{"":h})});
"function"!==typeof JSON.parse&&(JSON.parse=function(h,p){function l(h,k){var n,s,u=h[k];if(u&&"object"===typeof u)for(n in u)Object.prototype.hasOwnProperty.call(u,n)&&(s=l(u,n),void 0!==s?u[n]=s:delete u[n]);return p.call(h,k,u)}var n;h=String(h);k.lastIndex=0;k.test(h)&&(h=h.replace(k,function(h){return"\\u"+("0000"+h.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(h.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return n=eval("("+h+")"),"function"===typeof p?l({"":n},""):n;throw new SyntaxError("JSON.parse");})})();
(function(l,h){function p(a){var b=a.length,c=d.type(a);return d.isWindow(a)?!1:1===a.nodeType&&b?!0:"array"===c||"function"!==c&&(0===b||"number"==typeof b&&0<b&&b-1 in a)}function k(){Object.defineProperty(this.cache={},0,{get:function(){return{}}});this.expando=d.expando+Math.random()}function n(a,b,c){var e;if(c===h&&1===a.nodeType)if(e="data-"+b.replace(jc,"-$1").toLowerCase(),c=a.getAttribute(e),"string"==typeof c){try{c="true"===c?!0:"false"===c?!1:"null"===c?null:+c+""===c?+c:kc.test(c)?JSON.parse(c):
c}catch(d){}I.set(a,b,c)}else c=h;return c}function s(){return!0}function u(){return!1}function D(){try{return x.activeElement}catch(a){}}function E(a,b){for(;(a=a[b])&&1!==a.nodeType;);return a}function H(a,b,c){if(d.isFunction(b))return d.grep(a,function(a,d){return!!b.call(a,d,a)!==c});if(b.nodeType)return d.grep(a,function(a){return a===b!==c});if("string"==typeof b){if(lc.test(b))return d.filter(b,a,c);b=d.filter(b,a)}return d.grep(a,function(a){return 0<=xa.call(b,a)!==c})}function J(a,b){return d.nodeName(a,
"table")&&d.nodeName(1===b.nodeType?b:b.firstChild,"tr")?a.getElementsByTagName("tbody")[0]||a.appendChild(a.ownerDocument.createElement("tbody")):a}function hc(a){return a.type=(null!==a.getAttribute("type"))+"/"+a.type,a}function ic(a){var b=mc.exec(a.type);return b?a.type=b[1]:a.removeAttribute("type"),a}function Q(a,b){for(var c=a.length,e=0;c>e;e++)v.set(a[e],"globalEval",!b||v.get(b[e],"globalEval"))}function fa(a,b){var c,e,f,g,j,q;if(1===b.nodeType){if(v.hasData(a)&&(c=v.access(a),e=v.set(b,
c),q=c.events))for(f in delete e.handle,e.events={},q){c=0;for(e=q[f].length;e>c;c++)d.event.add(b,f,q[f][c])}I.hasData(a)&&(g=I.access(a),j=d.extend({},g),I.set(b,j))}}function G(a,b){var c=a.getElementsByTagName?a.getElementsByTagName(b||"*"):a.querySelectorAll?a.querySelectorAll(b||"*"):[];return b===h||b&&d.nodeName(a,b)?d.merge([a],c):c}function O(a,b){if(b in a)return b;for(var c=b.charAt(0).toUpperCase()+b.slice(1),e=b,d=lb.length;d--;)if(b=lb[d]+c,b in a)return b;return e}function z(a,b){return a=
b||a,"none"===d.css(a,"display")||!d.contains(a.ownerDocument,a)}function mb(a,b){for(var c,e,f,g=[],j=0,q=a.length;q>j;j++)e=a[j],e.style&&(g[j]=v.get(e,"olddisplay"),c=e.style.display,b?(g[j]||"none"!==c||(e.style.display=""),""===e.style.display&&z(e)&&(g[j]=v.access(e,"olddisplay",nc(e.nodeName)))):g[j]||(f=z(e),(c&&"none"!==c||!f)&&v.set(e,"olddisplay",f?c:d.css(e,"display"))));for(j=0;q>j;j++)e=a[j],e.style&&(b&&"none"!==e.style.display&&""!==e.style.display||(e.style.display=b?g[j]||"":"none"));
return a}function nb(a,b,c){return(a=oc.exec(b))?Math.max(0,a[1]-(c||0))+(a[2]||"px"):b}function ob(a,b,c,e,f){b=c===(e?"border":"content")?4:"width"===b?1:0;for(var g=0;4>b;b+=2)"margin"===c&&(g+=d.css(a,c+ga[b],!0,f)),e?("content"===c&&(g-=d.css(a,"padding"+ga[b],!0,f)),"margin"!==c&&(g-=d.css(a,"border"+ga[b]+"Width",!0,f))):(g+=d.css(a,"padding"+ga[b],!0,f),"padding"!==c&&(g+=d.css(a,"border"+ga[b]+"Width",!0,f)));return g}function pb(a,b,c){var e=!0,f="width"===b?a.offsetWidth:a.offsetHeight,
g=l.getComputedStyle(a,null),j=d.support.boxSizing&&"border-box"===d.css(a,"boxSizing",!1,g);if(0>=f||null==f){if(f=oa(a,b,g),(0>f||null==f)&&(f=a.style[b]),Qa.test(f))return f;e=j&&(d.support.boxSizingReliable||f===a.style[b]);f=parseFloat(f)||0}return f+ob(a,b,c||(j?"border":"content"),e,g)+"px"}function nc(a){var b=x,c=qb[a];return c||(c=rb(a,b),"none"!==c&&c||(sa=(sa||d("<iframe frameborder='0' width='0' height='0'/>").css("cssText","display:block !important")).appendTo(b.documentElement),b=(sa[0].contentWindow||
sa[0].contentDocument).document,b.write("<!doctype html><html><body>"),b.close(),c=rb(a,b),sa.detach()),qb[a]=c),c}function rb(a,b){var c=d(b.createElement(a)).appendTo(b.body),e=d.css(c[0],"display");return c.remove(),e}function Ra(a,b,c,e){var f;if(d.isArray(b))d.each(b,function(b,d){c||pc.test(a)?e(a,d):Ra(a+"["+("object"==typeof d?b:"")+"]",d,c,e)});else if(c||"object"!==d.type(b))e(a,b);else for(f in b)Ra(a+"["+f+"]",b[f],c,e)}function sb(a){return function(b,c){"string"!=typeof b&&(c=b,b="*");
var e,f=0,g=b.toLowerCase().match(W)||[];if(d.isFunction(c))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(c)):(a[e]=a[e]||[]).push(c)}}function tb(a,b,c,e){function f(q){var N;return g[q]=!0,d.each(a[q]||[],function(a,d){var q=d(b,c,e);return"string"!=typeof q||j||g[q]?j?!(N=q):h:(b.dataTypes.unshift(q),f(q),!1)}),N}var g={},j=a===Sa;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Ta(a,b){var c,e,f=d.ajaxSettings.flatOptions||{};for(c in b)b[c]!==h&&((f[c]?a:e||(e={}))[c]=
b[c]);return e&&d.extend(!0,a,e),a}function ub(){return setTimeout(function(){pa=h}),pa=d.now()}function vb(a,b,c){for(var e,d=(ta[b]||[]).concat(ta["*"]),g=0,j=d.length;j>g;g++)if(e=d[g].call(c,b,a))return e}function wb(a,b,c){var e,f,g=0,j=ya.length,q=d.Deferred().always(function(){delete h.elem}),h=function(){if(f)return!1;for(var b=pa||ub(),b=Math.max(0,r.startTime+r.duration-b),c=1-(b/r.duration||0),e=0,d=r.tweens.length;d>e;e++)r.tweens[e].run(c);return q.notifyWith(a,[r,c,b]),1>c&&d?b:(q.resolveWith(a,
[r]),!1)},r=q.promise({elem:a,props:d.extend({},b),opts:d.extend(!0,{specialEasing:{}},c),originalProperties:b,originalOptions:c,startTime:pa||ub(),duration:c.duration,tweens:[],createTween:function(b,c){var e=d.Tween(a,r.opts,b,c,r.opts.specialEasing[b]||r.opts.easing);return r.tweens.push(e),e},stop:function(b){var c=0,e=b?r.tweens.length:0;if(f)return this;for(f=!0;e>c;c++)r.tweens[c].run(1);return b?q.resolveWith(a,[r,b]):q.rejectWith(a,[r,b]),this}});b=r.props;c=r.opts.specialEasing;var t,m,
A,k;for(e in b)if(t=d.camelCase(e),m=c[t],A=b[e],d.isArray(A)&&(m=A[1],A=b[e]=A[0]),e!==t&&(b[t]=A,delete b[e]),k=d.cssHooks[t],k&&"expand"in k)for(e in A=k.expand(A),delete b[t],A)e in b||(b[e]=A[e],c[e]=m);else c[t]=m;for(;j>g;g++)if(e=ya[g].call(r,a,b,r.opts))return e;return d.map(b,vb,r),d.isFunction(r.opts.start)&&r.opts.start.call(a,r),d.fx.timer(d.extend(h,{elem:a,anim:r,queue:r.opts.queue})),r.progress(r.opts.progress).done(r.opts.done,r.opts.complete).fail(r.opts.fail).always(r.opts.always)}
function L(a,b,c,e,d){return new L.prototype.init(a,b,c,e,d)}function za(a,b){var c,e={height:a},d=0;for(b=b?1:0;4>d;d+=2-b)c=ga[d],e["margin"+c]=e["padding"+c]=a;return b&&(e.opacity=e.width=a),e}var xb,Aa,Ba=typeof h,rc=l.location,x=l.document,yb=x.documentElement,sc=l.jQuery,tc=l.$,Ca={},Da=[],zb=Da.concat,Ua=Da.push,ha=Da.slice,xa=Da.indexOf,uc=Ca.toString,Va=Ca.hasOwnProperty,vc="2.0.3".trim,d=function(a,b){return new d.fn.init(a,b,xb)},Ea=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,W=/\S+/g,
wc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]*))$/,Ab=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,xc=/^-ms-/,yc=/-([\da-z])/gi,zc=function(a,b){return b.toUpperCase()},Fa=function(){x.removeEventListener("DOMContentLoaded",Fa,!1);l.removeEventListener("load",Fa,!1);d.ready()};d.fn=d.prototype={jquery:"2.0.3",constructor:d,init:function(a,b,c){var e,f;if(!a)return this;if("string"==typeof a){if(e="<"===a.charAt(0)&&">"===a.charAt(a.length-1)&&3<=a.length?[null,a,null]:wc.exec(a),!e||!e[1]&&b)return!b||b.jquery?(b||c).find(a):
this.constructor(b).find(a);if(e[1]){if(b=b instanceof d?b[0]:b,d.merge(this,d.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:x,!0)),Ab.test(e[1])&&d.isPlainObject(b))for(e in b)d.isFunction(this[e])?this[e](b[e]):this.attr(e,b[e]);return this}return f=x.getElementById(e[2]),f&&f.parentNode&&(this.length=1,this[0]=f),this.context=x,this.selector=a,this}return a.nodeType?(this.context=this[0]=a,this.length=1,this):d.isFunction(a)?c.ready(a):(a.selector!==h&&(this.selector=a.selector,this.context=
a.context),d.makeArray(a,this))},selector:"",length:0,toArray:function(){return ha.call(this)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a){a=d.merge(this.constructor(),a);return a.prevObject=this,a.context=this.context,a},each:function(a,b){return d.each(this,a,b)},ready:function(a){return d.ready.promise().done(a),this},slice:function(){return this.pushStack(ha.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},
eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&b>a?[this[a]]:[])},map:function(a){return this.pushStack(d.map(this,function(b,c){return a.call(b,c,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:Ua,sort:[].sort,splice:[].splice};d.fn.init.prototype=d.fn;d.extend=d.fn.extend=function(){var a,b,c,e,f,g,j=arguments[0]||{},q=1,N=arguments.length,r=!1;"boolean"==typeof j&&(r=j,j=arguments[1]||{},q=2);"object"==typeof j||d.isFunction(j)||(j={});for(N===
q&&(j=this,--q);N>q;q++)if(null!=(a=arguments[q]))for(b in a)c=j[b],e=a[b],j!==e&&(r&&e&&(d.isPlainObject(e)||(f=d.isArray(e)))?(f?(f=!1,g=c&&d.isArray(c)?c:[]):g=c&&d.isPlainObject(c)?c:{},j[b]=d.extend(r,g,e)):e!==h&&(j[b]=e));return j};d.extend({expando:"jQuery"+("2.0.3"+Math.random()).replace(/\D/g,""),noConflict:function(a){return l.$===d&&(l.$=tc),a&&l.jQuery===d&&(l.jQuery=sc),d},isReady:!1,readyWait:1,holdReady:function(a){a?d.readyWait++:d.ready(!0)},ready:function(a){(!0===a?--d.readyWait:
d.isReady)||(d.isReady=!0,!0!==a&&0<--d.readyWait||(Aa.resolveWith(x,[d]),d.fn.trigger&&d(x).trigger("ready").off("ready")))},isFunction:function(a){return"function"===d.type(a)},isArray:Array.isArray,isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==a?a+"":"object"==typeof a||"function"==typeof a?Ca[uc.call(a)]||"object":typeof a},isPlainObject:function(a){if("object"!==d.type(a)||a.nodeType||d.isWindow(a))return!1;
try{if(a.constructor&&!Va.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}return!0},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseHTML:function(a,b,c){if(!a||"string"!=typeof a)return null;"boolean"==typeof b&&(c=b,b=!1);b=b||x;var e=Ab.exec(a);c=!c&&[];return e?[b.createElement(e[1])]:(e=d.buildFragment([a],b,c),c&&d(c).remove(),d.merge([],e.childNodes))},parseJSON:JSON.parse,parseXML:function(a){var b,c;if(!a||"string"!=
typeof a)return null;try{c=new DOMParser,b=c.parseFromString(a,"text/xml")}catch(e){b=h}return(!b||b.getElementsByTagName("parsererror").length)&&d.error("Invalid XML: "+a),b},noop:function(){},globalEval:function(a){var b,c=eval;(a=d.trim(a))&&(1===a.indexOf("use strict")?(b=x.createElement("script"),b.text=a,x.head.appendChild(b).parentNode.removeChild(b)):c(a))},camelCase:function(a){return a.replace(xc,"ms-").replace(yc,zc)},nodeName:function(a,b){return a.nodeName&&a.nodeName.toLowerCase()===
b.toLowerCase()},each:function(a,b,c){var e,d=0,g=a.length,j=p(a);if(c)if(j)for(;g>d&&!(e=b.apply(a[d],c),!1===e);d++);else for(d in a){if(e=b.apply(a[d],c),!1===e)break}else if(j)for(;g>d&&!(e=b.call(a[d],d,a[d]),!1===e);d++);else for(d in a)if(e=b.call(a[d],d,a[d]),!1===e)break;return a},trim:function(a){return null==a?"":vc.call(a)},makeArray:function(a,b){var c=b||[];return null!=a&&(p(Object(a))?d.merge(c,"string"==typeof a?[a]:a):Ua.call(c,a)),c},inArray:function(a,b,c){return null==b?-1:xa.call(b,
a,c)},merge:function(a,b){var c=b.length,e=a.length,d=0;if("number"==typeof c)for(;c>d;d++)a[e++]=b[d];else for(;b[d]!==h;)a[e++]=b[d++];return a.length=e,a},grep:function(a,b,c){var e,d=[],g=0,j=a.length;for(c=!!c;j>g;g++)e=!!b(a[g],g),c!==e&&d.push(a[g]);return d},map:function(a,b,c){var e,d=0,g=a.length,j=[];if(p(a))for(;g>d;d++)e=b(a[d],d,c),null!=e&&(j[j.length]=e);else for(d in a)e=b(a[d],d,c),null!=e&&(j[j.length]=e);return zb.apply([],j)},guid:1,proxy:function(a,b){var c,e,f;return"string"==
typeof b&&(c=a[b],b=a,a=c),d.isFunction(a)?(e=ha.call(arguments,2),f=function(){return a.apply(b||this,e.concat(ha.call(arguments)))},f.guid=a.guid=a.guid||d.guid++,f):h},access:function(a,b,c,e,f,g,j){var q=0,N=a.length,r=null==c;if("object"===d.type(c))for(q in f=!0,c)d.access(a,b,q,c[q],!0,g,j);else if(e!==h&&(f=!0,d.isFunction(e)||(j=!0),r&&(j?(b.call(a,e),b=null):(r=b,b=function(a,b,c){return r.call(d(a),c)})),b))for(;N>q;q++)b(a[q],c,j?e:e.call(a[q],q,b(a[q],c)));return f?a:r?b.call(a):N?b(a[0],
c):g},now:Date.now,swap:function(a,b,c,e){var d,g={};for(d in b)g[d]=a.style[d],a.style[d]=b[d];c=c.apply(a,e||[]);for(d in b)a.style[d]=g[d];return c}});d.ready.promise=function(a){return Aa||(Aa=d.Deferred(),"complete"===x.readyState?setTimeout(d.ready):(x.addEventListener("DOMContentLoaded",Fa,!1),l.addEventListener("load",Fa,!1))),Aa.promise(a)};d.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),function(a,b){Ca["[object "+b+"]"]=b.toLowerCase()});xb=d(x);var Wa=
l,y=function(a,b,c,e){var d,g,j,q,h;if((b?b.ownerDocument||b:$)!==M&&ia(b),b=b||M,c=c||[],!a||"string"!=typeof a)return c;if(1!==(q=b.nodeType)&&9!==q)return[];if(X&&!e){if(d=Ac.exec(a))if(j=d[1])if(9===q){if(g=b.getElementById(j),!g||!g.parentNode)return c;if(g.id===j)return c.push(g),c}else{if(b.ownerDocument&&(g=b.ownerDocument.getElementById(j))&&ua(b,g)&&g.id===j)return c.push(g),c}else{if(d[2])return aa.apply(c,b.getElementsByTagName(a)),c;if((j=d[3])&&C.getElementsByClassName&&b.getElementsByClassName)return aa.apply(c,
b.getElementsByClassName(j)),c}if(C.qsa&&(!P||!P.test(a))){if(g=d=K,j=b,h=9===q&&a,1===q&&"object"!==b.nodeName.toLowerCase()){q=Ga(a);(d=b.getAttribute("id"))?g=d.replace(Bc,"\\$&"):b.setAttribute("id",g);g="[id='"+g+"'] ";for(j=q.length;j--;)q[j]=g+Ha(q[j]);j=Xa.test(a)&&b.parentNode||b;h=q.join(",")}if(h)try{return aa.apply(c,j.querySelectorAll(h)),c}catch(r){}finally{d||b.removeAttribute("id")}}}var t;a:{a=a.replace(Ia,"$1");var m,A;g=Ga(a);if(!e&&1===g.length){if(t=g[0]=g[0].slice(0),2<t.length&&
"ID"===(m=t[0]).type&&C.getById&&9===b.nodeType&&X&&w.relative[t[1].type]){if(b=(w.find.ID(m.matches[0].replace(ba,ca),b)||[])[0],!b){t=c;break a}a=a.slice(t.shift().value.length)}for(q=Ja.needsContext.test(a)?0:t.length;q--&&!(m=t[q],w.relative[d=m.type]);)if((A=w.find[d])&&(e=A(m.matches[0].replace(ba,ca),Xa.test(t[0].type)&&b.parentNode||b))){if(t.splice(q,1),a=e.length&&Ha(t),!a){t=(aa.apply(c,e),c);break a}break}}t=(Ya(a,g)(e,b,!X,c,Xa.test(a)),c)}return t},Za=function(){function a(c,e){return b.push(c+=
" ")>w.cacheLength&&delete a[b.shift()],a[c]=e}var b=[];return a},U=function(a){return a[K]=!0,a},V=function(a){var b=M.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}},$a=function(a,b){for(var c=a.split("|"),e=a.length;e--;)w.attrHandle[c[e]]=b},Cb=function(a,b){var c=b&&a,e=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||Bb)-(~a.sourceIndex||Bb);if(e)return e;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1},Cc=function(a){return function(b){return"input"===
b.nodeName.toLowerCase()&&b.type===a}},Dc=function(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}},ja=function(a){return U(function(b){return b=+b,U(function(c,e){for(var d,g=a([],c.length,b),j=g.length;j--;)c[d=g[j]]&&(c[d]=!(e[d]=c[d]))})})},Db=function(){},Ga=function(a,b){var c,e,d,g,j,q,h;if(j=Eb[a+" "])return b?0:j.slice(0);j=a;q=[];for(h=w.preFilter;j;){(!c||(e=Ec.exec(j)))&&(e&&(j=j.slice(e[0].length)||j),q.push(d=[]));c=!1;(e=Fc.exec(j))&&
(c=e.shift(),d.push({value:c,type:e[0].replace(Ia," ")}),j=j.slice(c.length));for(g in w.filter)!(e=Ja[g].exec(j))||h[g]&&!(e=h[g](e))||(c=e.shift(),d.push({value:c,type:g,matches:e}),j=j.slice(c.length));if(!c)break}return b?j.length:j?y.error(a):Eb(a,q).slice(0)},Ha=function(a){for(var b=0,c=a.length,e="";c>b;b++)e+=a[b].value;return e},ab=function(a,b,c){var e=b.dir,d=c&&"parentNode"===e,g=Gc++;return b.first?function(b,c,g){for(;b=b[e];)if(1===b.nodeType||d)return a(b,c,g)}:function(b,c,h){var r,
t,m,A=Y+" "+g;if(h)for(;b=b[e];){if((1===b.nodeType||d)&&a(b,c,h))return!0}else for(;b=b[e];)if(1===b.nodeType||d)if(m=b[K]||(b[K]={}),(t=m[e])&&t[0]===A){if(!0===(r=t[1])||r===Ka)return!0===r}else if(t=m[e]=[A],t[1]=a(b,c,h)||Ka,!0===t[1])return!0}},bb=function(a){return 1<a.length?function(b,c,e){for(var d=a.length;d--;)if(!a[d](b,c,e))return!1;return!0}:a[0]},La=function(a,b,c,e,d){for(var g,j=[],q=0,h=a.length,r=null!=b;h>q;q++)(g=a[q])&&(!c||c(g,e,d))&&(j.push(g),r&&b.push(q));return j},cb=function(a,
b,c,e,d,g){return e&&!e[K]&&(e=cb(e)),d&&!d[K]&&(d=cb(d,g)),U(function(g,q,h,r){var t,m,A=[],k=[],p=q.length,n;if(!(n=g)){n=b||"*";for(var l=h.nodeType?[h]:h,s=[],u=0,v=l.length;v>u;u++)y(n,l[u],s);n=s}n=!a||!g&&b?n:La(n,A,a,h,r);l=c?d||(g?a:p||e)?[]:q:n;if(c&&c(n,l,h,r),e){t=La(l,k);e(t,[],h,r);for(h=t.length;h--;)(m=t[h])&&(l[k[h]]=!(n[k[h]]=m))}if(g){if(d||a){if(d){t=[];for(h=l.length;h--;)(m=l[h])&&t.push(n[h]=m);d(null,l=[],t,r)}for(h=l.length;h--;)(m=l[h])&&-1<(t=d?ka.call(g,m):A[h])&&(g[t]=
!(q[t]=m))}}else l=La(l===q?l.splice(p,l.length):l),d?d(null,q,l,r):aa.apply(q,l)})},db=function(a){var b,c,e,d=a.length,g=w.relative[a[0].type];c=g||w.relative[" "];for(var j=g?1:0,q=ab(function(a){return a===b},c,!0),h=ab(function(a){return-1<ka.call(b,a)},c,!0),r=[function(a,c,d){return!g&&(d||c!==Ma)||((b=c).nodeType?q(a,c,d):h(a,c,d))}];d>j;j++)if(c=w.relative[a[j].type])r=[ab(bb(r),c)];else{if(c=w.filter[a[j].type].apply(null,a[j].matches),c[K]){for(e=++j;d>e&&!w.relative[a[e].type];e++);return cb(1<
j&&bb(r),1<j&&Ha(a.slice(0,j-1).concat({value:" "===a[j-2].type?"*":""})).replace(Ia,"$1"),c,e>j&&db(a.slice(j,e)),d>e&&db(a=a.slice(e)),d>e&&Ha(a))}r.push(c)}return bb(r)},qa,C,Ka,w,Na,Fb,Ya,Ma,la,ia,M,Z,X,P,ma,Oa,ua,K="sizzle"+-new Date,$=Wa.document,Y=0,Gc=0,Gb=Za(),Eb=Za(),Hb=Za(),ra=!1,eb=function(a,b){return a===b?(ra=!0,0):0},Bb=-2147483648,Hc={}.hasOwnProperty,da=[],Ic=da.pop,Jc=da.push,aa=da.push,Ib=da.slice,ka=da.indexOf||function(a){for(var b=0,c=this.length;c>b;b++)if(this[b]===a)return b;
return-1},Jb="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),Kb="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+Jb+")|)|)[\\x20\\t\\r\\n\\f]*\\]",fb=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+Kb.replace(3,8)+")*)|.*)\\)|)",Ia=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),Ec=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,
Fc=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Xa=/[\x20\t\r\n\f]*[+~]/,Kc=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*)[\\x20\\t\\r\\n\\f]*\\]","g"),Lc=RegExp(fb),Mc=RegExp("^"+Jb+"$"),Ja={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+Kb),PSEUDO:RegExp("^"+fb),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},gb=/^[^{]+\{\s*\[native \w/,Ac=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,Nc=/^(?:input|select|textarea|button)$/i,Oc=/^h\d$/i,Bc=/'|\\/g,ba=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)",
"ig"),ca=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(55296|a>>10,56320|1023&a)};try{aa.apply(da=Ib.call($.childNodes),$.childNodes),da[$.childNodes.length].nodeType}catch(nd){aa={apply:da.length?function(a,b){Jc.apply(a,Ib.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}Fb=y.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};C=y.support={};ia=y.setDocument=function(a){var b=
a?a.ownerDocument||a:$;a=b.defaultView;return b!==M&&9===b.nodeType&&b.documentElement?(M=b,Z=b.documentElement,X=!Fb(b),a&&a.attachEvent&&a!==a.top&&a.attachEvent("onbeforeunload",function(){ia()}),C.attributes=V(function(a){return a.className="i",!a.getAttribute("className")}),C.getElementsByTagName=V(function(a){return a.appendChild(b.createComment("")),!a.getElementsByTagName("*").length}),C.getElementsByClassName=V(function(a){return a.innerHTML="<div class='a'></div><div class='a i'></div>",
a.firstChild.className="i",2===a.getElementsByClassName("i").length}),C.getById=V(function(a){return Z.appendChild(a).id=K,!b.getElementsByName||!b.getElementsByName(K).length}),C.getById?(w.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&X){var d=b.getElementById(a);return d&&d.parentNode?[d]:[]}},w.filter.ID=function(a){var b=a.replace(ba,ca);return function(a){return a.getAttribute("id")===b}}):(delete w.find.ID,w.filter.ID=function(a){var b=a.replace(ba,ca);return function(a){return(a=
"undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}}),w.find.TAG=C.getElementsByTagName?function(a,b){return"undefined"!==typeof b.getElementsByTagName?b.getElementsByTagName(a):void 0}:function(a,b){var d,g=[],j=0,q=b.getElementsByTagName(a);if("*"===a){for(;d=q[j++];)1===d.nodeType&&g.push(d);return g}return q},w.find.CLASS=C.getElementsByClassName&&function(a,b){return"undefined"!==typeof b.getElementsByClassName&&X?b.getElementsByClassName(a):void 0},ma=[],P=[],(C.qsa=
gb.test(b.querySelectorAll))&&(V(function(a){a.innerHTML="<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||P.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||P.push(":checked")}),V(function(a){var d=b.createElement("input");d.setAttribute("type","hidden");a.appendChild(d).setAttribute("t","");a.querySelectorAll("[t^='']").length&&
P.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll(":enabled").length||P.push(":enabled",":disabled");a.querySelectorAll("*,:x");P.push(",.*:")})),(C.matchesSelector=gb.test(Oa=Z.webkitMatchesSelector||Z.mozMatchesSelector||Z.oMatchesSelector||Z.msMatchesSelector))&&V(function(a){C.disconnectedMatch=Oa.call(a,"div");Oa.call(a,"[s!='']:x");ma.push("!=",fb)}),P=P.length&&RegExp(P.join("|")),ma=ma.length&&RegExp(ma.join("|")),ua=gb.test(Z.contains)||Z.compareDocumentPosition?function(a,
b){var d=9===a.nodeType?a.documentElement:a,g=b&&b.parentNode;return a===g||!(!g||1!==g.nodeType||!(d.contains?d.contains(g):a.compareDocumentPosition&&16&a.compareDocumentPosition(g)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1},eb=Z.compareDocumentPosition?function(a,d){if(a===d)return ra=!0,0;var f=d.compareDocumentPosition&&a.compareDocumentPosition&&a.compareDocumentPosition(d);return f?1&f||!C.sortDetached&&d.compareDocumentPosition(a)===f?a===b||ua($,a)?-1:d===b||ua($,
d)?1:la?ka.call(la,a)-ka.call(la,d):0:4&f?-1:1:a.compareDocumentPosition?-1:1}:function(a,d){var f,g=0;f=a.parentNode;var j=d.parentNode,q=[a],h=[d];if(a===d)return ra=!0,0;if(!f||!j)return a===b?-1:d===b?1:f?-1:j?1:la?ka.call(la,a)-ka.call(la,d):0;if(f===j)return Cb(a,d);for(f=a;f=f.parentNode;)q.unshift(f);for(f=d;f=f.parentNode;)h.unshift(f);for(;q[g]===h[g];)g++;return g?Cb(q[g],h[g]):q[g]===$?-1:h[g]===$?1:0},b):M};y.matches=function(a,b){return y(a,null,null,b)};y.matchesSelector=function(a,
b){if((a.ownerDocument||a)!==M&&ia(a),b=b.replace(Kc,"='$1']"),!(!C.matchesSelector||!X||ma&&ma.test(b)||P&&P.test(b)))try{var c=Oa.call(a,b);if(c||C.disconnectedMatch||a.document&&11!==a.document.nodeType)return c}catch(d){}return 0<y(b,M,null,[a]).length};y.contains=function(a,b){return(a.ownerDocument||a)!==M&&ia(a),ua(a,b)};y.attr=function(a,b){(a.ownerDocument||a)!==M&&ia(a);var c=w.attrHandle[b.toLowerCase()],c=c&&Hc.call(w.attrHandle,b.toLowerCase())?c(a,b,!X):void 0;return void 0===c?C.attributes||
!X?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null:c};y.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};y.uniqueSort=function(a){var b,c=[],d=0,f=0;if(ra=!C.detectDuplicates,la=!C.sortStable&&a.slice(0),a.sort(eb),ra){for(;b=a[f++];)b===a[f]&&(d=c.push(f));for(;d--;)a.splice(c[d],1)}return a};Na=y.getText=function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"==typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=
a.nextSibling)c+=Na(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d];d++)c+=Na(b);return c};w=y.selectors={cacheLength:50,createPseudo:U,match:Ja,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){return a[1]=a[1].replace(ba,ca),a[3]=(a[4]||a[5]||"").replace(ba,ca),"~="===a[2]&&(a[3]=" "+a[3]+" "),a.slice(0,4)},CHILD:function(a){return a[1]=a[1].toLowerCase(),
"nth"===a[1].slice(0,3)?(a[3]||y.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&y.error(a[0]),a},PSEUDO:function(a){var b,c=!a[5]&&a[2];return Ja.CHILD.test(a[0])?null:(a[3]&&void 0!==a[4]?a[2]=a[4]:c&&Lc.test(c)&&(b=Ga(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=c.slice(0,b)),a.slice(0,3))}},filter:{TAG:function(a){var b=a.replace(ba,ca).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&
a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=Gb[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&Gb(a,function(a){return b.test("string"==typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")})},ATTR:function(a,b,c){return function(d){d=y.attr(d,a);return null==d?"!="===b:b?(d+="","="===b?d===c:"!="===b?d!==c:"^="===b?c&&0===d.indexOf(c):"*="===b?c&&-1<d.indexOf(c):"$="===b?c&&d.slice(-c.length)===c:"~="===b?
-1<(" "+d+" ").indexOf(c):"|="===b?d===c||d.slice(0,c.length+1)===c+"-":!1):!0}},CHILD:function(a,b,c,d,f){var g="nth"!==a.slice(0,3),j="last"!==a.slice(-4),q="of-type"===b;return 1===d&&0===f?function(a){return!!a.parentNode}:function(b,c,h){var m,A,k,l,n;c=g!==j?"nextSibling":"previousSibling";var p=b.parentNode,s=q&&b.nodeName.toLowerCase();h=!h&&!q;if(p){if(g){for(;c;){for(A=b;A=A[c];)if(q?A.nodeName.toLowerCase()===s:1===A.nodeType)return!1;n=c="only"===a&&!n&&"nextSibling"}return!0}if(n=[j?
p.firstChild:p.lastChild],j&&h){h=p[K]||(p[K]={});m=h[a]||[];l=m[0]===Y&&m[1];k=m[0]===Y&&m[2];for(A=l&&p.childNodes[l];A=++l&&A&&A[c]||(k=l=0)||n.pop();)if(1===A.nodeType&&++k&&A===b){h[a]=[Y,l,k];break}}else if(h&&(m=(b[K]||(b[K]={}))[a])&&m[0]===Y)k=m[1];else for(;(A=++l&&A&&A[c]||(k=l=0)||n.pop())&&(!(q?A.nodeName.toLowerCase()===s:1===A.nodeType)||!++k||!(h&&((A[K]||(A[K]={}))[a]=[Y,k]),A===b)););return k-=f,k===d||0===k%d&&0<=k/d}}},PSEUDO:function(a,b){var c,d=w.pseudos[a]||w.setFilters[a.toLowerCase()]||
y.error("unsupported pseudo: "+a);return d[K]?d(b):1<d.length?(c=[a,a,"",b],w.setFilters.hasOwnProperty(a.toLowerCase())?U(function(a,c){for(var j,q=d(a,b),h=q.length;h--;)j=ka.call(a,q[h]),a[j]=!(c[j]=q[h])}):function(a){return d(a,0,c)}):d}},pseudos:{not:U(function(a){var b=[],c=[],d=Ya(a.replace(Ia,"$1"));return d[K]?U(function(a,b,c,h){var N;c=d(a,null,h,[]);for(h=a.length;h--;)(N=c[h])&&(a[h]=!(b[h]=N))}):function(a,g,j){return b[0]=a,d(b,null,j,c),!c.pop()}}),has:U(function(a){return function(b){return 0<
y(a,b).length}}),contains:U(function(a){return function(b){return-1<(b.textContent||b.innerText||Na(b)).indexOf(a)}}),lang:U(function(a){return Mc.test(a||"")||y.error("unsupported lang: "+a),a=a.replace(ba,ca).toLowerCase(),function(b){var c;do if(c=X?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(a){var b=Wa.location&&Wa.location.hash;return b&&b.slice(1)===a.id},root:function(a){return a===
Z},focus:function(a){return a===M.activeElement&&(!M.hasFocus||M.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){return a.parentNode&&a.parentNode.selectedIndex,!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if("@"<a.nodeName||3===a.nodeType||4===a.nodeType)return!1;
return!0},parent:function(a){return!w.pseudos.empty(a)},header:function(a){return Oc.test(a.nodeName)},input:function(a){return Nc.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||b.toLowerCase()===a.type)},first:ja(function(){return[0]}),last:ja(function(a,b){return[b-1]}),eq:ja(function(a,b,c){return[0>c?c+b:c]}),
even:ja(function(a,b){for(var c=0;b>c;c+=2)a.push(c);return a}),odd:ja(function(a,b){for(var c=1;b>c;c+=2)a.push(c);return a}),lt:ja(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:ja(function(a,b,c){for(c=0>c?c+b:c;b>++c;)a.push(c);return a})}};w.pseudos.nth=w.pseudos.eq;for(qa in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})w.pseudos[qa]=Cc(qa);for(qa in{submit:!0,reset:!0})w.pseudos[qa]=Dc(qa);Db.prototype=w.filters=w.pseudos;w.setFilters=new Db;Ya=y.compile=function(a,b){var c,
d=[],f=[],g=Hb[a+" "];if(!g){b||(b=Ga(a));for(c=b.length;c--;)g=db(b[c]),g[K]?d.push(g):f.push(g);var j=0,h=0<d.length,N=0<f.length;c=function(a,b,c,g,k){var l,n,p=[],s=0,u="0",v=a&&[],D=null!=k,B=Ma,x=a||N&&w.find.TAG("*",k&&b.parentNode||b),E=Y+=null==B?1:Math.random()||0.1;for(D&&(Ma=b!==M&&b,Ka=j);null!=(k=x[u]);u++){if(N&&k){for(l=0;n=f[l++];)if(n(k,b,c)){g.push(k);break}D&&(Y=E,Ka=++j)}h&&((k=!n&&k)&&s--,a&&v.push(k))}if(s+=u,h&&u!==s){for(l=0;n=d[l++];)n(v,p,b,c);if(a){if(0<s)for(;u--;)v[u]||
p[u]||(p[u]=Ic.call(g));p=La(p)}aa.apply(g,p);D&&!a&&0<p.length&&1<s+d.length&&y.uniqueSort(g)}return D&&(Y=E,Ma=B),v};c=h?U(c):c;g=Hb(a,c)}return g};C.sortStable=K.split("").sort(eb).join("")===K;C.detectDuplicates=ra;ia();C.sortDetached=V(function(a){return 1&a.compareDocumentPosition(M.createElement("div"))});V(function(a){return a.innerHTML="<a href='#'></a>","#"===a.firstChild.getAttribute("href")})||$a("type|href|height|width",function(a,b,c){return c?void 0:a.getAttribute(b,"type"===b.toLowerCase()?
1:2)});C.attributes&&V(function(a){return a.innerHTML="<input/>",a.firstChild.setAttribute("value",""),""===a.firstChild.getAttribute("value")})||$a("value",function(a,b,c){return c||"input"!==a.nodeName.toLowerCase()?void 0:a.defaultValue});V(function(a){return null==a.getAttribute("disabled")})||$a("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;return c?void 0:(d=a.getAttributeNode(b))&&d.specified?
d.value:!0===a[b]?b.toLowerCase():null});d.find=y;d.expr=y.selectors;d.expr[":"]=d.expr.pseudos;d.unique=y.uniqueSort;d.text=y.getText;d.isXMLDoc=y.isXML;d.contains=y.contains;var Lb={};d.Callbacks=function(a){var b;if("string"==typeof a){if(!(b=Lb[a])){b=a;var c=Lb[b]={};b=(d.each(b.match(W)||[],function(a,b){c[b]=!0}),c)}}else b=d.extend({},a);a=b;var e,f,g,j,q,k,r=[],t=!a.once&&[],m=function(b){e=a.memory&&b;f=!0;k=j||0;j=0;q=r.length;for(g=!0;r&&q>k;k++)if(!1===r[k].apply(b[0],b[1])&&a.stopOnFalse){e=
!1;break}g=!1;r&&(t?t.length&&m(t.shift()):e?r=[]:l.disable())},l={add:function(){if(r){var b=r.length;(function qc(b){d.each(b,function(b,c){var e=d.type(c);"function"===e?a.unique&&l.has(c)||r.push(c):c&&c.length&&"string"!==e&&qc(c)})})(arguments);g?q=r.length:e&&(j=b,m(e))}return this},remove:function(){return r&&d.each(arguments,function(a,b){for(var c;-1<(c=d.inArray(b,r,c));)r.splice(c,1),g&&(q>=c&&q--,k>=c&&k--)}),this},has:function(a){return a?-1<d.inArray(a,r):!(!r||!r.length)},empty:function(){return r=
[],q=0,this},disable:function(){return r=t=e=h,this},disabled:function(){return!r},lock:function(){return t=h,e||l.disable(),this},locked:function(){return!t},fireWith:function(a,b){return!r||f&&!t||(b=b||[],b=[a,b.slice?b.slice():b],g?t.push(b):m(b)),this},fire:function(){return l.fireWith(this,arguments),this},fired:function(){return!!f}};return l};d.extend({Deferred:function(a){var b=[["resolve","done",d.Callbacks("once memory"),"resolved"],["reject","fail",d.Callbacks("once memory"),"rejected"],
["notify","progress",d.Callbacks("memory")]],c="pending",e={state:function(){return c},always:function(){return f.done(arguments).fail(arguments),this},then:function(){var a=arguments;return d.Deferred(function(c){d.each(b,function(b,h){var k=h[0],t=d.isFunction(a[b])&&a[b];f[h[1]](function(){var a=t&&t.apply(this,arguments);a&&d.isFunction(a.promise)?a.promise().done(c.resolve).fail(c.reject).progress(c.notify):c[k+"With"](this===e?c.promise():this,t?[a]:arguments)})});a=null}).promise()},promise:function(a){return null!=
a?d.extend(a,e):e}},f={};return e.pipe=e.then,d.each(b,function(a,d){var h=d[2],k=d[3];e[d[1]]=h.add;k&&h.add(function(){c=k},b[1^a][2].disable,b[2][2].lock);f[d[0]]=function(){return f[d[0]+"With"](this===f?e:this,arguments),this};f[d[0]+"With"]=h.fireWith}),e.promise(f),a&&a.call(f,f),f},when:function(a){var b=0,c=ha.call(arguments),e=c.length,f=1!==e||a&&d.isFunction(a.promise)?e:0,g=1===f?a:d.Deferred(),j=function(a,b,c){return function(d){b[a]=this;c[a]=1<arguments.length?ha.call(arguments):
d;c===h?g.notifyWith(b,c):--f||g.resolveWith(b,c)}},h,k,r;if(1<e){h=Array(e);k=Array(e);for(r=Array(e);e>b;b++)c[b]&&d.isFunction(c[b].promise)?c[b].promise().done(j(b,r,c)).fail(g.reject).progress(j(b,k,h)):--f}return f||g.resolveWith(r,c),g.promise()}});var Pc=d,Mb,F={},R=x.createElement("input"),Nb=x.createDocumentFragment(),S=x.createElement("div"),Ob=x.createElement("select"),Pb=Ob.appendChild(x.createElement("option"));Mb=R.type?(R.type="checkbox",F.checkOn=""!==R.value,F.optSelected=Pb.selected,
F.reliableMarginRight=!0,F.boxSizingReliable=!0,F.pixelPosition=!1,R.checked=!0,F.noCloneChecked=R.cloneNode(!0).checked,Ob.disabled=!0,F.optDisabled=!Pb.disabled,R=x.createElement("input"),R.value="t",R.type="radio",F.radioValue="t"===R.value,R.setAttribute("checked","t"),R.setAttribute("name","t"),Nb.appendChild(R),F.checkClone=Nb.cloneNode(!0).cloneNode(!0).lastChild.checked,F.focusinBubbles="onfocusin"in l,S.style.backgroundClip="content-box",S.cloneNode(!0).style.backgroundClip="",F.clearCloneStyle=
"content-box"===S.style.backgroundClip,d(function(){var a,b,c=x.getElementsByTagName("body")[0];c&&(a=x.createElement("div"),a.style.cssText="border:0;width:0;height:0;position:absolute;top:0;left:-9999px;margin-top:1px",c.appendChild(a).appendChild(S),S.innerHTML="",S.style.cssText="-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%",d.swap(c,null!=c.style.zoom?{zoom:1}:{},function(){F.boxSizing=
4===S.offsetWidth}),l.getComputedStyle&&(F.pixelPosition="1%"!==(l.getComputedStyle(S,null)||{}).top,F.boxSizingReliable="4px"===(l.getComputedStyle(S,null)||{width:"4px"}).width,b=S.appendChild(x.createElement("div")),b.style.cssText=S.style.cssText="padding:0;margin:0;border:0;display:block;-webkit-box-sizing:content-box;-moz-box-sizing:content-box;box-sizing:content-box",b.style.marginRight=b.style.width="0",S.style.width="1px",F.reliableMarginRight=!parseFloat((l.getComputedStyle(b,null)||{}).marginRight)),
c.removeChild(a))}),F):F;Pc.support=Mb;var I,v,kc=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,jc=/([A-Z])/g;k.uid=1;k.accepts=function(a){return a.nodeType?1===a.nodeType||9===a.nodeType:!0};k.prototype={key:function(a){if(!k.accepts(a))return 0;var b={},c=a[this.expando];if(!c){c=k.uid++;try{b[this.expando]={value:c},Object.defineProperties(a,b)}catch(e){b[this.expando]=c,d.extend(a,b)}}return this.cache[c]||(this.cache[c]={}),c},set:function(a,b,c){var e;a=this.key(a);var f=this.cache[a];if("string"==typeof b)f[b]=
c;else if(d.isEmptyObject(f))d.extend(this.cache[a],b);else for(e in b)f[e]=b[e];return f},get:function(a,b){var c=this.cache[this.key(a)];return b===h?c:c[b]},access:function(a,b,c){var e;return b===h||b&&"string"==typeof b&&c===h?(e=this.get(a,b),e!==h?e:this.get(a,d.camelCase(b))):(this.set(a,b,c),c!==h?c:b)},remove:function(a,b){var c,e,f=this.key(a),g=this.cache[f];if(b===h)this.cache[f]={};else{d.isArray(b)?e=b.concat(b.map(d.camelCase)):(c=d.camelCase(b),b in g?e=[b,c]:(e=c,e=e in g?[e]:e.match(W)||
[]));for(c=e.length;c--;)delete g[e[c]]}},hasData:function(a){return!d.isEmptyObject(this.cache[a[this.expando]]||{})},discard:function(a){a[this.expando]&&delete this.cache[a[this.expando]]}};I=new k;v=new k;d.extend({acceptData:k.accepts,hasData:function(a){return I.hasData(a)||v.hasData(a)},data:function(a,b,c){return I.access(a,b,c)},removeData:function(a,b){I.remove(a,b)},_data:function(a,b,c){return v.access(a,b,c)},_removeData:function(a,b){v.remove(a,b)}});d.fn.extend({data:function(a,b){var c,
e,f=this[0],g=0,j=null;if(a===h){if(this.length&&(j=I.get(f),1===f.nodeType&&!v.get(f,"hasDataAttrs"))){for(c=f.attributes;c.length>g;g++)e=c[g].name,0===e.indexOf("data-")&&(e=d.camelCase(e.slice(5)),n(f,e,j[e]));v.set(f,"hasDataAttrs",!0)}return j}return"object"==typeof a?this.each(function(){I.set(this,a)}):d.access(this,function(b){var c,e=d.camelCase(a);if(f&&b===h){if((c=I.get(f,a),c!==h)||(c=I.get(f,e),c!==h)||(c=n(f,e,h),c!==h))return c}else this.each(function(){var c=I.get(this,e);I.set(this,
e,b);-1!==a.indexOf("-")&&c!==h&&I.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){I.remove(this,a)})}});d.extend({queue:function(a,b,c){var e;return a?(b=(b||"fx")+"queue",e=v.get(a,b),c&&(!e||d.isArray(c)?e=v.access(a,b,d.makeArray(c)):e.push(c)),e||[]):h},dequeue:function(a,b){b=b||"fx";var c=d.queue(a,b),e=c.length,f=c.shift(),g=d._queueHooks(a,b),j=function(){d.dequeue(a,b)};"inprogress"===f&&(f=c.shift(),e--);f&&("fx"===b&&c.unshift("inprogress"),
delete g.stop,f.call(a,j,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var c=b+"queueHooks";return v.get(a,c)||v.access(a,c,{empty:d.Callbacks("once memory").add(function(){v.remove(a,[b+"queue",c])})})}});d.fn.extend({queue:function(a,b){var c=2;return"string"!=typeof a&&(b=a,a="fx",c--),c>arguments.length?d.queue(this[0],a):b===h?this:this.each(function(){var c=d.queue(this,a,b);d._queueHooks(this,a);"fx"===a&&"inprogress"!==c[0]&&d.dequeue(this,a)})},dequeue:function(a){return this.each(function(){d.dequeue(this,
a)})},delay:function(a,b){return a=d.fx?d.fx.speeds[a]||a:a,b=b||"fx",this.queue(b,function(b,d){var f=setTimeout(b,a);d.stop=function(){clearTimeout(f)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var c,e=1,f=d.Deferred(),g=this,j=this.length,q=function(){--e||f.resolveWith(g,[g])};"string"!=typeof a&&(b=a,a=h);for(a=a||"fx";j--;)(c=v.get(g[j],a+"queueHooks"))&&c.empty&&(e++,c.empty.add(q));return q(),f.promise(b)}});var Qb,hb=/[\t\r\n\f]/g,Qc=/\r/g,Rc=/^(?:input|select|textarea|button)$/i;
d.fn.extend({attr:function(a,b){return d.access(this,d.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){d.removeAttr(this,a)})},prop:function(a,b){return d.access(this,d.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[d.propFix[a]||a]})},addClass:function(a){var b,c,e,f,g,j=0,h=this.length;b="string"==typeof a&&a;if(d.isFunction(a))return this.each(function(b){d(this).addClass(a.call(this,b,this.className))});if(b)for(b=
(a||"").match(W)||[];h>j;j++)if(c=this[j],e=1===c.nodeType&&(c.className?(" "+c.className+" ").replace(hb," "):" ")){for(g=0;f=b[g++];)0>e.indexOf(" "+f+" ")&&(e+=f+" ");c.className=d.trim(e)}return this},removeClass:function(a){var b,c,e,f,g,j=0,h=this.length;b=0===arguments.length||"string"==typeof a&&a;if(d.isFunction(a))return this.each(function(b){d(this).removeClass(a.call(this,b,this.className))});if(b)for(b=(a||"").match(W)||[];h>j;j++)if(c=this[j],e=1===c.nodeType&&(c.className?(" "+c.className+
" ").replace(hb," "):"")){for(g=0;f=b[g++];)for(;0<=e.indexOf(" "+f+" ");)e=e.replace(" "+f+" "," ");c.className=a?d.trim(e):""}return this},toggleClass:function(a,b){var c=typeof a;return"boolean"==typeof b&&"string"===c?b?this.addClass(a):this.removeClass(a):d.isFunction(a)?this.each(function(c){d(this).toggleClass(a.call(this,c,this.className,b),b)}):this.each(function(){if("string"===c)for(var b,f=0,g=d(this),j=a.match(W)||[];b=j[f++];)g.hasClass(b)?g.removeClass(b):g.addClass(b);else(c===Ba||
"boolean"===c)&&(this.className&&v.set(this,"__className__",this.className),this.className=this.className||!1===a?"":v.get(this,"__className__")||"")})},hasClass:function(a){a=" "+a+" ";for(var b=0,c=this.length;c>b;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(hb," ").indexOf(a))return!0;return!1},val:function(a){var b,c,e,f=this[0];if(arguments.length)return e=d.isFunction(a),this.each(function(c){var f;1===this.nodeType&&(f=e?a.call(this,c,d(this).val()):a,null==f?f="":"number"==
typeof f?f+="":d.isArray(f)&&(f=d.map(f,function(a){return null==a?"":a+""})),b=d.valHooks[this.type]||d.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&b.set(this,f,"value")!==h||(this.value=f))});if(f)return b=d.valHooks[f.type]||d.valHooks[f.nodeName.toLowerCase()],b&&"get"in b&&(c=b.get(f,"value"))!==h?c:(c=f.value,"string"==typeof c?c.replace(Qc,""):null==c?"":c)}});d.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){for(var b,
c=a.options,e=a.selectedIndex,f="select-one"===a.type||0>e,g=f?null:[],j=f?e+1:c.length,h=0>e?j:f?e:0;j>h;h++)if(b=c[h],!(!b.selected&&h!==e||(d.support.optDisabled?b.disabled:null!==b.getAttribute("disabled"))||b.parentNode.disabled&&d.nodeName(b.parentNode,"optgroup"))){if(a=d(b).val(),f)return a;g.push(a)}return g},set:function(a,b){for(var c,e,f=a.options,g=d.makeArray(b),j=f.length;j--;)e=f[j],(e.selected=0<=d.inArray(d(e).val(),g))&&(c=!0);return c||(a.selectedIndex=-1),g}}},attr:function(a,
b,c){var e,f,g=a.nodeType;if(a&&3!==g&&8!==g&&2!==g)return typeof a.getAttribute===Ba?d.prop(a,b,c):(1===g&&d.isXMLDoc(a)||(b=b.toLowerCase(),e=d.attrHooks[b]||(d.expr.match.bool.test(b)?Qb:void 0)),c===h?e&&"get"in e&&null!==(f=e.get(a,b))?f:(f=d.find.attr(a,b),null==f?h:f):null!==c?e&&"set"in e&&(f=e.set(a,c,b))!==h?f:(a.setAttribute(b,c+""),c):(d.removeAttr(a,b),h))},removeAttr:function(a,b){var c,e,f=0,g=b&&b.match(W);if(g&&1===a.nodeType)for(;c=g[f++];)e=d.propFix[c]||c,d.expr.match.bool.test(c)&&
(a[e]=!1),a.removeAttribute(c)},attrHooks:{type:{set:function(a,b){if(!d.support.radioValue&&"radio"===b&&d.nodeName(a,"input")){var c=a.value;return a.setAttribute("type",b),c&&(a.value=c),b}}}},propFix:{"for":"htmlFor","class":"className"},prop:function(a,b,c){var e,f,g,j=a.nodeType;if(a&&3!==j&&8!==j&&2!==j)return g=1!==j||!d.isXMLDoc(a),g&&(b=d.propFix[b]||b,f=d.propHooks[b]),c!==h?f&&"set"in f&&(e=f.set(a,c,b))!==h?e:a[b]=c:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]},propHooks:{tabIndex:{get:function(a){return a.hasAttribute("tabindex")||
Rc.test(a.nodeName)||a.href?a.tabIndex:-1}}}});Qb={set:function(a,b,c){return!1===b?d.removeAttr(a,c):a.setAttribute(c,c),c}};d.each(d.expr.match.bool.source.match(/\w+/g),function(a,b){var c=d.expr.attrHandle[b]||d.find.attr;d.expr.attrHandle[b]=function(a,b,g){var j=d.expr.attrHandle[b];a=g?h:(d.expr.attrHandle[b]=h)!=c(a,b,g)?b.toLowerCase():null;return d.expr.attrHandle[b]=j,a}});d.support.optSelected||(d.propHooks.selected={get:function(a){a=a.parentNode;return a&&a.parentNode&&a.parentNode.selectedIndex,
null}});d.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){d.propFix[this.toLowerCase()]=this});d.each(["radio","checkbox"],function(){d.valHooks[this]={set:function(a,b){return d.isArray(b)?a.checked=0<=d.inArray(d(a).val(),b):h}};d.support.checkOn||(d.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});var Sc=/^key/,Tc=/^(?:mouse|contextmenu)|click/,Rb=/^(?:focusinfocus|focusoutblur)$/,
Sb=/^([^.]*)(?:\.(.+)|)$/;d.event={global:{},add:function(a,b,c,e,f){var g,j,q,k,r,l,m,p,n,s;if(r=v.get(a)){c.handler&&(g=c,c=g.handler,f=g.selector);c.guid||(c.guid=d.guid++);(k=r.events)||(k=r.events={});(j=r.handle)||(j=r.handle=function(a){return typeof d===Ba||a&&d.event.triggered===a.type?h:d.event.dispatch.apply(j.elem,arguments)},j.elem=a);b=(b||"").match(W)||[""];for(r=b.length;r--;)q=Sb.exec(b[r])||[],n=s=q[1],q=(q[2]||"").split(".").sort(),n&&(m=d.event.special[n]||{},n=(f?m.delegateType:
m.bindType)||n,m=d.event.special[n]||{},l=d.extend({type:n,origType:s,data:e,handler:c,guid:c.guid,selector:f,needsContext:f&&d.expr.match.needsContext.test(f),namespace:q.join(".")},g),(p=k[n])||(p=k[n]=[],p.delegateCount=0,m.setup&&!1!==m.setup.call(a,e,q,j)||a.addEventListener&&a.addEventListener(n,j,!1)),m.add&&(m.add.call(a,l),l.handler.guid||(l.handler.guid=c.guid)),f?p.splice(p.delegateCount++,0,l):p.push(l),d.event.global[n]=!0);a=null}},remove:function(a,b,c,e,f){var g,j,h,k,r,l,m,n,p,s,
u,D=v.hasData(a)&&v.get(a);if(D&&(k=D.events)){b=(b||"").match(W)||[""];for(r=b.length;r--;)if(h=Sb.exec(b[r])||[],p=u=h[1],s=(h[2]||"").split(".").sort(),p){m=d.event.special[p]||{};p=(e?m.delegateType:m.bindType)||p;n=k[p]||[];h=h[2]&&RegExp("(^|\\.)"+s.join("\\.(?:.*\\.|)")+"(\\.|$)");for(j=g=n.length;g--;)l=n[g],!f&&u!==l.origType||c&&c.guid!==l.guid||h&&!h.test(l.namespace)||e&&e!==l.selector&&("**"!==e||!l.selector)||(n.splice(g,1),l.selector&&n.delegateCount--,m.remove&&m.remove.call(a,l));
j&&!n.length&&(m.teardown&&!1!==m.teardown.call(a,s,D.handle)||d.removeEvent(a,p,D.handle),delete k[p])}else for(p in k)d.event.remove(a,p+b[r],c,e,!0);d.isEmptyObject(k)&&(delete D.handle,v.remove(a,"events"))}},trigger:function(a,b,c,e){var f,g,j,q,k,r,n,m=[c||x],p=Va.call(a,"type")?a.type:a;f=Va.call(a,"namespace")?a.namespace.split("."):[];if(g=j=c=c||x,3!==c.nodeType&&8!==c.nodeType&&!Rb.test(p+d.event.triggered)&&(0<=p.indexOf(".")&&(f=p.split("."),p=f.shift(),f.sort()),k=0>p.indexOf(":")&&
"on"+p,a=a[d.expando]?a:new d.Event(p,"object"==typeof a&&a),a.isTrigger=e?2:3,a.namespace=f.join("."),a.namespace_re=a.namespace?RegExp("(^|\\.)"+f.join("\\.(?:.*\\.|)")+"(\\.|$)"):null,a.result=h,a.target||(a.target=c),b=null==b?[a]:d.makeArray(b,[a]),n=d.event.special[p]||{},e||!n.trigger||!1!==n.trigger.apply(c,b))){if(!e&&!n.noBubble&&!d.isWindow(c)){q=n.delegateType||p;for(Rb.test(q+p)||(g=g.parentNode);g;g=g.parentNode)m.push(g),j=g;j===(c.ownerDocument||x)&&m.push(j.defaultView||j.parentWindow||
l)}for(f=0;(g=m[f++])&&!a.isPropagationStopped();)a.type=1<f?q:n.bindType||p,(r=(v.get(g,"events")||{})[a.type]&&v.get(g,"handle"))&&r.apply(g,b),(r=k&&g[k])&&d.acceptData(g)&&r.apply&&!1===r.apply(g,b)&&a.preventDefault();return a.type=p,e||a.isDefaultPrevented()||n._default&&!1!==n._default.apply(m.pop(),b)||!d.acceptData(c)||k&&d.isFunction(c[p])&&!d.isWindow(c)&&(j=c[k],j&&(c[k]=null),d.event.triggered=p,c[p](),d.event.triggered=h,j&&(c[k]=j)),a.result}},dispatch:function(a){a=d.event.fix(a);
var b,c,e,f,g,j=[],q=ha.call(arguments);b=(v.get(this,"events")||{})[a.type]||[];var k=d.event.special[a.type]||{};if(q[0]=a,a.delegateTarget=this,!k.preDispatch||!1!==k.preDispatch.call(this,a)){j=d.event.handlers.call(this,a,b);for(b=0;(f=j[b++])&&!a.isPropagationStopped();){a.currentTarget=f.elem;for(c=0;(g=f.handlers[c++])&&!a.isImmediatePropagationStopped();)(!a.namespace_re||a.namespace_re.test(g.namespace))&&(a.handleObj=g,a.data=g.data,e=((d.event.special[g.origType]||{}).handle||g.handler).apply(f.elem,
q),e!==h&&!1===(a.result=e)&&(a.preventDefault(),a.stopPropagation()))}return k.postDispatch&&k.postDispatch.call(this,a),a.result}},handlers:function(a,b){var c,e,f,g,j=[],q=b.delegateCount,k=a.target;if(q&&k.nodeType&&(!a.button||"click"!==a.type))for(;k!==this;k=k.parentNode||this)if(!0!==k.disabled||"click"!==a.type){e=[];for(c=0;q>c;c++)g=b[c],f=g.selector+" ",e[f]===h&&(e[f]=g.needsContext?0<=d(f,this).index(k):d.find(f,this,null,[k]).length),e[f]&&e.push(g);e.length&&j.push({elem:k,handlers:e})}return b.length>
q&&j.push({elem:this,handlers:b.slice(q)}),j},props:"altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){return null==a.which&&(a.which=null!=b.charCode?b.charCode:b.keyCode),a}},mouseHooks:{props:"button buttons clientX clientY offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var c,d,f,g=b.button;return null==
a.pageX&&null!=b.clientX&&(c=a.target.ownerDocument||x,d=c.documentElement,f=c.body,a.pageX=b.clientX+(d&&d.scrollLeft||f&&f.scrollLeft||0)-(d&&d.clientLeft||f&&f.clientLeft||0),a.pageY=b.clientY+(d&&d.scrollTop||f&&f.scrollTop||0)-(d&&d.clientTop||f&&f.clientTop||0)),a.which||g===h||(a.which=1&g?1:2&g?3:4&g?2:0),a}},fix:function(a){if(a[d.expando])return a;var b,c,e;b=a.type;var f=a,g=this.fixHooks[b];g||(this.fixHooks[b]=g=Tc.test(b)?this.mouseHooks:Sc.test(b)?this.keyHooks:{});e=g.props?this.props.concat(g.props):
this.props;a=new d.Event(f);for(b=e.length;b--;)c=e[b],a[c]=f[c];return a.target||(a.target=x),3===a.target.nodeType&&(a.target=a.target.parentNode),g.filter?g.filter(a,f):a},special:{load:{noBubble:!0},focus:{trigger:function(){return this!==D()&&this.focus?(this.focus(),!1):h},delegateType:"focusin"},blur:{trigger:function(){return this===D()&&this.blur?(this.blur(),!1):h},delegateType:"focusout"},click:{trigger:function(){return"checkbox"===this.type&&this.click&&d.nodeName(this,"input")?(this.click(),
!1):h},_default:function(a){return d.nodeName(a.target,"a")}},beforeunload:{postDispatch:function(a){a.result!==h&&(a.originalEvent.returnValue=a.result)}}},simulate:function(a,b,c,e){a=d.extend(new d.Event,c,{type:a,isSimulated:!0,originalEvent:{}});e?d.event.trigger(a,null,b):d.event.dispatch.call(b,a);a.isDefaultPrevented()&&c.preventDefault()}};d.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};d.Event=function(a,b){return this instanceof d.Event?(a&&a.type?(this.originalEvent=
a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||a.getPreventDefault&&a.getPreventDefault()?s:u):this.type=a,b&&d.extend(this,b),this.timeStamp=a&&a.timeStamp||d.now(),this[d.expando]=!0,h):new d.Event(a,b)};d.Event.prototype={isDefaultPrevented:u,isPropagationStopped:u,isImmediatePropagationStopped:u,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=s;a&&a.preventDefault&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=
s;a&&a.stopPropagation&&a.stopPropagation()},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=s;this.stopPropagation()}};d.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){d.event.special[a]={delegateType:b,bindType:b,handle:function(a){var e,f=a.relatedTarget,g=a.handleObj;return(!f||f!==this&&!d.contains(this,f))&&(a.type=g.origType,e=g.handler.apply(this,arguments),a.type=b),e}}});d.support.focusinBubbles||d.each({focus:"focusin",blur:"focusout"},function(a,
b){var c=0,e=function(a){d.event.simulate(b,a.target,d.event.fix(a),!0)};d.event.special[b]={setup:function(){0===c++&&x.addEventListener(a,e,!0)},teardown:function(){0===--c&&x.removeEventListener(a,e,!0)}}});d.fn.extend({on:function(a,b,c,e,f){var g,j;if("object"==typeof a){"string"!=typeof b&&(c=c||b,b=h);for(j in a)this.on(j,b,c,a[j],f);return this}if(null==c&&null==e?(e=b,c=b=h):null==e&&("string"==typeof b?(e=c,c=h):(e=c,c=b,b=h)),!1===e)e=u;else if(!e)return this;return 1===f&&(g=e,e=function(a){return d().off(a),
g.apply(this,arguments)},e.guid=g.guid||(g.guid=d.guid++)),this.each(function(){d.event.add(this,a,e,c,b)})},one:function(a,b,c,d){return this.on(a,b,c,d,1)},off:function(a,b,c){var e,f;if(a&&a.preventDefault&&a.handleObj)return e=a.handleObj,d(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler),this;if("object"==typeof a){for(f in a)this.off(f,b,a[f]);return this}return(!1===b||"function"==typeof b)&&(c=b,b=h),!1===c&&(c=u),this.each(function(){d.event.remove(this,
a,c,b)})},trigger:function(a,b){return this.each(function(){d.event.trigger(a,b,this)})},triggerHandler:function(a,b){var c=this[0];return c?d.event.trigger(a,b,c,!0):h}});var lc=/^.[^:#\[\.,]*$/,Uc=/^(?:parents|prev(?:Until|All))/,Tb=d.expr.match.needsContext,Vc={children:!0,contents:!0,next:!0,prev:!0};d.fn.extend({find:function(a){var b,c=[],e=this,f=e.length;if("string"!=typeof a)return this.pushStack(d(a).filter(function(){for(b=0;f>b;b++)if(d.contains(e[b],this))return!0}));for(b=0;f>b;b++)d.find(a,
e[b],c);return c=this.pushStack(1<f?d.unique(c):c),c.selector=this.selector?this.selector+" "+a:a,c},has:function(a){var b=d(a,this),c=b.length;return this.filter(function(){for(var a=0;c>a;a++)if(d.contains(this,b[a]))return!0})},not:function(a){return this.pushStack(H(this,a||[],!0))},filter:function(a){return this.pushStack(H(this,a||[],!1))},is:function(a){return!!H(this,"string"==typeof a&&Tb.test(a)?d(a):a||[],!1).length},closest:function(a,b){for(var c,e=0,f=this.length,g=[],j=Tb.test(a)||
"string"!=typeof a?d(a,b||this.context):0;f>e;e++)for(c=this[e];c&&c!==b;c=c.parentNode)if(11>c.nodeType&&(j?-1<j.index(c):1===c.nodeType&&d.find.matchesSelector(c,a))){g.push(c);break}return this.pushStack(1<g.length?d.unique(g):g)},index:function(a){return a?"string"==typeof a?xa.call(d(a),this[0]):xa.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){var c="string"==typeof a?d(a,b):d.makeArray(a&&a.nodeType?[a]:a),c=d.merge(this.get(),c);
return this.pushStack(d.unique(c))},addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});d.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return d.dir(a,"parentNode")},parentsUntil:function(a,b,c){return d.dir(a,"parentNode",c)},next:function(a){return E(a,"nextSibling")},prev:function(a){return E(a,"previousSibling")},nextAll:function(a){return d.dir(a,"nextSibling")},prevAll:function(a){return d.dir(a,"previousSibling")},
nextUntil:function(a,b,c){return d.dir(a,"nextSibling",c)},prevUntil:function(a,b,c){return d.dir(a,"previousSibling",c)},siblings:function(a){return d.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return d.sibling(a.firstChild)},contents:function(a){return a.contentDocument||d.merge([],a.childNodes)}},function(a,b){d.fn[a]=function(c,e){var f=d.map(this,b,c);return"Until"!==a.slice(-5)&&(e=c),e&&"string"==typeof e&&(f=d.filter(e,f)),1<this.length&&(Vc[a]||d.unique(f),Uc.test(a)&&
f.reverse()),this.pushStack(f)}});d.extend({filter:function(a,b,c){var e=b[0];return c&&(a=":not("+a+")"),1===b.length&&1===e.nodeType?d.find.matchesSelector(e,a)?[e]:[]:d.find.matches(a,d.grep(b,function(a){return 1===a.nodeType}))},dir:function(a,b,c){for(var e=[],f=c!==h;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&d(a).is(c))break;e.push(a)}return e},sibling:function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c}});var Ub=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,
Vb=/<([\w:]+)/,Wc=/<|&#?\w+;/,Xc=/<(?:script|style|link)/i,Wb=/^(?:checkbox|radio)$/i,Yc=/checked\s*(?:[^=]|=\s*.checked.)/i,Xb=/^$|\/(?:java|ecma)script/i,mc=/^true\/(.*)/,Zc=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g,T={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};T.optgroup=T.option;T.tbody=T.tfoot=
T.colgroup=T.caption=T.thead;T.th=T.td;d.fn.extend({text:function(a){return d.access(this,function(a){return a===h?d.text(this):this.empty().append((this[0]&&this[0].ownerDocument||x).createTextNode(a))},null,a,arguments.length)},append:function(){return this.domManip(arguments,function(a){(1===this.nodeType||11===this.nodeType||9===this.nodeType)&&J(this,a).appendChild(a)})},prepend:function(){return this.domManip(arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=
J(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return this.domManip(arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this.nextSibling)})},remove:function(a,b){for(var c,e=a?d.filter(a,this):this,f=0;null!=(c=e[f]);f++)b||1!==c.nodeType||d.cleanData(G(c)),c.parentNode&&(b&&d.contains(c.ownerDocument,c)&&Q(G(c,"script")),c.parentNode.removeChild(c));
return this},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(d.cleanData(G(a,!1)),a.textContent="");return this},clone:function(a,b){return a=null==a?!1:a,b=null==b?a:b,this.map(function(){return d.clone(this,a,b)})},html:function(a){return d.access(this,function(a){var c=this[0]||{},e=0,f=this.length;if(a===h&&1===c.nodeType)return c.innerHTML;if("string"==typeof a&&!Xc.test(a)&&!T[(Vb.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(Ub,"<$1></$2>");try{for(;f>e;e++)c=this[e]||
{},1===c.nodeType&&(d.cleanData(G(c,!1)),c.innerHTML=a);c=0}catch(g){}}c&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=d.map(this,function(a){return[a.nextSibling,a.parentNode]}),b=0;return this.domManip(arguments,function(c){var e=a[b++],f=a[b++];f&&(e&&e.parentNode!==f&&(e=this.nextSibling),d(this).remove(),f.insertBefore(c,e))},!0),b?this:this.remove()},detach:function(a){return this.remove(a,!0)},domManip:function(a,b,c){a=zb.apply([],a);var e,f,g,j,h=0,k=this.length,
p=this,l=k-1,m=a[0],n=d.isFunction(m);if(n||!(1>=k||"string"!=typeof m||d.support.checkClone)&&Yc.test(m))return this.each(function(d){var e=p.eq(d);n&&(a[0]=m.call(this,d,e.html()));e.domManip(a,b,c)});if(k&&(e=d.buildFragment(a,this[0].ownerDocument,!1,!c&&this),f=e.firstChild,1===e.childNodes.length&&(e=f),f)){f=d.map(G(e,"script"),hc);for(g=f.length;k>h;h++)j=e,h!==l&&(j=d.clone(j,!0,!0),g&&d.merge(f,G(j,"script"))),b.call(this[h],j,h);if(g){e=f[f.length-1].ownerDocument;d.map(f,ic);for(h=0;g>
h;h++)j=f[h],Xb.test(j.type||"")&&!v.access(j,"globalEval")&&d.contains(e,j)&&(j.src?d._evalUrl(j.src):d.globalEval(j.textContent.replace(Zc,"")))}}return this}});d.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){d.fn[a]=function(a){for(var e=[],f=d(a),g=f.length-1,j=0;g>=j;j++)a=j===g?this:this.clone(!0),d(f[j])[b](a),Ua.apply(e,a.get());return this.pushStack(e)}});d.extend({clone:function(a,b,c){var e,f,g,j,h=a.cloneNode(!0),
k=d.contains(a.ownerDocument,a);if(!d.support.noCloneChecked&&!(1!==a.nodeType&&11!==a.nodeType||d.isXMLDoc(a))){j=G(h);g=G(a);e=0;for(f=g.length;f>e;e++){var p=g[e],l=j[e],m=l.nodeName.toLowerCase();"input"===m&&Wb.test(p.type)?l.checked=p.checked:("input"===m||"textarea"===m)&&(l.defaultValue=p.defaultValue)}}if(b)if(c){g=g||G(a);j=j||G(h);e=0;for(f=g.length;f>e;e++)fa(g[e],j[e])}else fa(a,h);return j=G(h,"script"),0<j.length&&Q(j,!k&&G(a,"script")),h},buildFragment:function(a,b,c,e){for(var f,
g,j,h,k=0,p=a.length,l=b.createDocumentFragment(),m=[];p>k;k++)if(f=a[k],f||0===f)if("object"===d.type(f))d.merge(m,f.nodeType?[f]:f);else if(Wc.test(f)){g=g||l.appendChild(b.createElement("div"));j=(Vb.exec(f)||["",""])[1].toLowerCase();j=T[j]||T._default;g.innerHTML=j[1]+f.replace(Ub,"<$1></$2>")+j[2];for(j=j[0];j--;)g=g.lastChild;d.merge(m,g.childNodes);g=l.firstChild;g.textContent=""}else m.push(b.createTextNode(f));l.textContent="";for(k=0;f=m[k++];)if((!e||-1===d.inArray(f,e))&&(h=d.contains(f.ownerDocument,
f),g=G(l.appendChild(f),"script"),h&&Q(g),c))for(j=0;f=g[j++];)Xb.test(f.type||"")&&c.push(f);return l},cleanData:function(a){for(var b,c,e,f,g,j,q=d.event.special,p=0;(c=a[p])!==h;p++){if(k.accepts(c)&&(g=c[v.expando],g&&(b=v.cache[g]))){if(e=Object.keys(b.events||{}),e.length)for(j=0;(f=e[j])!==h;j++)q[f]?d.event.remove(c,f):d.removeEvent(c,f,b.handle);v.cache[g]&&delete v.cache[g]}delete I.cache[c[I.expando]]}},_evalUrl:function(a){return d.ajax({url:a,type:"GET",dataType:"script",async:!1,global:!1,
"throws":!0})}});d.fn.extend({wrapAll:function(a){var b;return d.isFunction(a)?this.each(function(b){d(this).wrapAll(a.call(this,b))}):(this[0]&&(b=d(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&b.insertBefore(this[0]),b.map(function(){for(var a=this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this)),this)},wrapInner:function(a){return d.isFunction(a)?this.each(function(b){d(this).wrapInner(a.call(this,b))}):this.each(function(){var b=d(this),c=b.contents();c.length?
c.wrapAll(a):b.append(a)})},wrap:function(a){var b=d.isFunction(a);return this.each(function(c){d(this).wrapAll(b?a.call(this,c):a)})},unwrap:function(){return this.parent().each(function(){d.nodeName(this,"body")||d(this).replaceWith(this.childNodes)}).end()}});var oa,sa,$c=/^(none|table(?!-c[ea]).+)/,Yb=/^margin/,oc=RegExp("^("+Ea+")(.*)$","i"),Qa=RegExp("^("+Ea+")(?!px)[a-z%]+$","i"),ad=RegExp("^([+-])=("+Ea+")","i"),qb={BODY:"block"},bd={position:"absolute",visibility:"hidden",display:"block"},
Zb={letterSpacing:0,fontWeight:400},ga=["Top","Right","Bottom","Left"],lb=["Webkit","O","Moz","ms"];d.fn.extend({css:function(a,b){return d.access(this,function(a,b,f){var g,j={},k=0;if(d.isArray(b)){f=l.getComputedStyle(a,null);for(g=b.length;g>k;k++)j[b[k]]=d.css(a,b[k],!1,f);return j}return f!==h?d.style(a,b,f):d.css(a,b)},a,b,1<arguments.length)},show:function(){return mb(this,!0)},hide:function(){return mb(this)},toggle:function(a){return"boolean"==typeof a?a?this.show():this.hide():this.each(function(){z(this)?
d(this).show():d(this).hide()})}});d.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=oa(a,"opacity");return""===c?"1":c}}}},cssNumber:{columnCount:!0,fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,c,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g,j,k=d.camelCase(b),p=a.style;return b=d.cssProps[k]||(d.cssProps[k]=O(p,k)),j=d.cssHooks[b]||d.cssHooks[k],c===h?j&&"get"in j&&(f=
j.get(a,!1,e))!==h?f:p[b]:(g=typeof c,"string"===g&&(f=ad.exec(c))&&(c=(f[1]+1)*f[2]+parseFloat(d.css(a,b)),g="number"),null==c||"number"===g&&isNaN(c)||("number"!==g||d.cssNumber[k]||(c+="px"),d.support.clearCloneStyle||""!==c||0!==b.indexOf("background")||(p[b]="inherit"),j&&"set"in j&&(c=j.set(a,c,e))===h||(p[b]=c)),h)}},css:function(a,b,c,e){var f,g,j,k=d.camelCase(b);return b=d.cssProps[k]||(d.cssProps[k]=O(a.style,k)),j=d.cssHooks[b]||d.cssHooks[k],j&&"get"in j&&(f=j.get(a,!0,c)),f===h&&(f=
oa(a,b,e)),"normal"===f&&b in Zb&&(f=Zb[b]),""===c||c?(g=parseFloat(f),!0===c||d.isNumeric(g)?g||0:f):f}});oa=function(a,b,c){var e,f,g,j=(c=c||l.getComputedStyle(a,null))?c.getPropertyValue(b)||c[b]:h,k=a.style;return c&&(""!==j||d.contains(a.ownerDocument,a)||(j=d.style(a,b)),Qa.test(j)&&Yb.test(b)&&(e=k.width,f=k.minWidth,g=k.maxWidth,k.minWidth=k.maxWidth=k.width=j,j=c.width,k.width=e,k.minWidth=f,k.maxWidth=g)),j};d.each(["height","width"],function(a,b){d.cssHooks[b]={get:function(a,e,f){return e?
0===a.offsetWidth&&$c.test(d.css(a,"display"))?d.swap(a,bd,function(){return pb(a,b,f)}):pb(a,b,f):h},set:function(a,e,f){var g=f&&l.getComputedStyle(a,null);return nb(a,e,f?ob(a,b,f,d.support.boxSizing&&"border-box"===d.css(a,"boxSizing",!1,g),g):0)}}});d(function(){d.support.reliableMarginRight||(d.cssHooks.marginRight={get:function(a,b){return b?d.swap(a,{display:"inline-block"},oa,[a,"marginRight"]):h}});!d.support.pixelPosition&&d.fn.position&&d.each(["top","left"],function(a,b){d.cssHooks[b]=
{get:function(a,e){return e?(e=oa(a,b),Qa.test(e)?d(a).position()[b]+"px":e):h}}})});d.expr&&d.expr.filters&&(d.expr.filters.hidden=function(a){return 0>=a.offsetWidth&&0>=a.offsetHeight},d.expr.filters.visible=function(a){return!d.expr.filters.hidden(a)});d.each({margin:"",padding:"",border:"Width"},function(a,b){d.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"==typeof c?c.split(" "):[c];4>d;d++)f[a+ga[d]+b]=c[d]||c[d-2]||c[0];return f}};Yb.test(a)||(d.cssHooks[a+b].set=nb)});var cd=
/%20/g,pc=/\[\]$/,$b=/\r?\n/g,dd=/^(?:submit|button|image|reset|file)$/i,ed=/^(?:input|select|textarea|keygen)/i;d.fn.extend({serialize:function(){return d.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=d.prop(this,"elements");return a?d.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!d(this).is(":disabled")&&ed.test(this.nodeName)&&!dd.test(a)&&(this.checked||!Wb.test(a))}).map(function(a,b){var c=d(this).val();return null==c?null:
d.isArray(c)?d.map(c,function(a){return{name:b.name,value:a.replace($b,"\r\n")}}):{name:b.name,value:c.replace($b,"\r\n")}}).get()}});d.param=function(a,b){var c,e=[],f=function(a,b){b=d.isFunction(b)?b():null==b?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};if(b===h&&(b=d.ajaxSettings&&d.ajaxSettings.traditional),d.isArray(a)||a.jquery&&!d.isPlainObject(a))d.each(a,function(){f(this.name,this.value)});else for(c in a)Ra(c,a[c],b,f);return e.join("&").replace(cd,"+")};d.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),
function(a,b){d.fn[b]=function(a,d){return 0<arguments.length?this.on(b,null,a,d):this.trigger(b)}});d.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)},bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,d){return this.on(b,a,c,d)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});var na,ea,ib=d.now(),jb=/\?/,fd=/#.*$/,ac=/([?&])_=[^&]*/,gd=/^(.*?):[ \t]*([^\r\n]*)$/gm,
hd=/^(?:GET|HEAD)$/,id=/^\/\//,bc=/^([\w.+-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,cc=d.fn.load,dc={},Sa={},ec="*/".concat("*");try{ea=rc.href}catch(od){ea=x.createElement("a"),ea.href="",ea=ea.href}na=bc.exec(ea.toLowerCase())||[];d.fn.load=function(a,b,c){if("string"!=typeof a&&cc)return cc.apply(this,arguments);var e,f,g,j=this,k=a.indexOf(" ");return 0<=k&&(e=a.slice(k),a=a.slice(0,k)),d.isFunction(b)?(c=b,b=h):b&&"object"==typeof b&&(f="POST"),0<j.length&&d.ajax({url:a,type:f,dataType:"html",data:b}).done(function(a){g=
arguments;j.html(e?d("<div>").append(d.parseHTML(a)).find(e):a)}).complete(c&&function(a,b){j.each(c,g||[a.responseText,b,a])}),this};d.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){d.fn[b]=function(a){return this.on(b,a)}});d.extend({active:0,lastModified:{},etag:{},ajaxSettings:{url:ea,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(na[1]),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",
accepts:{"*":ec,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,"text html":!0,"text json":d.parseJSON,"text xml":d.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Ta(Ta(a,d.ajaxSettings),b):Ta(d.ajaxSettings,a)},ajaxPrefilter:sb(dc),ajaxTransport:sb(Sa),ajax:function(a,
b){function c(a,b,c,j){var p,n,t,E,w=b;if(2!==y){y=2;k&&clearTimeout(k);e=h;g=j||"";B.readyState=0<a?4:0;j=200<=a&&300>a||304===a;if(c){t=m;for(var N=B,H,z,C,J,K=t.contents,G=t.dataTypes;"*"===G[0];)G.shift(),H===h&&(H=t.mimeType||N.getResponseHeader("Content-Type"));if(H)for(z in K)if(K[z]&&K[z].test(H)){G.unshift(z);break}if(G[0]in c)C=G[0];else{for(z in c){if(!G[0]||t.converters[z+" "+G[0]]){C=z;break}J||(J=z)}C=C||J}t=C?(C!==G[0]&&G.unshift(C),c[C]):h}var I;a:{c=m;H=t;z=B;C=j;var F,M,L;t={};N=
c.dataTypes.slice();if(N[1])for(F in c.converters)t[F.toLowerCase()]=c.converters[F];for(J=N.shift();J;)if(c.responseFields[J]&&(z[c.responseFields[J]]=H),!L&&C&&c.dataFilter&&(H=c.dataFilter(H,c.dataType)),L=J,J=N.shift())if("*"===J)J=L;else if("*"!==L&&L!==J){if(F=t[L+" "+J]||t["* "+J],!F)for(I in t)if(M=I.split(" "),M[1]===J&&(F=t[L+" "+M[0]]||t["* "+M[0]])){!0===F?F=t[I]:!0!==t[I]&&(J=M[0],N.unshift(M[1]));break}if(!0!==F)if(F&&c["throws"])H=F(H);else try{H=F(H)}catch(O){I={state:"parsererror",
error:F?O:"No conversion from "+L+" to "+J};break a}}I={state:"success",data:H}}t=I;j?(m.ifModified&&(E=B.getResponseHeader("Last-Modified"),E&&(d.lastModified[f]=E),E=B.getResponseHeader("etag"),E&&(d.etag[f]=E)),204===a||"HEAD"===m.type?w="nocontent":304===a?w="notmodified":(w=t.state,p=t.data,n=t.error,j=!n)):(n=w,(a||!w)&&(w="error",0>a&&(a=0)));B.status=a;B.statusText=(b||w)+"";j?D.resolveWith(s,[p,w,B]):D.rejectWith(s,[B,w,n]);B.statusCode(x);x=h;l&&u.trigger(j?"ajaxSuccess":"ajaxError",[B,
m,j?p:n]);v.fireWith(s,[B,w]);l&&(u.trigger("ajaxComplete",[B,m]),--d.active||d.event.trigger("ajaxStop"))}}"object"==typeof a&&(b=a,a=h);b=b||{};var e,f,g,j,k,p,l,n,m=d.ajaxSetup({},b),s=m.context||m,u=m.context&&(s.nodeType||s.jquery)?d(s):d.event,D=d.Deferred(),v=d.Callbacks("once memory"),x=m.statusCode||{},E={},w={},y=0,H="canceled",B={readyState:0,getResponseHeader:function(a){var b;if(2===y){if(!j)for(j={};b=gd.exec(g);)j[b[1].toLowerCase()]=b[2];b=j[a.toLowerCase()]}return null==b?null:b},
getAllResponseHeaders:function(){return 2===y?g:null},setRequestHeader:function(a,b){var c=a.toLowerCase();return y||(a=w[c]=w[c]||a,E[a]=b),this},overrideMimeType:function(a){return y||(m.mimeType=a),this},statusCode:function(a){var b;if(a)if(2>y)for(b in a)x[b]=[x[b],a[b]];else B.always(a[B.status]);return this},abort:function(a){a=a||H;return e&&e.abort(a),c(0,a),this}};if(D.promise(B).complete=v.add,B.success=B.done,B.error=B.fail,m.url=((a||m.url||ea)+"").replace(fd,"").replace(id,na[1]+"//"),
m.type=b.method||b.type||m.method||m.type,m.dataTypes=d.trim(m.dataType||"*").toLowerCase().match(W)||[""],null==m.crossDomain&&(p=bc.exec(m.url.toLowerCase()),m.crossDomain=!(!p||p[1]===na[1]&&p[2]===na[2]&&(p[3]||("http:"===p[1]?"80":"443"))===(na[3]||("http:"===na[1]?"80":"443")))),m.data&&m.processData&&"string"!=typeof m.data&&(m.data=d.param(m.data,m.traditional)),tb(dc,m,b,B),2===y)return B;(l=m.global)&&0===d.active++&&d.event.trigger("ajaxStart");m.type=m.type.toUpperCase();m.hasContent=
!hd.test(m.type);f=m.url;m.hasContent||(m.data&&(f=m.url+=(jb.test(f)?"&":"?")+m.data,delete m.data),!1===m.cache&&(m.url=ac.test(f)?f.replace(ac,"$1_="+ib++):f+(jb.test(f)?"&":"?")+"_="+ib++));m.ifModified&&(d.lastModified[f]&&B.setRequestHeader("If-Modified-Since",d.lastModified[f]),d.etag[f]&&B.setRequestHeader("If-None-Match",d.etag[f]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&B.setRequestHeader("Content-Type",m.contentType);B.setRequestHeader("Accept",m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?
m.accepts[m.dataTypes[0]]+("*"!==m.dataTypes[0]?", "+ec+"; q=0.01":""):m.accepts["*"]);for(n in m.headers)B.setRequestHeader(n,m.headers[n]);if(m.beforeSend&&(!1===m.beforeSend.call(s,B,m)||2===y))return B.abort();H="abort";for(n in{success:1,error:1,complete:1})B[n](m[n]);if(e=tb(Sa,m,b,B)){B.readyState=1;l&&u.trigger("ajaxSend",[B,m]);m.async&&0<m.timeout&&(k=setTimeout(function(){B.abort("timeout")},m.timeout));try{y=1,e.send(E,c)}catch(z){if(!(2>y))throw z;c(-1,z)}}else c(-1,"No Transport");return B},
getJSON:function(a,b,c){return d.get(a,b,c,"json")},getScript:function(a,b){return d.get(a,h,b,"script")}});d.each(["get","post"],function(a,b){d[b]=function(a,e,f,g){return d.isFunction(e)&&(g=g||f,f=e,e=h),d.ajax({url:a,type:b,dataType:g,data:e,success:f})}});d.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/(?:java|ecma)script/},converters:{"text script":function(a){return d.globalEval(a),a}}});d.ajaxPrefilter("script",
function(a){a.cache===h&&(a.cache=!1);a.crossDomain&&(a.type="GET")});d.ajaxTransport("script",function(a){if(a.crossDomain){var b,c;return{send:function(e,f){b=d("<script>").prop({async:!0,charset:a.scriptCharset,src:a.url}).on("load error",c=function(a){b.remove();c=null;a&&f("error"===a.type?404:200,a.type)});x.head.appendChild(b[0])},abort:function(){c&&c()}}}});var fc=[],kb=/(=)\?(?=&|$)|\?\?/;d.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=fc.pop()||d.expando+"_"+ib++;return this[a]=
!0,a}});d.ajaxPrefilter("json jsonp",function(a,b,c){var e,f,g,j=!1!==a.jsonp&&(kb.test(a.url)?"url":"string"==typeof a.data&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&kb.test(a.data)&&"data");return j||"jsonp"===a.dataTypes[0]?(e=a.jsonpCallback=d.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback,j?a[j]=a[j].replace(kb,"$1"+e):!1!==a.jsonp&&(a.url+=(jb.test(a.url)?"&":"?")+a.jsonp+"="+e),a.converters["script json"]=function(){return g||d.error(e+" was not called"),
g[0]},a.dataTypes[0]="json",f=l[e],l[e]=function(){g=arguments},c.always(function(){l[e]=f;a[e]&&(a.jsonpCallback=b.jsonpCallback,fc.push(e));g&&d.isFunction(f)&&f(g[0]);g=f=h}),"script"):h});d.ajaxSettings.xhr=function(){try{return new XMLHttpRequest}catch(a){}};var va=d.ajaxSettings.xhr(),jd={"0":200,1223:204},kd=0,wa={};l.ActiveXObject&&d(l).on("unload",function(){for(var a in wa)wa[a]();wa=h});d.support.cors=!!va&&"withCredentials"in va;d.support.ajax=va=!!va;d.ajaxTransport(function(a){var b;
return d.support.cors||va&&!a.crossDomain?{send:function(c,d){var f,g,j=a.xhr();if(j.open(a.type,a.url,a.async,a.username,a.password),a.xhrFields)for(f in a.xhrFields)j[f]=a.xhrFields[f];a.mimeType&&j.overrideMimeType&&j.overrideMimeType(a.mimeType);a.crossDomain||c["X-Requested-With"]||(c["X-Requested-With"]="XMLHttpRequest");for(f in c)j.setRequestHeader(f,c[f]);b=function(a){return function(){b&&(delete wa[g],b=j.onload=j.onerror=null,"abort"===a?j.abort():"error"===a?d(j.status||404,j.statusText):
d(jd[j.status]||j.status,j.statusText,"string"==typeof j.responseText?{text:j.responseText}:h,j.getAllResponseHeaders()))}};j.onload=b();j.onerror=b("error");b=wa[g=kd++]=b("abort");j.send(a.hasContent&&a.data||null)},abort:function(){b&&b()}}:h});var pa,Pa,ld=/^(?:toggle|show|hide)$/,gc=RegExp("^(?:([+-])=|)("+Ea+")([a-z%]*)$","i"),md=/queueHooks$/,ya=[function(a,b,c){var e,f,g,j,k,p=this,l={},n=a.style,m=a.nodeType&&z(a),s=v.get(a,"fxshow");c.queue||(j=d._queueHooks(a,"fx"),null==j.unqueued&&(j.unqueued=
0,k=j.empty.fire,j.empty.fire=function(){j.unqueued||k()}),j.unqueued++,p.always(function(){p.always(function(){j.unqueued--;d.queue(a,"fx").length||j.empty.fire()})}));1===a.nodeType&&("height"in b||"width"in b)&&(c.overflow=[n.overflow,n.overflowX,n.overflowY],"inline"===d.css(a,"display")&&"none"===d.css(a,"float")&&(n.display="inline-block"));c.overflow&&(n.overflow="hidden",p.always(function(){n.overflow=c.overflow[0];n.overflowX=c.overflow[1];n.overflowY=c.overflow[2]}));for(e in b)if(f=b[e],
ld.exec(f)){if(delete b[e],g=g||"toggle"===f,f===(m?"hide":"show")){if("show"!==f||!s||s[e]===h)continue;m=!0}l[e]=s&&s[e]||d.style(a,e)}if(!d.isEmptyObject(l))for(e in s?"hidden"in s&&(m=s.hidden):s=v.access(a,"fxshow",{}),g&&(s.hidden=!m),m?d(a).show():p.done(function(){d(a).hide()}),p.done(function(){var b;v.remove(a,"fxshow");for(b in l)d.style(a,b,l[b])}),l)b=vb(m?s[e]:0,e,p),e in s||(s[e]=b.start,m&&(b.end=b.start,b.start="width"===e||"height"===e?1:0))}],ta={"*":[function(a,b){var c=this.createTween(a,
b),e=c.cur(),f=gc.exec(b),g=f&&f[3]||(d.cssNumber[a]?"":"px"),j=(d.cssNumber[a]||"px"!==g&&+e)&&gc.exec(d.css(c.elem,a)),h=1,k=20;if(j&&j[3]!==g){g=g||j[3];f=f||[];j=+e||1;do h=h||".5",j/=h,d.style(c.elem,a,j+g);while(h!==(h=c.cur()/e)&&1!==h&&--k)}return f&&(j=c.start=+j||+e||0,c.unit=g,c.end=f[1]?j+(f[1]+1)*f[2]:+f[2]),c}]};d.Animation=d.extend(wb,{tweener:function(a,b){d.isFunction(a)?(b=a,a=["*"]):a=a.split(" ");for(var c,e=0,f=a.length;f>e;e++)c=a[e],ta[c]=ta[c]||[],ta[c].unshift(b)},prefilter:function(a,
b){b?ya.unshift(a):ya.push(a)}});d.Tween=L;L.prototype={constructor:L,init:function(a,b,c,e,f,g){this.elem=a;this.prop=c;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(d.cssNumber[c]?"":"px")},cur:function(){var a=L.propHooks[this.prop];return a&&a.get?a.get(this):L.propHooks._default.get(this)},run:function(a){var b,c=L.propHooks[this.prop];return this.pos=b=this.options.duration?d.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):
a,this.now=(this.end-this.start)*b+this.start,this.options.step&&this.options.step.call(this.elem,this.now,this),c&&c.set?c.set(this):L.propHooks._default.set(this),this}};L.prototype.init.prototype=L.prototype;L.propHooks={_default:{get:function(a){var b;return null==a.elem[a.prop]||a.elem.style&&null!=a.elem.style[a.prop]?(b=d.css(a.elem,a.prop,""),b&&"auto"!==b?b:0):a.elem[a.prop]},set:function(a){d.fx.step[a.prop]?d.fx.step[a.prop](a):a.elem.style&&(null!=a.elem.style[d.cssProps[a.prop]]||d.cssHooks[a.prop])?
d.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};L.propHooks.scrollTop=L.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};d.each(["toggle","show","hide"],function(a,b){var c=d.fn[b];d.fn[b]=function(a,d,g){return null==a||"boolean"==typeof a?c.apply(this,arguments):this.animate(za(b,!0),a,d,g)}});d.fn.extend({fadeTo:function(a,b,c,d){return this.filter(z).css("opacity",0).show().end().animate({opacity:b},a,c,d)},animate:function(a,b,c,e){var f=
d.isEmptyObject(a),g=d.speed(b,c,e);b=function(){var b=wb(this,d.extend({},a),g);(f||v.get(this,"finish"))&&b.stop(!0)};return b.finish=b,f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,c){var e=function(a){var b=a.stop;delete a.stop;b(c)};return"string"!=typeof a&&(c=b,b=a,a=h),b&&!1!==a&&this.queue(a||"fx",[]),this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",j=d.timers,h=v.get(this);if(g)h[g]&&h[g].stop&&e(h[g]);else for(g in h)h[g]&&h[g].stop&&md.test(g)&&e(h[g]);for(g=
j.length;g--;)j[g].elem!==this||null!=a&&j[g].queue!==a||(j[g].anim.stop(c),b=!1,j.splice(g,1));(b||!c)&&d.dequeue(this,a)})},finish:function(a){return!1!==a&&(a=a||"fx"),this.each(function(){var b,c=v.get(this),e=c[a+"queue"];b=c[a+"queueHooks"];var f=d.timers,g=e?e.length:0;c.finish=!0;d.queue(this,a,[]);b&&b.stop&&b.stop.call(this,!0);for(b=f.length;b--;)f[b].elem===this&&f[b].queue===a&&(f[b].anim.stop(!0),f.splice(b,1));for(b=0;g>b;b++)e[b]&&e[b].finish&&e[b].finish.call(this);delete c.finish})}});
d.each({slideDown:za("show"),slideUp:za("hide"),slideToggle:za("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){d.fn[a]=function(a,d,f){return this.animate(b,a,d,f)}});d.speed=function(a,b,c){var e=a&&"object"==typeof a?d.extend({},a):{complete:c||!c&&b||d.isFunction(a)&&a,duration:a,easing:c&&b||b&&!d.isFunction(b)&&b};return e.duration=d.fx.off?0:"number"==typeof e.duration?e.duration:e.duration in d.fx.speeds?d.fx.speeds[e.duration]:d.fx.speeds._default,
(null==e.queue||!0===e.queue)&&(e.queue="fx"),e.old=e.complete,e.complete=function(){d.isFunction(e.old)&&e.old.call(this);e.queue&&d.dequeue(this,e.queue)},e};d.easing={linear:function(a){return a},swing:function(a){return 0.5-Math.cos(a*Math.PI)/2}};d.timers=[];d.fx=L.prototype.init;d.fx.tick=function(){var a,b=d.timers,c=0;for(pa=d.now();b.length>c;c++)a=b[c],a()||b[c]!==a||b.splice(c--,1);b.length||d.fx.stop();pa=h};d.fx.timer=function(a){a()&&d.timers.push(a)&&d.fx.start()};d.fx.interval=13;
d.fx.start=function(){Pa||(Pa=setInterval(d.fx.tick,d.fx.interval))};d.fx.stop=function(){clearInterval(Pa);Pa=null};d.fx.speeds={slow:600,fast:200,_default:400};d.fx.step={};d.expr&&d.expr.filters&&(d.expr.filters.animated=function(a){return d.grep(d.timers,function(b){return a===b.elem}).length});d.fn.offset=function(a){if(arguments.length)return a===h?this:this.each(function(b){d.offset.setOffset(this,a,b)});var b,c,e=this[0],f={top:0,left:0},g=e&&e.ownerDocument;if(g)return b=g.documentElement,
d.contains(b,e)?(typeof e.getBoundingClientRect!==Ba&&(f=e.getBoundingClientRect()),c=d.isWindow(g)?g:9===g.nodeType&&g.defaultView,{top:f.top+c.pageYOffset-b.clientTop,left:f.left+c.pageXOffset-b.clientLeft}):f};d.offset={setOffset:function(a,b,c){var e,f,g,j,h,k,p=d.css(a,"position"),n=d(a),m={};"static"===p&&(a.style.position="relative");h=n.offset();g=d.css(a,"top");k=d.css(a,"left");("absolute"===p||"fixed"===p)&&-1<(g+k).indexOf("auto")?(e=n.position(),j=e.top,f=e.left):(j=parseFloat(g)||0,
f=parseFloat(k)||0);d.isFunction(b)&&(b=b.call(a,c,h));null!=b.top&&(m.top=b.top-h.top+j);null!=b.left&&(m.left=b.left-h.left+f);"using"in b?b.using.call(a,m):n.css(m)}};d.fn.extend({position:function(){if(this[0]){var a,b,c=this[0],e={top:0,left:0};return"fixed"===d.css(c,"position")?b=c.getBoundingClientRect():(a=this.offsetParent(),b=this.offset(),d.nodeName(a[0],"html")||(e=a.offset()),e.top+=d.css(a[0],"borderTopWidth",!0),e.left+=d.css(a[0],"borderLeftWidth",!0)),{top:b.top-e.top-d.css(c,"marginTop",
!0),left:b.left-e.left-d.css(c,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||yb;a&&!d.nodeName(a,"html")&&"static"===d.css(a,"position");)a=a.offsetParent;return a||yb})}});d.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var c="pageYOffset"===b;d.fn[a]=function(e){return d.access(this,function(a,e,j){var k=d.isWindow(a)?a:9===a.nodeType&&a.defaultView;return j===h?k?k[b]:a[e]:(k?k.scrollTo(c?l.pageXOffset:j,c?j:l.pageYOffset):
a[e]=j,h)},a,e,arguments.length,null)}});d.each({Height:"height",Width:"width"},function(a,b){d.each({padding:"inner"+a,content:b,"":"outer"+a},function(c,e){d.fn[e]=function(e,g){var j=arguments.length&&(c||"boolean"!=typeof e),k=c||(!0===e||!0===g?"margin":"border");return d.access(this,function(b,c,e){var f;return d.isWindow(b)?b.document.documentElement["client"+a]:9===b.nodeType?(f=b.documentElement,Math.max(b.body["scroll"+a],f["scroll"+a],b.body["offset"+a],f["offset"+a],f["client"+a])):e===
h?d.css(b,c,k):d.style(b,c,e,k)},b,j?e:h,j,null)}})});d.fn.size=function(){return this.length};d.fn.andSelf=d.fn.addBack;"object"==typeof module&&module&&"object"==typeof module.exports?module.exports=d:"function"==typeof define&&define.amd&&define("jquery",[],function(){return d});"object"==typeof l&&"object"==typeof l.document&&(l.jQuery=l.$=d)})(window);
(function(){var l=[].slice,h=window,p;p=function(k,p,s){var u,D,E,H,J;3>arguments.length&&(u=[h].concat(l.call(arguments)),k=u[0],p=u[1],s=u[2]);D=k;J=p.split(".");E=0;for(H=J.length;E<H;E++)u=J[E],k=k[u]||(k[u]={});return s(k,D)};p("__spider",function(h){return h.namespace=p});__spider.$=jQuery.noConflict(!0)}).call(this);
(function(){__spider.namespace("__spider.utils",function(l){l.element=function(h,p){var k,n;n=h.tagName.toLowerCase();if(p)return n;var l=h.id||"",u,D,E,H;E=h.classList;H=[];u=0;for(D=E.length;u<D;u++)k=E[u],H.push(k);return{name:n,id:l,classes:H.sort()}};l.path=function(h,p){var k;for(k=[];h&&h!==document.body;)k.splice(0,0,l.element(h,p)),h=h.parentElement;return k};l.bound=function(h){var p,k;k=document.documentElement.scrollTop||document.body.scrollTop;p=document.documentElement.scrollLeft||document.body.scrollLeft;
h=h.getBoundingClientRect();return{width:h.width,height:h.height,left:h.left+p,top:h.top+k}};return l.computed=function(h){var p,k,l,s,u;k=document.defaultView.getComputedStyle(document.body);h=document.defaultView.getComputedStyle(h);p={};s=0;for(u=h.length;s<u;s++)l=h[s],"width"===l||("height"===l||"top"===l||"left"===l||"right"===l||"bottom"===l)||"-"!==l.charAt(0)&&h[l]!==k[l]&&(p[l]=h[l]);return p}})}).call(this);
(function(){__spider.namespace("__spider.extractor",function(l){l.extract_meta=function(){var h,p,k,l,s,u;s=document.querySelectorAll("title");u=[];k=0;for(l=s.length;k<l;k++)p=s[k],u.push(p.innerText);l=document.querySelectorAll('meta[name="description"]');s=[];p=0;for(k=l.length;p<k;p++)h=l[p],s.push(h.content);u.push.apply(u,function(){var k,p,l,n;l=document.querySelectorAll('meta[name="og:title"], meta[property="og:title"]');n=[];k=0;for(p=l.length;k<p;k++)h=l[k],n.push(h.content);return n}());
s.push.apply(s,function(){var k,p,l,n;l=document.querySelectorAll('meta[name="og:description"], meta[property="og:description"]');n=[];k=0;for(p=l.length;k<p;k++)h=l[k],n.push(h.content);return n}());u.push.apply(u,function(){var k,p,l,n;l=document.querySelectorAll('meta[name="twitter:title"], meta[property="twitter:title"]');n=[];k=0;for(p=l.length;k<p;k++)h=l[k],n.push(h.content);return n}());s.push.apply(s,function(){var k,l,p,n;p=document.querySelectorAll('meta[name="twitter:description"], meta[property="twitter:description"]');
n=[];k=0;for(l=p.length;k<l;k++)h=p[k],n.push(h.content);return n}());return{url:window.location.href,titles:u,descriptions:s}};l.extract_body=function(){var h,p,k,l,s;h={};s=document.defaultView.getComputedStyle(document.body);k=0;for(l=s.length;k<l;k++)p=s[k],"-"!==p.charAt(0)&&(h[p]=document.defaultView.getComputedStyle(document.body)[p]);return{scroll:{top:document.documentElement.scrollTop||document.body.scrollTop,left:document.documentElement.scrollLeft||document.body.scrollLeft},bound:__spider.utils.bound(document.body),
computed:h}};l.extract_links=function(){var h,l,k,n,s;n=document.querySelectorAll("a[href]");s=[];l=0;for(k=n.length;l<k;l++)h=n[l],s.push(h.href);return s};l.extract_texts=function(){var h,l,k,n,s;n=[];for(s=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,null,!1);k=s.nextNode();)if(0<k.nodeValue.trim().length&&(l=k.parentElement,h=__spider.utils.bound(l),0<h.width*h.height)){for(;l;){h=document.defaultView.getComputedStyle(l);if(0<parseInt(h.width)*parseInt(h.height))break;l=l.parentElement}l&&
(l.__spider?l.__spider.text.push(k.nodeValue):(l.__spider={element:__spider.utils.element(l),path:__spider.utils.path(l,!0),selector:__spider.utils.path(l),text:[k.nodeValue],html:l.innerHTML,bound:__spider.utils.bound(l),computed:__spider.utils.computed(l)},n.push(l.__spider)))}return n};l.extract_images=function(){var h,l,k,n,s,u;l=[];u=document.querySelectorAll("img[src]");n=0;for(s=u.length;n<s;n++)k=u[n],h=__spider.utils.bound(k),0<h.width*h.height&&l.push({src:k.src,element:__spider.utils.element(k),
path:__spider.utils.path(k,!0),selector:__spider.utils.path(k),bound:h,computed:__spider.utils.computed(k)});return l};return l.extract=function(){var h;h=l.extract_meta();h.body=l.extract_body();h.links=l.extract_links();h.texts=l.extract_texts();h.images=l.extract_images();return h}})}).call(this);
(function(){__spider.namespace("__spider.ui",function(l){var h;h=function(){var h;h=__spider.$("div#__spider");if(h.length)return h;h=__spider.$("<div />");h.attr({id:"__spider"});h.css({position:"fixed",zIndex:999999999,top:15,left:15,background:"#2f96b4",color:"white",fontFamily:'"Helvetica Neue", Helvetica, Arial, sans-serif',fontSize:"14px",lineHeight:"20px",fontWeight:"bold",padding:"10px 15px"});h.text("Loading ...");h.insertBefore(__spider.$(document.body));return h};l.info=function(l){var k;
k=h();k.css({background:"#2f96b4"});return k.html(l)};l.success=function(l){var k;k=h();k.css({background:"#51a351"});return k.html(l)};return l.error=function(l){var k;k=h();k.css({background:"#da4f49"});return k.html(l)}})}).call(this);
(function(){__spider.namespace("__spider.capture",function(l){var h,p;p=function(h){h=__spider.$.ajax({type:"POST",url:window.__spider_url+"/capture",dataType:"json",data:JSON.stringify(h)});h.done(function(){return __spider.ui.success("Done! :)")});return h.error(function(h,k){return __spider.ui.error("Something went wrong while uploading data: "+k)})};h=function(){var h;h=__spider.extractor.extract();__spider.ui.info("Uploading ...");return setTimeout(function(){return p(h)},50)};return l.run=function(){if(window.__spider_url)return __spider.ui.info("Capturing ..."),
setTimeout(h,50);__spider.ui.error("Bookmarklet outdated!")}});__spider.$(function(){return __spider.capture.run()})}).call(this);
